# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"
generics:
  - name: Service
    namespace: Infra
    description: "Services"
    default_filter: name__value
    order_by:
      - name__value
    display_labels:
      - name__value
    attributes:
      - name: name
        kind: Text
        label: Name
        optional: false
        order_weight: 1
      - name: description
        kind: Text
        order_weight: 2
        optional: true
      - name: status
        order_weight: 3
        optional: false
        kind: Dropdown
        choices:
          - name: provisioning
            label: Provisioning
            description: "In the process of being set up and configured."
            color: "#ffff7f"
          - name: active
            label: Active
            description: "Fully operational and currently in service."
            color: "#7fbf7f"
          - name: decommissioning
            label: Decommissioning
            description: "In the process of beeing taken out of service."
            color: "#fbfbfb"
          - name: decommissioned
            label: Decommissioned
            description: "Taken out of service."
            color: "#bfbfbf"
nodes:
  - name: BackBoneService
    namespace: Infra
    label: "Backbone Service"
    description: "Backbone service attached to a Topology."
    icon: "carbon:container-services"
    inherit_from:
      - InfraService
    uniqueness_constraints:
      - ["circuit_id__value", "internal_circuit_id__value"]
    attributes:
      - name: circuit_id
        kind: Text
        label: Circuit ID
        optional: false
        order_weight: 3
      - name: internal_circuit_id
        kind: Text
        label: Internal Circuit ID
        optional: false
        order_weight: 2
    relationships:
      - name: provider
        cardinality: one
        peer: OrganizationProvider
        optional: false
        kind: Attribute
      - name: site_a
        label: Site A
        cardinality: one
        peer: LocationSite
        optional: false
        identifier: infrabackboneservice__location_site_a
        kind: Attribute
        order_weight: 4
      - name: site_b
        label: Site B
        cardinality: one
        peer: LocationSite
        optional: false
        identifier: infrabackboneservice__location_site_b
        kind: Attribute
        order_weight: 5
  - name: Layer2NetworkService
    namespace: Infra
    description: "Layer 2 network service attached to a Topology."
    label: Layer2 Network Service
    icon: "carbon:ibm-cloud-internet-services"
    inherit_from:
      - InfraService
    relationships:
      - name: vlan
        peer: InfraVLAN
        cardinality: one
        kind: Component
        order_weight: 1500
        optional: true

  - name: Layer3NetworkService
    namespace: Infra
    description: "Layer 3 network service attached to a Topology."
    label: Layer3 Network Service
    icon: "carbon:ibm-cloud-internet-services"
    inherit_from:
      - InfraService
    relationships:
      - name: prefix
        peer: IpamIPPrefix
        cardinality: one
        kind: Component
        order_weight: 1400
        optional: true
      - name: vlan
        peer: InfraVLAN
        cardinality: one
        kind: Component
        order_weight: 1500
        optional: true

# extensions:
#   nodes:
#     - kind: InfraVLAN
#       relationships:
#         - name: network_service
#           peer: InfraService
#           optional: true
#           cardinality: one
#           kind: Attribute
#           order_weight: 1400