query device_replace($name: String!, $device_type: String!, $role: String!) {
  DcimPhysicalDevice(name__value: $name) {
    edges {
      node {
        id
        name { value }
        role { value }
        device_type { value }
        object_template { id }
        interfaces {
          edges {
            node {
              id
              name { value }
              role { value }
              interface_type { value }
              status { value }
              ip_address {
                id
                address { value }
              }
              cable { id }
              interface_services {
                edges {
                  node {
                    id
                    name { value }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  TemplateDcimPhysicalDevice(device_type__value: $device_type, role__value: $role) {
    edges {
      node {
        id
        template_name: name { value }
        status { value }
        device_type { value }
        role { value }
        platform { value }
        interfaces {
          edges {
            node {
              id
              name { value }
              role { value }
              interface_type { value }
              status { value }
            }
          }
        }
      }
    }
  }
}
