query edge_config($device: String!) {
  DcimGenericDevice(name__value: $device) {
    edges {
      node {
        name { value }
        device_services {
          count
          edges {
            node {
              __typename
              name { value }
              ... on ServiceBGP {
                local_ip { node { address { value } } }
                local_as { node { asn { value } } }
                remote_ip { node { address { value } } }
                remote_as { node { asn { value } } }
                peer_group {
                  node {
                    name { value }
                    local_pref { value }
                    send_community { value }
                    maximum_routes { value }
                  }
                }
              }
              ... on ServiceOSPF {
                router_id { node { address { value } } }
                area {
                  node {
                    area { value }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name { value }
              description { value }
              status { value }
              role { value }
              ... on DcimPhysicalInterface {
                ip_addresses {
                  edges {
                    node {
                      address { value }
                      ip_namespace { node { name { value } } }
                    }
                  }
                }
              }
              ... on DcimVirtualInterface {
                ip_addresses {
                  edges {
                    node {
                      address { value }
                      ip_namespace { node { name { value } } }
                    }
                  }
                }
              }
              interface_services {
                edges {
                  node {
                    ... on ServiceNetworkSegment {
                      __typename
                      vlan_id { value }
                      status { value }
                      prefix {  node { prefix { value } } }
                    }
                    ... on ServiceOSPF {
                      __typename
                      router_id { node { address { value } } }
                      area { node { area { value } } }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
