query edge_config($device: String!) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        __typename
        id
        name { value }
        role { value }
        device_type {
          node {
            name { value }
            manufacturer { node { name { value } } }
          }
        }
        platform {
          node {
            name { value }
          }
        }
        primary_address {
          node {
            address { value }
            ip_namespace { node { name { value } } }
          }
        }
        tags {
          edges {
            node { name { value } }
          }
        }

        # Device Services (BGP, OSPF) with nested peerings
        ...DeviceCapabilitiesOnDeviceFields

        # Interface Information
        interfaces {
          edges {
            node {
              __typename
              name { value }
              description { value }
              status { value }
              role { value }
              ... on DcimPhysicalInterface {
                interface_type { value }
                mtu { value }
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
                cable {
                  node {
                    id
                    endpoints {
                      edges {
                        node {
                          __typename
                          ... on DcimPhysicalInterface {
                            name { value }
                            ip_address {
                              node {
                                address { value }
                              }
                            }
                            device {
                              node {
                                name { value }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }

              ... on DcimVirtualInterface {
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
              }

              ... on DcimLAGInterface {
                lag_id { value }
                lacp_mode { value }
                mtu { value }
                minimum_links { value }
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
                member_interfaces {
                  edges {
                    node {
                      name { value }
                    }
                  }
                }
              }
              ...InterfaceCapabilitiesWithSegmentOnInterfaceFields
            }
          }
        }
      }
    }
  }
}
