query edge_config($device: String!) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        __typename
        id
        name { value }
        role { value }
        device_type {
          node {
            name { value }
            manufacturer { node { name { value } } }
          }
        }
        platform {
          node {
            name { value }
          }
        }
        primary_address {
          node {
            address { value }
            ip_namespace { node { name { value } } }
          }
        }
        tags {
          edges {
            node { name { value } }
          }
        }

        # Enhanced BGP Services with Peer Groups
        device_services {
          edges {
            node {
              __typename
              name { value }
              status { value }

              ... on ManagedBGP {
                session_type { value }
                multipath { value }
                graceful_restart { value }
                local_ip { node { address { value } } }
                local_as { node { asn { value } } }
                remote_ip { node { address { value } } }
                remote_as { node { asn { value } } }
                router_id { node { address { value } } }

                # CRITICAL: BGP Peer Group Information
                peer_group {
                  node {
                    name { value }
                    description { value }
                    peer_group_type { value }
                    bfd_enabled { value }
                    ebgp_multihop { value }
                    send_community { value }
                    send_community_extended { value }
                    route_reflector_client { value }
                    password { value }
                    maximum_routes { value }
                    local_pref { value }
                  }
                }
              }
              ... on ManagedPIM {
                dr_priority { value }
                rp_mode { value }
                rp_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
              }
              ... on ManagedOSPF {
                process_id { value }
                version { value }
                router_type { value }
                reference_bandwidth { value }
                router_id { node { address { value } } }
                area {
                  node {
                    area { value }
                    name { value }
                    area_type { value }
                    description { value }
                  }
                }
              }
            }
          }
        }

        # Enhanced Interface Information
        interfaces {
          edges {
            node {
              __typename
              name { value }
              description { value }
              status { value }
              role { value }
              ... on DcimPhysicalInterface {
                interface_type { value }
                mtu { value }
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
              }

              ... on DcimVirtualInterface {
                ip_addresses {
                  edges {
                    node {
                      address { value }
                      ip_namespace { node { name { value } } }
                    }
                  }
                }
              }
              interface_services {
                edges {
                  node {
                    __typename
                    ... on ManagedOSPF {
                      area { node { area { value } } }
                      ospf_interface_profile {
                        node {
                          metric { value }
                          mode { value }
                          authentication_mode { value }
                          authentication_key { value }
                        }
                      }
                    }
                    ... on ManagedNetworkSegment {
                      vlan_id { value }
                      name { value }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}