query leaf_config(
  $device: String!
  $segment_status_values: [String!] = ["active", "provisioning"]
) {
  DcimDevice(name__value: $device) {
    edges {
      node {
        __typename
        id
        name { value }
        role { value }
        platform {
          node {
            name { value }
            netmiko_device_type { value }
          }
        }
        primary_address {
          node {
            address { value }
            ip_namespace { node { name { value } } }
          }
        }
        tags {
          edges {
            node { name { value } }
          }
        }

        # Device Services (BGP, OSPF) with nested peerings
        ... on DcimCapabilities {
          ...DeviceCapabilitiesFields
        }

        # Interface Information
        interfaces {
          edges {
            node {
              __typename
              name { value }
              description { value }
              status { value }
              role { value }
              ... on DcimPhysicalInterface {
                interface_type { value }
                mtu { value }
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
                cable {
                  node {
                    id
                    endpoints {
                      edges {
                        node {
                          __typename
                          ... on DcimPhysicalInterface {
                            name { value }
                            ip_address {
                              node {
                                address { value }
                              }
                            }
                            device {
                              node {
                                name { value }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }

              ... on DcimVirtualInterface {
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
              }

              ... on DcimLAGInterface {
                lag_id { value }
                lacp_mode { value }
                mtu { value }
                minimum_links { value }
                ip_address {
                  node {
                    address { value }
                    ip_namespace { node { name { value } } }
                  }
                }
                mlag_domain {
                  node {
                    id
                    name { value }
                  }
                }
                member_interfaces {
                  edges {
                    node {
                      name { value }
                    }
                  }
                }
              }
              ...InterfaceCapabilitiesWithSegmentFields
            }
          }
        }
      }
    }
  }

}

fragment NetworkSegmentFields on ManagedNetworkSegment {
  ... on ManagedVlanSegment {
    ...SegmentBaseFields
    ...SegmentDeploymentsActiveFields
    ...SegmentGatewayWithNamespaceFields
    ...SecurityPolicyFields
  }
  ... on ManagedVxlanSegment {
    ...SegmentBaseFields
    arp_suppression { value }
    ...SegmentDeploymentsActiveFields
    ...SegmentGatewayWithNamespaceFields
    ...SecurityPolicyFields
  }
}

# SecurityPolicyFields is spread inside each concrete segment type (ManagedVlan/VxlanSegment).
fragment SecurityPolicyFields on ManagedNetworkSegment {
  inline_service {
    node { id name { value } }
  }
  isolation_mode { value }
  security_tag {
    node {
      name { value }
      group_id { value }
      rules_as_source {
        edges {
          node {
            action { value }
            log { value }
            destination_tag {
              node {
                name { value }
                group_id { value }
              }
            }
          }
        }
      }
    }
  }
}
