query leaf_config($device: String!) {
  physical: DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_type {
          node {
            platform {
              node {
                netmiko_device_type {
                  value
                }
              }
            }
            manufacturer {
              node {
                name {
                  value
                }
              }
            }
          }
        }

        device_service {
          count
          edges {
            node {
              __typename
              name {
                value
              }
              ... on ServiceBGP {
                session_type {
                  value
                }
                local_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                local_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                remote_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                remote_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                router_id {
                  node {
                    address {
                      value
                    }
                  }
                }
                status {
                  value
                }
                description {
                  value
                }
                device {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
              ... on ServiceOSPF {
                router_id {
                  node {
                    address {
                      value
                    }
                  }
                }
                area {
                  node {
                    area {
                      value
                    }
                    name {
                      value
                    }
                  }
                }
                version {
                  value
                }
                status {
                  value
                }
                device {
                  node {
                    name {
                      value
                    }
                  }
                }
                ospf_interface {
                  edges {
                    node {
                      name {
                        value
                      }
                      role {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status {
                value
              }
              role {
                value
              }
              ... on DcimPhysicalInterface {
                connector {
                  node {
                    ... on DcimPhysicalInterface {
                      name {
                        value
                      }
                      device {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                      ip_namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
              ... on DcimVirtualInterface {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                      ip_namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
              service {
                edges {
                  node {
                    __typename
                    ... on ServiceNetworkSegment {
                      name {
                        value
                      }
                      vni {
                        value
                      }
                      status {
                        value
                      }
                      description {
                        value
                      }
                      segment_type {
                        value
                      }
                      tenant_isolation {
                        value
                      }
                      # Security attributes
                      security_enforcement {
                        value
                      }
                      default_deny_all {
                        value
                      }
                      enable_logging {
                        value
                      }
                      # Security relationships
                      security_zone {
                        node {
                          name {
                            value
                          }
                          trust_level {
                            value
                          }
                          isolation_level {
                            value
                          }
                          description {
                            value
                          }
                        }
                      }
                      security_profile {
                        node {
                          name {
                            value
                          }
                          description {
                            value
                          }
                          default_action {
                            value
                          }
                          enable_micro_segmentation {
                            value
                          }
                          enable_dhcp_snooping {
                            value
                          }
                          enable_arp_inspection {
                            value
                          }
                          max_mac_addresses {
                            value
                          }
                          allowed_protocols {
                            edges {
                              node {
                                name {
                                  value
                                }
                              }
                            }
                          }
                          blocked_protocols {
                            edges {
                              node {
                                name {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                      access_control_lists {
                        edges {
                          node {
                            name {
                              value
                            }
                            description {
                              value
                            }
                            acl_type {
                              value
                            }
                            rules {
                              edges {
                                node {
                                  index {
                                    value
                                  }
                                  name {
                                    value
                                  }
                                  action {
                                    value
                                  }
                                  direction {
                                    value
                                  }
                                  log {
                                    value
                                  }
                                  description {
                                    value
                                  }
                                  source_addresses {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                  destination_addresses {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                  services {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                      customer {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      prefixes {
                        edges {
                          node {
                            prefix {
                              value
                            }
                          }
                        }
                      }
                      vxlan_services {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }

      }
    }
  }
  virtual: DcimVirtualDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_type {
          node {
            platform {
              node {
                netmiko_device_type {
                  value
                }
              }
            }
            manufacturer {
              node {
                name {
                  value
                }
              }
            }
          }
        }

        device_service {
          count
          edges {
            node {
              __typename
              name {
                value
              }
              ... on ServiceBGP {
                session_type {
                  value
                }
                local_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                local_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                remote_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                remote_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                router_id {
                  node {
                    address {
                      value
                    }
                  }
                }
                status {
                  value
                }
                description {
                  value
                }
              }
              ... on ServiceOSPF {
                router_id {
                  node {
                    address {
                      value
                    }
                  }
                }
                area {
                  node {
                    area {
                      value
                    }
                    name {
                      value
                    }
                  }
                }
                version {
                  value
                }
                status {
                  value
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status {
                value
              }
              role {
                value
              }
              ... on DcimVirtualInterface {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                      ip_namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
              service {
                edges {
                  node {
                    __typename
                    ... on ServiceNetworkSegment {
                      name {
                        value
                      }
                      vni {
                        value
                      }
                      status {
                        value
                      }
                      description {
                        value
                      }
                      segment_type {
                        value
                      }
                      tenant_isolation {
                        value
                      }
                      # Security attributes
                      security_enforcement {
                        value
                      }
                      default_deny_all {
                        value
                      }
                      enable_logging {
                        value
                      }
                      # Security relationships
                      security_zone {
                        node {
                          name {
                            value
                          }
                          trust_level {
                            value
                          }
                          isolation_level {
                            value
                          }
                          description {
                            value
                          }
                        }
                      }
                      security_profile {
                        node {
                          name {
                            value
                          }
                          description {
                            value
                          }
                          default_action {
                            value
                          }
                          enable_micro_segmentation {
                            value
                          }
                          enable_dhcp_snooping {
                            value
                          }
                          enable_arp_inspection {
                            value
                          }
                          max_mac_addresses {
                            value
                          }
                          allowed_protocols {
                            edges {
                              node {
                                name {
                                  value
                                }
                              }
                            }
                          }
                          blocked_protocols {
                            edges {
                              node {
                                name {
                                  value
                                }
                              }
                            }
                          }
                        }
                      }
                      access_control_lists {
                        edges {
                          node {
                            name {
                              value
                            }
                            description {
                              value
                            }
                            acl_type {
                              value
                            }
                            rules {
                              edges {
                                node {
                                  index {
                                    value
                                  }
                                  name {
                                    value
                                  }
                                  action {
                                    value
                                  }
                                  direction {
                                    value
                                  }
                                  log {
                                    value
                                  }
                                  description {
                                    value
                                  }
                                  source_addresses {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                  destination_addresses {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                  services {
                                    edges {
                                      node {
                                        name {
                                          value
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                      customer {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      prefixes {
                        edges {
                          node {
                            prefix {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
