query loadbalancer_cloud($instance: String!) {
  CloudLoadBalancer(name__value: $instance) {
    edges {
      node {
        id
        name { value }
        lb_type { value }
        scheme { value }
        virtual_network {
          node {
            id
            name { value }
            account {
              node {
                name { value }
                provider {
                  node { name { value } }
                }
              }
            }
          }
        }
        network_segments {
          edges {
            node {
              id
              name { value }
              availability_zone {
                node { name { value } }
              }
            }
          }
        }
      }
    }
  }

  LoadbalancerVIP(load_balancer__name__value: $instance) {
    edges {
      node {
        id
        hostname { value }
        protocol { value }
        port { value }
        ssl_certificate { value }
        load_balancing_algorithm { value }
        session_persistence { value }
        health_checks {
          edges {
            node {
              check { value }
              rise { value }
              fall { value }
              timeout { value }
            }
          }
        }
        members {
          edges {
            node {
              name { value }
              weight { value }
              pool_interfaces {
                edges {
                  node {
                    port { value }
                    ip_address { node { address { value } } }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
