query proxy_config($device: String!) {
  DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name { value }
        platform {
          node {
            name { value }
            netmiko_device_type { value }
            napalm_driver { value }
            ansible_network_os { value }
          }
        }
        ... on DcimCapabilities {
        capabilities {
          edges {
            node {
              __typename
              ... on ManagedGeneric {
                name { value }
                status { value }
              }
              ... on ManagedProxyHA {
                name { value }
                group_id { value }
                mode { value }
                priority { value }
                preempt { value }
                proxy_type { value }
                proxy_vendor { value }
                capabilities { edges { node { name { value } } } }
              }
            }
          }
        }
        }
        interfaces {
          edges {
            node {
              __typename
              name { value }
              description { value }
              status { value }
              role { value }
              ... on DcimPhysicalInterface {
                ip_address { node { address { value } ip_namespace { node { name { value } } } } }
              }
              ... on DcimVirtualInterface {
                ip_address { node { address { value } ip_namespace { node { name { value } } } } }
                parent_interface { node { name { value } } }
              }
            }
          }
        }
      }
    }
  }
}
