"""Static data"""

REGIONS = (
    # name, shortname
    ("EMEA", "emea"),
    ("APAC", "apac"),
    ("AMERICAS", "americas"),
)

COUNTRIES = (
    # name, shortname, parent(REGION)
    # Europe
    ("France", "FR", "EMEA"),
    ("Germany", "DE", "EMEA"),
    ("Netherlands", "NL", "EMEA"),
    ("United Kingdom", "UK", "EMEA"),
    ("Poland", "PL", "EMEA"),
    ("Spain", "ES", "EMEA"),
    ("Italy", "IT", "EMEA"),
    ("Switzerland", "CH", "EMEA"),
    # Americas
    ("United States of America", "USA", "AMERICAS"),
    ("Canada", "CA", "AMERICAS"),
    # Asia
    ("China", "CN", "APAC"),
    ("Japan", "JP", "APAC"),
    ("Korea", "KR", "APAC"),
    ("India", "IN", "APAC"),
    # Africa
    ("Egypt", "EG", "EMEA"),
    ("South Africa", "ZA", "EMEA"),
)

CITIES = (
    # name, shortname, parent (COUNTRY)
    ("Paris", "PAR", "France"),
    ("Frankfurt", "FRA", "Germany"),
    ("Munich", "MUC", "Germany"),
    ("London", "LON", "United Kingdom"),
    ("Milan", "MIL", "Italy"),
    ("Amsterdam", "AMS", "Netherlands"),
    ("New York", "NYC", "United States of America"),
    ("Toronto", "TOR", "Canada"),
    ("Beijing", "BJ", "China"),
    ("Tokyo", "TYO", "Japan"),
    ("Seoul", "SEL", "Korea"),
    ("Delhi", "DEL", "India"),
    ("Cairo", "CAI", "Egypt"),
    ("Johannesburg", "JNB", "South Africa"),
    ("Katowice", "KTW", "Poland"),
    ("Madrid", "MAD", "Spain"),
    ("Barcelona", "BCN", "Spain"),
)

SITES = (
    # name, shortname, status, site_type, parent
    ("DC-1", "DC1", "active", "dc", "Frankfurt"),
    ("EQX-1", "EQX1", "active", "pop", "Frankfurt"),
    ("FRA-1", "FRA1", "active", "campus", "Frankfurt"),
    ("FRA-2", "FRA2", "active", "office", "Frankfurt"),
    ("DC-2", "DC2", "active", "dc", "Katowice"),
)

ACCOUNTS = (
    # name, password, type, role
    ("pop-builder", "Script", "Password123", "read-write"),
    ("generator", "Script", "Password123", "read-write"),
    ("CRM Synchronization", "Script", "Password123", "read-write"),
    ("Tomek Zajac", "User", "Password123", "read-write"),
    ("Some User1", "User", "Password123", "read-only"),
    ("Some User2", "User", "Password123", "read-write"),
    ("Some User3", "User", "Password123", "read-write"),
    ("Engineering Team", "User", "Password123", "read-write"),
    ("Architecture Team", "User", "Password123", "read-only"),
    ("Operation Team", "User", "Password123", "read-only"),
)

TAGS = ["blue", "green", "red"]


PROVIDERS = [
    "Arelion",
    "Colt Technology Services",
    "Verizon Business",
    "GTT Communications",
    "Hurricane Electric",
    "Lumen",
    "Zayo",
    "Equinix",
    "Interxion",
    "PCCW Global",
    "Orange S.A",
    "Tata Communications",
    "Sprint",
    "NTT America",
    "Cogent Communications",
    "Comcast Cable Communication",
    "Telecom Italia Sparkle",
    "AT&T Services",
    "Technology Partner",
]

CUSTOMERS = ["OE1", "ABC", "CDE"]

MANUFACTURERS = ["Juniper", "Cisco", "Arista", "Perle", "Citrix", "Sonic", "Linux"]

SUBNETS_1918 = {
    # prefix, state, owner
    ("10.0.0.0/8", "active"),
    ("172.16.0.0/16", "active"),
    ("192.168.0.0/16", "active"),
}

PLATFORMS = (
    # name, nornir_platform, napalm_driver, netmiko_device_type, ansible_network_os, containerlab_os
    ("Cisco IOS-XE", "ios", "ios", "cisco_ios", "ios", "ios"),
    ("Cisco IOS-XR", "iosxr", "iosxr", "cisco_xr", "cisco.iosxr.iosxr", "cisco_xrv"),
    ("Cisco NX-OS", "nxos_ssh", "nxos_ssh", "cisco_nxos", "nxos", "cisco_n9kv"),
    (
        "Juniper JunOS",
        "junos",
        "junos",
        "juniper_junos",
        "junos",
        "juniper_vjunosswitch",
    ),
    ("Arista EOS", "eos", "eos", "arista_eos", "eos", "ceos"),
    ("Sonic OS", "dell_sonic", "dell_sonic", "dell_sonic", "dell_sonic", "dell_sonic"),
    ("Linux", "linux", "linux", "linux", "linux", "linux"),
    ("Perle IOLAN", "linux", "linux", "linux", "linux", "linux"),
)

DEVICE_TYPES = (
    # name, part_number, height (U), full_depth, manufacturer, platform
    ("MX204", "MX204-HWBASE-AC-FS", 1, False, "Juniper", "Juniper JunOS"),
    ("CCS-720DP-48S-2F", None, 1, False, "Arista", "Arista EOS"),
    ("DCS-7280DR3-24-F", None, 1, False, "Arista", "Arista EOS"),
    ("NCS-5501-SE", None, 1, False, "Cisco", "Cisco IOS-XR"),
    ("ASR1002-HX", None, 2, True, "Cisco", "Cisco IOS-XR"),
    ("N9K-C9000V", "N9K-C9000V", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX", "N9K-C93108TC-FX", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX3", "N9K-C93108TC-FX3", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX3P", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93120TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93128TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9316D-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-EX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX3", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX3S", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93216TC-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93240YC-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332C", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332D-GX2B", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332PQ", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9336C-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9336PQ", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348D-GX2A", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FX3", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FX3PH", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FXP", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93600CD-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364C-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364C", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364D-GX2A", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372PX-E", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372PX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372TX-E", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9396PX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("SRX-1500", None, 1, False, "Juniper", "Juniper JunOS"),
    ("C9200L-48P-4G", None, 1, False, "Cisco", "Cisco IOS-XE"),
    ("C9200L-24P-4G", None, 1, False, "Cisco", "Cisco IOS-XE"),
    ("SCG50R", None, 1, False, "Perle", "Perle IOLAN"),
)

GROUPS = (
    # name, description
    ("edge_routers", "Edge Routers"),
    ("core_routers", "Core Routers"),
    ("cisco_dc_spine", "Cisco DC spine devices"),
    ("cisco_dc_leaf", "Cisco DC leaf devices"),
    ("cisco_dc_oob", "Cisco DC OOB devices"),
    ("cisco_pop_router", "Cisco POP Routers"),
    ("arista_dc_leaf", "Arista DC leaf devices"),
    ("arista_dc_spine", "Arista DC spine devices"),
    ("sonic_dc_leaf", "Sonic DC leaf devices"),
    ("sonic_dc_spine", "Sonic DC spine devices"),
    ("linux_devices", "Linux Devices"),
    ("leafs", "All leafs"),
    ("spines", "All spines"),
    ("firewalls", "All firewalls"),
    ("juniper_firewall", "Juniper firewall"),
    ("checkpoint_firewall", "Checkpoint Firewall Devices"),
    ("perle_dc_console", "Perle DC Console"),
    ("provisioning_circuits", "Provisioning Circuits"),
    ("topologies_dc", "Data Center Topologies"),
    ("topologies_pop", "POP Topologies"),
    ("topologies_clab", "Containerlab Topologies"),
)

ASNS = (
    # asn, organization
    (1299, "Arelion"),
    (8220, "Colt Technology Services"),
    (701, "Verizon Business"),
    (3257, "GTT Communications"),
    (6939, "Hurricane Electric"),
    (3356, "Lumen"),
    (6461, "Zayo"),
    (24115, "Equinix"),
    (20710, "Interxion"),
    (3491, "PCCW Global"),
    (5511, "Orange S.A"),
    (6453, "Tata Communications"),
    (1239, "Sprint"),
    (2914, "NTT America"),
    (174, "Cogent Communications"),
    (7922, "Comcast Cable Communication"),
    (6762, "Telecom Italia Sparkle"),
    (7018, "AT&T Services"),
)


DESIGN_ELEMENTS = [
    # name, description, quantity, role, device_type, interface_pattern
    (
        "CISCO S 2 SPINES C9336C-FX2",
        "2 Cisco C9336C-FX2 spines",
        2,
        "spine",
        "N9K-C9336C-FX2",
        [
            {"name": "Ethernet1/1", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/2", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/3", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/4", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/5", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/6", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/7", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/8", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/9", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/10", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/11", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/12", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/13", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/14", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/15", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/16", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/17", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/18", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/19", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/20", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/21", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/22", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/23", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/24", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/25", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/26", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/27", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/28", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/29", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/30", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/31", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/32", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/33", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/34", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/35", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/36", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO S 8 LEAFS N9K-C9336C-FX2",
        "8 Cisco C9336C-FX2 leafs",
        8,
        "leaf",
        "N9K-C9336C-FX2",
        [
            {"name": "Ethernet1/1", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/2", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/3", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/4", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/5", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/6", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/7", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/8", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/9", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/10", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/11", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/12", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/13", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/14", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/15", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/16", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/17", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/18", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/19", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/20", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/21", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/22", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/23", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/24", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/25", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/26", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/27", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/28", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/29", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/30", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/31", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/32", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/33", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/34", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/35", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/36", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO M 4 SPINES N9K-C9316D-GX",
        "4 Cisco N9K-C9316D-GX spines",
        4,
        "spine",
        "N9K-C9316D-GX",
        [
            {"name": "Ethernet1/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/2", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/3", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/4", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/5", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/6", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/7", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/8", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/9", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/10", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/11", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/12", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/13", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/14", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/15", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/16", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO M 16 LEAFS N9K-C93180YC-FX3",
        "16 Cisco N9K-C93180YC-FX3 leafs",
        16,
        "leaf",
        "N9K-C93180YC-FX3",
        [
            {"name": "Ethernet1/1", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/2", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/3", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/4", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/5", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/6", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/7", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/8", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/9", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/10", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/11", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/12", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/13", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/14", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/15", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/16", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/17", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/18", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/19", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/20", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/21", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/22", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/23", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/24", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/25", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/26", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/27", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/28", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/29", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/30", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/31", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/32", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/33", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/34", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/35", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/36", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/37", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/38", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/39", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/40", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/41", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/42", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/43", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/44", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/45", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/46", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/47", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/48", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/49", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/50", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/51", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/52", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/53", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/54", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "ARISTA S 2 SPINES DCS-7280DR3-24-F",
        "2 Arista DCS-7280DR3-24-F spines",
        2,
        "spine",
        "DCS-7280DR3-24-F",
        [
            {"name": "Ethernet1/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet2/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet3/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet4/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet5/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet6/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet7/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet8/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet9/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet10/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet11/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet12/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet13/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet14/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet15/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet16/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet17/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet18/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet19/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet20/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet21/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet22/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet23/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet24/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Management1", "type": "1000base-t", "role": "management"},
            {"name": "Console", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "ARISTA S 6 LEAFS CCS-720DP-48S-2F",
        "6 Arista CCS-720DP-48S-2F leafs",
        6,
        "leaf",
        "CCS-720DP-48S-2F",
        [
            {"name": "Ethernet1", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet2", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet3", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet4", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet5", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet6", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet7", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet8", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet9", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet10", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet11", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet12", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet13", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet14", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet15", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet16", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet17", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet18", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet19", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet20", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet21", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet22", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet23", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet24", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet25", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet26", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet27", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet28", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet29", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet30", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet31", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet32", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet33", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet34", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet35", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet36", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet37", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet38", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet39", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet40", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet41", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet42", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet43", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet44", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet45", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet46", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet47", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet48", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet49", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet50", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet51", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet52", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Management1", "type": "1000base-t", "role": "management"},
            {"name": "Console", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "JUNIPER 2 FIREWALLS SRX-1500",
        "2 Juniper SRX-1500 firewalls",
        2,
        "firewall",
        "SRX-1500",
        [
            {"name": "fxp0", "type": "1000base-t", "role": "management"},
            {"name": "ge-0/0/0", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/1", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/2", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/3", "type": "1000base-t", "role": "leaf"},
        ],
    ),
    (
        "CISCO S 2 OOB SWITCHES C9200L-24P-4G",
        "2 Cisco C9200L-24P-4G OOB switches",
        2,
        "oob",
        "C9200L-24P-4G",
        [
            {
                "name": "GigabitEthernet1/0/1",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/2",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/3",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/4",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/5",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/6",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/7",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/8",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/9",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/10",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/11",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/12",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/13",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/14",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/15",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/16",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/17",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/18",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/19",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/20",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/21",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/22",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/23",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/24",
                "type": "1000base-t",
                "role": "management",
            },
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "PERLE 2 CONSOLE SCG50R",
        "2 Perle SCG50R console servers",
        2,
        "console",
        "SCG50R",
        [
            {"name": "Ethernet0", "type": "1000base-t", "role": "management"},
            {"name": "Ethernet1", "type": "1000base-t", "role": "management"},
            {"name": "con0", "type": "1000base-t", "role": "console"},
            {"name": "con1", "type": "1000base-t", "role": "console"},
            {"name": "con2", "type": "1000base-t", "role": "console"},
            {"name": "con3", "type": "1000base-t", "role": "console"},
            {"name": "con4", "type": "1000base-t", "role": "console"},
            {"name": "con5", "type": "1000base-t", "role": "console"},
            {"name": "con6", "type": "1000base-t", "role": "console"},
            {"name": "con7", "type": "1000base-t", "role": "console"},
            {"name": "con8", "type": "1000base-t", "role": "console"},
            {"name": "con9", "type": "1000base-t", "role": "console"},
            {"name": "con10", "type": "1000base-t", "role": "console"},
            {"name": "con11", "type": "1000base-t", "role": "console"},
            {"name": "con12", "type": "1000base-t", "role": "console"},
            {"name": "con13", "type": "1000base-t", "role": "console"},
            {"name": "con14", "type": "1000base-t", "role": "console"},
            {"name": "con15", "type": "1000base-t", "role": "console"},
            {"name": "con16", "type": "1000base-t", "role": "console"},
            {"name": "con17", "type": "1000base-t", "role": "console"},
            {"name": "con18", "type": "1000base-t", "role": "console"},
            {"name": "con19", "type": "1000base-t", "role": "console"},
            {"name": "con20", "type": "1000base-t", "role": "console"},
            {"name": "con21", "type": "1000base-t", "role": "console"},
            {"name": "con22", "type": "1000base-t", "role": "console"},
            {"name": "con23", "type": "1000base-t", "role": "console"},
            {"name": "con24", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO S 2 EDGE N9K-C9316D-GX",
        "2 Cisco N9K-C9316D-GX edges",
        2,
        "edge",
        "N9K-C9316D-GX",
        [
            {"name": "Ethernet1/1", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/2", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/3", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/4", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/5", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/6", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/7", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/8", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/9", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/10", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/11", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/12", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/13", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/14", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/15", "type": "400gbase-x-qsfpdd", "role": "peering"},
            {"name": "Ethernet1/16", "type": "400gbase-x-qsfpdd", "role": "peering"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
]


DESIGN = [
    # name, description, type, elements
    (
        "CISCO S",
        "Cisco S 2 spines, 8 leafs, 2 firewalls",
        "DC",
        [
            "CISCO S 2 SPINES C9336C-FX2",
            "CISCO S 8 LEAFS N9K-C9336C-FX2",
            "JUNIPER 2 FIREWALLS SRX-1500",
            "CISCO S 2 OOB SWITCHES C9200L-24P-4G",
            "PERLE 2 CONSOLE SCG50R",
        ],
    ),
    (
        "CISCO L",
        "Cisco L 4 spines, 16 leafs, 2 firewalls",
        "DC",
        [
            "CISCO M 4 SPINES N9K-C9316D-GX",
            "CISCO M 16 LEAFS N9K-C93180YC-FX3",
            "JUNIPER 2 FIREWALLS SRX-1500",
        ],
    ),
    (
        "ARISTA S",
        "Arista S 2 spines, 4 leafs, 2 firewalls",
        "DC",
        [
            "ARISTA S 2 SPINES DCS-7280DR3-24-F",
            "ARISTA S 6 LEAFS CCS-720DP-48S-2F",
            "JUNIPER 2 FIREWALLS SRX-1500",
        ],
    ),
    (
        "POP S",
        "POP 2 routers",
        "POP",
        [
            "CISCO S 2 EDGE N9K-C9316D-GX",
        ],
    ),
]
