"""Static data"""

REGIONS = (
    # name, shortname
    ("EMEA", "emea"),
    ("APAC", "apac"),
    ("AMERICAS", "americas"),
)

COUNTRIES = (
    # name, shortname, parent(REGION)
    # Europe
    ("France", "FR", "EMEA"),
    ("Germany", "DE", "EMEA"),
    ("Netherlands", "NL", "EMEA"),
    ("United Kingdom", "UK", "EMEA"),
    ("Poland", "PL", "EMEA"),
    ("Spain", "ES", "EMEA"),
    ("Italy", "IT", "EMEA"),
    ("Switzerland", "CH", "EMEA"),
    # Americas
    ("United States of America", "USA", "AMERICAS"),
    ("Canada", "CA", "AMERICAS"),
    # Asia
    ("China", "CN", "APAC"),
    ("Japan", "JP", "APAC"),
    ("Korea", "KR", "APAC"),
    ("India", "IN", "APAC"),
    # Africa
    ("Egypt", "EG", "EMEA"),
    ("South Africa", "ZA", "EMEA"),
)

CITIES = (
    # name, shortname, parent (COUNTRY)
    ("Paris", "PAR", "France"),
    ("Frankfurt", "FRA", "Germany"),
    ("Munich", "MUC", "Germany"),
    ("London", "LON", "United Kingdom"),
    ("Milan", "MIL", "Italy"),
    ("Amsterdam", "AMS", "Netherlands"),
    ("New York", "NYC", "United States of America"),
    ("Toronto", "TOR", "Canada"),
    ("Beijing", "BJ", "China"),
    ("Tokyo", "TYO", "Japan"),
    ("Seoul", "SEL", "Korea"),
    ("Delhi", "DEL", "India"),
    ("Cairo", "CAI", "Egypt"),
    ("Johannesburg", "JNB", "South Africa"),
    ("Katowice", "KTW", "Poland"),
    ("Madrid", "MAD", "Spain"),
    ("Barcelona", "BCN", "Spain"),
)

SITES = (
    # name, shortname, status, site_type, parent
    ("DC-1", "DC1", "active", "dc", "Frankfurt"),
    ("EQX-1", "EQX1", "active", "pop", "Frankfurt"),
    ("FRA-1", "FRA1", "active", "campus", "Frankfurt"),
    ("FRA-2", "FRA2", "active", "office", "Frankfurt"),
    ("PAR-1", "PAR1", "active", "office", "Paris"),
)

ACCOUNTS = (
    # name, password, type, role
    ("pop-builder", "Script", "Password123", "read-write"),
    ("generator", "Script", "Password123", "read-write"),
    ("CRM Synchronization", "Script", "Password123", "read-write"),
    ("Tomek Zajac", "User", "Password123", "read-write"),
    ("Some User1", "User", "Password123", "read-only"),
    ("Some User2", "User", "Password123", "read-write"),
    ("Some User3", "User", "Password123", "read-write"),
    ("Engineering Team", "User", "Password123", "read-write"),
    ("Architecture Team", "User", "Password123", "read-only"),
    ("Operation Team", "User", "Password123", "read-only"),
)

TAGS = ["blue", "green", "red", "yellow", "white", "black"]

PROVIDERS = [
    "Arelion",
    "Colt Technology Services",
    "Verizon Business",
    "GTT Communications",
    "Hurricane Electric",
    "Lumen",
    "Zayo",
    "Equinix",
    "Interxion",
    "PCCW Global",
    "Orange S.A",
    "Tata Communications",
    "Sprint",
    "NTT America",
    "Cogent Communications",
    "Comcast Cable Communication",
    "Telecom Italia Sparkle",
    "AT&T Services",
    "Technology Partner",
]

CUSTOMERS = ["OE1", "ABC", "CDE"]

MANUFACTURERS = [
    "Juniper",
    "Cisco",
    "Arista",
    "Perle",
    "Citrix",
    "Sonic",
    "Linux",
    "Edgecore",
]

SUBNETS_1918 = {
    # prefix, state, owner
    ("10.0.0.0/8", "active"),
    ("172.16.0.0/16", "active"),
    ("192.168.0.0/16", "active"),
}

PLATFORMS = (
    # name, nornir_platform, napalm_driver, netmiko_device_type, ansible_network_os, containerlab_os
    ("Cisco IOS-XE", "ios", "ios", "cisco_ios", "ios", "ios"),
    ("Cisco IOS-XR", "iosxr", "iosxr", "cisco_xr", "cisco.iosxr.iosxr", "cisco_xrv"),
    ("Cisco NX-OS", "nxos_ssh", "nxos_ssh", "cisco_nxos", "nxos", "cisco_n9kv"),
    (
        "Juniper JunOS",
        "junos",
        "junos",
        "juniper_junos",
        "junos",
        "juniper_vjunosswitch",
    ),
    ("Arista EOS", "eos", "eos", "arista_eos", "eos", "ceos"),
    ("Sonic OS", "sonic", "sonic", "sonic", "sonic", "sonic"),
    ("Linux", "linux", "linux", "linux", "linux", "linux"),
    ("Perle IOLAN", "linux", "linux", "linux", "linux", "linux"),
)

DEVICE_TYPES = (
    # name, part_number, height (U), full_depth, manufacturer, platform
    ("MX204", "MX204-HWBASE-AC-FS", 1, False, "Juniper", "Juniper JunOS"),
    ("CCS-720DP-48S-2F", None, 1, False, "Arista", "Arista EOS"),
    ("DCS-7280DR3-24-F", None, 1, False, "Arista", "Arista EOS"),
    ("NCS-5501-SE", None, 1, False, "Cisco", "Cisco IOS-XR"),
    ("ASR1002-HX", None, 2, True, "Cisco", "Cisco IOS-XR"),
    ("N9K-C9000V", "N9K-C9000V", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX", "N9K-C93108TC-FX", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX3", "N9K-C93108TC-FX3", 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93108TC-FX3P", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93120TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93128TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9316D-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-EX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX3", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93180YC-FX3S", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93216TC-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93240YC-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332C", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332D-GX2B", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9332PQ", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9336C-FX2", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9336PQ", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348D-GX2A", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FX3", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FX3PH", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9348GC-FXP", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C93600CD-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364C-GX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364C", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9364D-GX2A", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372PX-E", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372PX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372TX-E", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9372TX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("N9K-C9396PX", None, 1, False, "Cisco", "Cisco NX-OS"),
    ("SRX-1500", None, 1, False, "Juniper", "Juniper JunOS"),
    ("C9200L-48P-4G", None, 1, False, "Cisco", "Cisco IOS-XE"),
    ("C9200L-24P-4G", None, 1, False, "Cisco", "Cisco IOS-XE"),
    ("SCG50R", None, 1, False, "Perle", "Perle IOLAN"),
    ("5912-54XM-O-AC-F", None, 1, False, "Edgecore", "Sonic OS"),
    ("5912-54X-O-AC-F", None, 1, False, "Edgecore", "Sonic OS"),
    ("5912-54XM-O-AC-F", None, 1, False, "Edgecore", "Sonic OS"),
    ("7726-32X-O", None, 1, False, "Edgecore", "Sonic OS"),
)

GROUPS = (
    # name, description
    ("edge_routers", "Edge Routers"),
    ("core_routers", "Core Routers"),
    ("cisco_spine", "Cisco DC spine devices"),
    ("cisco_leaf", "Cisco DC leaf devices"),
    ("cisco_oob", "Cisco DC OOB devices"),
    ("cisco_edge", "Cisco edge devices"),
    ("cisco_pop_router", "Cisco POP Routers"),
    ("edgecore_leaf", "Cisco DC leaf devices"),
    ("edgecore_spine", "Cisco DC spine devices"),
    ("arista_leaf", "Arista DC leaf devices"),
    ("arista_spine", "Arista DC spine devices"),
    ("arista_pop_router", "Arista POP Routers"),
    ("sonic_leaf", "Sonic DC leaf devices"),
    ("sonic_spine", "Sonic DC spine devices"),
    ("linux_devices", "Linux Devices"),
    ("leafs", "All leafs"),
    ("spines", "All spines"),
    ("firewalls", "All firewalls"),
    ("juniper_firewall", "Juniper DC firewall"),
    ("juniper_edge_firewall", "Juniper POP firewall"),
    ("juniper_dc_firewall", "Juniper DC firewall"),
    ("checkpoint_firewall", "Checkpoint Firewall Devices"),
    ("perle_console", "Perle DC Console"),
    ("perle_pop_console", "Perle POP Console"),
    ("provisioning_circuits", "Provisioning Circuits"),
    ("topologies_dc", "Data Center Topologies"),
    ("topologies_pop", "POP Topologies"),
    ("topologies_clab", "Containerlab Topologies"),
)

ASNS = (
    # asn, organization
    (1299, "Arelion"),
    (8220, "Colt Technology Services"),
    (701, "Verizon Business"),
    (3257, "GTT Communications"),
    (6939, "Hurricane Electric"),
    (3356, "Lumen"),
    (6461, "Zayo"),
    (24115, "Equinix"),
    (20710, "Interxion"),
    (3491, "PCCW Global"),
    (5511, "Orange S.A"),
    (6453, "Tata Communications"),
    (1239, "Sprint"),
    (2914, "NTT America"),
    (174, "Cogent Communications"),
    (7922, "Comcast Cable Communication"),
    (6762, "Telecom Italia Sparkle"),
    (7018, "AT&T Services"),
)

ASN_POOLS = [
    # name, description, node, node_attribute, start, end
    (
        "PRIVATE-ASN32",
        "Private 32 bit ASN Pool",
        "ServiceAutonomousSystem",
        "asn",
        4200000000,
        4294967294,
    ),
    (
        "PRIVATE-ASN4",
        "Private 4 bit ASN Pool",
        "ServiceAutonomousSystem",
        "asn",
        64512,
        65534,
    ),
]

ZONES = ["OUTSIDE", "INSIDE", "DMZ", "EXTRANET"]

IP_PROTOCOLS = [
    # protol, name, description
    (None, "IP", "IP"),
    (1, "ICMP", "ICMP"),
    (6, "TCP", "TCP"),
    (17, "UDP", "UDP"),
    (21, "FTP", "FTP"),
    (22, "SSH", "SSH"),
    (23, "Telnet", "Telnet"),
    (25, "SMTP", "SMTP"),
    (42, "VRRP", "VRRP"),
    (53, "DNS", "DNS"),
    (67, "DHCP", "DHCP"),
    (69, "TFTP", "TFTP"),
    (80, "HTTP", "HTTP"),
    (443, "HTTPS", "HTTPS"),
    (3389, "RDP", "RDP"),
    (5060, "SIP", "SIP"),
    (8080, "HTTP", "HTTP"),
    (8443, "HTTPS", "HTTPS"),
]

SERVICES = [
    # name, ip_protocol, port
    ("DNS_UDP", "UDP", 53),
    ("DNS_TCP", "TCP", 53),
    ("HTTP", "TCP", 80),
    ("HTTPS", "TCP", 443),
    ("SSH", "TCP", 22),
    ("TELNET", "TCP", 23),
    ("RDP", "TCP", 3389),
    ("SIP", "UDP", 5060),
    ("TFTP", "UDP", 69),
    ("VRRP_UDP", "UDP", 42),
    ("VRRP_TCP", "TCP", 42),
    ("DHCP_UDP", "UDP", 67),
    ("FTP", "TCP", 21),
    ("SMTP", "TCP", 25),
    ("SNMP_UDP", "UDP", 161),
    ("NTP_UDP", "UDP", 123),
    ("SNMP_TCP", "TCP", 161),
]


SERVICE_GROUPS = [
    # name, services
    ("HTTP_HTTPS", ["HTTP", "HTTPS"]),
    ("ACCESS", ["SSH", "TELNET"]),
    ("DNS", ["DNS_UDP", "DNS_TCP"]),
]

PREFIXES = [
    # name, prefix
    ("IANA_PRIVATE_PREFIX_1", "10.0.0.0/8"),
    ("IANA_PRIVATE_PREFIX_2", "172.16.0.0/12"),
    ("IANA_PRIVATE_PREFIX_3", "192.168.0.0/16"),
    ("DATACENTER-EU-FR", "89.207.132.0/24"),
    ("DATACENTER-EU-DE", "44.178.0.0/16"),
    ("DATACENTER-US-NY", "244.178.0.0/16"),
]

ADDRESSES = [
    # name, address
    ("ANY", "0.0.0.0/0"),
    ("SMTP_SERVER_1", "192.168.0.10/32"),
    ("SMTP_SERVER_2", "10.0.12.3/32"),
    ("EUR_WEB_PROXY_1", "89.0.142.86/32"),
    ("EUR_WEB_PROXY_2", "10.7.4.3/32"),
]

ADDRESS_GROUPS = [
    # name, addresses
    ("SMTP_SERVERS", ["SMTP_SERVER_1", "SMTP_SERVER_2"]),
    ("EUR_WEB_PROXY", ["EUR_WEB_PROXY_1", "EUR_WEB_PROXY_2"]),
    (
        "IANA_PRIVATE_PREFIXES",
        ["IANA_PRIVATE_PREFIX_1", "IANA_PRIVATE_PREFIX_2", "IANA_PRIVATE_PREFIX_3"],
    ),
    ("DATACENTERS", ["DATACENTER-EU-FR", "DATACENTER-EU-DE", "DATACENTER-US-NY"]),
    (
        "BLOCK_INTERNET",
        [
            "ANY",
            "IANA_PRIVATE_PREFIX_1",
            "IANA_PRIVATE_PREFIX_2",
            "IANA_PRIVATE_PREFIX_3",
            "DATACENTER-US-NY",
        ],
    ),
]

POLICIES = [
    "GLOBAL_POLICY",
    "NORTH_AMERICA_POLICY",
    "EUROPE_POLICY",
    "FRA_POLICY",
    "FRA_FW1_POLICY",
]

RULES: list = [
    # name, policy, index, action,
    # source_zone, destination_zone,
    # source_address, source_groups, source_services,source_service_groups,
    # destination_address, destination_groups, destination_services, destination_service_groups
    (
        "permit-inbound-smtp",
        "GLOBAL_POLICY",
        0,
        "permit",
        "OUTSIDE",
        "DMZ",
        ["ANY"],
        [],
        [],
        [],
        [],
        ["SMTP_SERVERS"],
        ["SMTP"],
        [],
    ),
    (
        "deny-smtp-servers-outbound",
        "GLOBAL_POLICY",
        1,
        "deny",
        "DMZ",
        "OUTSIDE",
        [],
        ["SMTP_SERVERS"],
        [],
        [],
        ["ANY"],
        [],
        ["IP"],
        [],
    ),
    (
        "permit-web-proxies-outbound",
        "EUROPE_POLICY",
        0,
        "permit",
        "DMZ",
        "OUTSIDE",
        [],
        ["EUR_WEB_PROXY"],
        [],
        [],
        ["ANY"],
        [],
        [],
        ["HTTP_HTTPS"],
    ),
    (
        "deny-web-proxies-ip-outbound",
        "EUROPE_POLICY",
        1,
        "deny",
        "DMZ",
        "OUTSIDE",
        [],
        ["EUR_WEB_PROXY"],
        [],
        [],
        ["ANY"],
        [],
        ["IP"],
        [],
    ),
    (
        "permit-internal-to-webproxies",
        "EUROPE_POLICY",
        2,
        "permit",
        "INSIDE",
        "DMZ",
        ["ANY"],
        [],
        [],
        [],
        [],
        ["EUR_WEB_PROXY"],
        ["HTTP"],
        [],
    ),
    (
        "permit-smpt-servers-icmp",
        "EUROPE_POLICY",
        3,
        "permit",
        "DMZ",
        "OUTSIDE",
        [],
        ["SMTP_SERVERS"],
        [],
        [],
        ["ANY"],
        [],
        ["ICMP"],
        [],
    ),
    (
        "permit-inbound-smtp",
        "EUROPE_POLICY",
        4,
        "permit",
        "OUTSIDE",
        "DMZ",
        ["ANY"],
        [],
        [],
        [],
        [],
        ["SMTP_SERVERS"],
        ["SMTP"],
        [],
    ),
    (
        "deny-block-internet-internal",
        "FRA_POLICY",
        0,
        "deny",
        "OUTSIDE",
        "INSIDE",
        [],
        ["BLOCK_INTERNET"],
        [],
        [],
        ["ANY"],
        [],
        ["IP"],
        [],
    ),
    (
        "deny-block-internet-dmz",
        "FRA_POLICY",
        1,
        "deny",
        "OUTSIDE",
        "DMZ",
        [],
        ["BLOCK_INTERNET"],
        [],
        [],
        ["ANY"],
        [],
        ["IP"],
        [],
    ),
    (
        "permit-internal-ssh-smtp-servers",
        "FRA_POLICY",
        2,
        "permit",
        "INSIDE",
        "DMZ",
        ["ANY"],
        [],
        [],
        [],
        [],
        ["SMTP_SERVERS"],
        ["SSH"],
        [],
    ),
    (
        "permit-extranet-ssh-internal",
        "FRA_POLICY",
        999,
        "permit",
        "EXTRANET",
        "INSIDE",
        ["ANY"],
        [],
        [],
        [],
        ["ANY"],
        [],
        ["SSH"],
        [],
    ),
    (
        "deny-internal-block-internet",
        "FRA_FW1_POLICY",
        0,
        "deny",
        "INSIDE",
        "OUTSIDE",
        ["ANY"],
        [],
        [],
        [],
        [],
        ["BLOCK_INTERNET"],
        ["IP"],
        [],
    ),
]

DEVICE_TEMPLATES = (
    # name, role, platfrorm, interfaces
    (
        "N9K-C9336C-FX2",
        "spine",
        "Cisco NX-OS",
        (
            # name, type, role
            ("Ethernet1/1", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/2", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/3", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/4", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/5", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/6", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/7", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/8", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/9", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/10", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/11", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/12", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/13", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/14", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/15", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/16", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/17", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/18", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/19", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/20", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/21", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/22", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/23", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/24", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/25", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/26", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/27", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/28", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/29", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/30", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet1/31", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/32", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/33", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/34", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/35", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/36", "100gbase-x-qsfp28", "uplink"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "N9K-C9336C-FX2",
        "leaf",
        "Cisco NX-OS",
        (
            ("Ethernet1/1", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/2", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/3", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/4", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/5", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/6", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/7", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/8", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/9", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/10", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/11", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/12", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/13", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/14", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/15", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/16", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/17", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/18", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/19", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/20", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/21", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/22", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/23", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/24", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/25", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/26", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/27", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/28", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/29", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/30", "100gbase-x-qsfp28", "customer"),
            ("Ethernet1/31", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/32", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/33", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/34", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/35", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/36", "100gbase-x-qsfp28", "uplink"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "N9K-C9316D-GX",
        "spine",
        "Cisco NX-OS",
        (
            ("Ethernet1/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/2", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/3", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/4", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/5", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/6", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/7", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/8", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/9", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/10", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/11", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/12", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet1/13", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/14", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/15", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/16", "400gbase-x-qsfpdd", "uplink"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "N9K-C9316D-GX",
        "leaf",
        "Cisco NX-OS",
        (
            ("Ethernet1/1", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/2", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/3", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/4", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/5", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/6", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/7", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/8", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/9", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/10", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/11", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/12", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/13", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/14", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/15", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/16", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/17", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/18", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/19", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/20", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/21", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/22", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/23", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/24", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/25", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/26", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/27", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/28", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/29", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/30", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/31", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/32", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/33", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/34", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/35", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/36", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/37", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/38", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/39", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/40", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/41", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/42", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/43", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/44", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/45", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/46", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/47", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/48", "25gbase-x-sfp28", "customer"),
            ("Ethernet1/49", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/50", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/51", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/52", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/53", "100gbase-x-qsfp28", "uplink"),
            ("Ethernet1/54", "100gbase-x-qsfp28", "uplink"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "DCS-7280DR3-24-F",
        "spine",
        "Arista EOS",
        (
            ("Ethernet1/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet2/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet3/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet4/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet5/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet6/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet7/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet8/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet9/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet10/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet11/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet12/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet13/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet14/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet15/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet16/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet17/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet18/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet19/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet20/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet21/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet22/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet23/1", "400gbase-x-qsfpdd", "leaf"),
            ("Ethernet24/1", "400gbase-x-qsfpdd", "leaf"),
            ("Management1", "1000base-t", "management"),
            ("Console", "1000base-t", "console"),
        ),
    ),
    (
        "CCS-720DP-48S-2F",
        "leaf",
        "Arista EOS",
        (
            ("Ethernet1", "1000base-t", "customer"),
            ("Ethernet2", "1000base-t", "customer"),
            ("Ethernet3", "1000base-t", "customer"),
            ("Ethernet4", "1000base-t", "customer"),
            ("Ethernet5", "1000base-t", "customer"),
            ("Ethernet6", "1000base-t", "customer"),
            ("Ethernet7", "1000base-t", "customer"),
            ("Ethernet8", "1000base-t", "customer"),
            ("Ethernet9", "1000base-t", "customer"),
            ("Ethernet10", "1000base-t", "customer"),
            ("Ethernet11", "1000base-t", "customer"),
            ("Ethernet12", "1000base-t", "customer"),
            ("Ethernet13", "1000base-t", "customer"),
            ("Ethernet14", "1000base-t", "customer"),
            ("Ethernet15", "1000base-t", "customer"),
            ("Ethernet16", "1000base-t", "customer"),
            ("Ethernet17", "1000base-t", "customer"),
            ("Ethernet18", "1000base-t", "customer"),
            ("Ethernet19", "1000base-t", "customer"),
            ("Ethernet20", "1000base-t", "customer"),
            ("Ethernet21", "1000base-t", "customer"),
            ("Ethernet22", "1000base-t", "customer"),
            ("Ethernet23", "1000base-t", "customer"),
            ("Ethernet24", "1000base-t", "customer"),
            ("Ethernet25", "1000base-t", "customer"),
            ("Ethernet26", "1000base-t", "customer"),
            ("Ethernet27", "1000base-t", "customer"),
            ("Ethernet28", "1000base-t", "customer"),
            ("Ethernet29", "1000base-t", "customer"),
            ("Ethernet30", "1000base-t", "customer"),
            ("Ethernet31", "1000base-t", "customer"),
            ("Ethernet32", "1000base-t", "customer"),
            ("Ethernet33", "1000base-t", "customer"),
            ("Ethernet34", "1000base-t", "customer"),
            ("Ethernet35", "1000base-t", "customer"),
            ("Ethernet36", "1000base-t", "customer"),
            ("Ethernet37", "1000base-t", "customer"),
            ("Ethernet38", "1000base-t", "customer"),
            ("Ethernet39", "1000base-t", "customer"),
            ("Ethernet40", "1000base-t", "customer"),
            ("Ethernet41", "1000base-t", "customer"),
            ("Ethernet42", "1000base-t", "customer"),
            ("Ethernet43", "1000base-t", "customer"),
            ("Ethernet44", "1000base-t", "customer"),
            ("Ethernet45", "1000base-t", "customer"),
            ("Ethernet46", "1000base-t", "customer"),
            ("Ethernet47", "1000base-t", "customer"),
            ("Ethernet48", "1000base-t", "customer"),
            ("Ethernet49", "10gbase-x-sfpp", "uplink"),
            ("Ethernet50", "10gbase-x-sfpp", "uplink"),
            ("Ethernet51", "10gbase-x-sfpp", "uplink"),
            ("Ethernet52", "10gbase-x-sfpp", "uplink"),
            ("Management1", "1000base-t", "management"),
            ("Console", "1000base-t", "console"),
        ),
    ),
    (
        "SRX-1500",
        "edge_firewall",
        "Juniper JunOS",
        (
            ("con", "1000base-t", "console"),
            ("fxp0", "1000base-t", "management"),
            ("ge-0/0/0", "1000base-t", "leaf"),
            ("ge-0/0/1", "1000base-t", "leaf"),
            ("ge-0/0/2", "1000base-t", "leaf"),
            ("ge-0/0/3", "1000base-t", "leaf"),
        ),
    ),
    (
        "SRX-1500",
        "dc_firewall",
        "Juniper JunOS",
        (
            ("fxp0", "1000base-t", "management"),
            ("ge-0/0/0", "1000base-t", "leaf"),
            ("ge-0/0/1", "1000base-t", "leaf"),
            ("ge-0/0/2", "1000base-t", "leaf"),
            ("ge-0/0/3", "1000base-t", "leaf"),
        ),
    ),
    (
        "C9200L-24P-4G",
        "oob",
        "Cisco IOS-XE",
        (
            ("GigabitEthernet1/0/1", "1000base-t", "management"),
            ("GigabitEthernet1/0/2", "1000base-t", "management"),
            ("GigabitEthernet1/0/3", "1000base-t", "management"),
            ("GigabitEthernet1/0/4", "1000base-t", "management"),
            ("GigabitEthernet1/0/5", "1000base-t", "management"),
            ("GigabitEthernet1/0/6", "1000base-t", "management"),
            ("GigabitEthernet1/0/7", "1000base-t", "management"),
            ("GigabitEthernet1/0/8", "1000base-t", "management"),
            ("GigabitEthernet1/0/9", "1000base-t", "management"),
            ("GigabitEthernet1/0/10", "1000base-t", "management"),
            ("GigabitEthernet1/0/11", "1000base-t", "management"),
            ("GigabitEthernet1/0/12", "1000base-t", "management"),
            ("GigabitEthernet1/0/13", "1000base-t", "management"),
            ("GigabitEthernet1/0/14", "1000base-t", "management"),
            ("GigabitEthernet1/0/15", "1000base-t", "management"),
            ("GigabitEthernet1/0/16", "1000base-t", "management"),
            ("GigabitEthernet1/0/17", "1000base-t", "management"),
            ("GigabitEthernet1/0/18", "1000base-t", "management"),
            ("GigabitEthernet1/0/19", "1000base-t", "management"),
            ("GigabitEthernet1/0/20", "1000base-t", "management"),
            ("GigabitEthernet1/0/21", "1000base-t", "management"),
            ("GigabitEthernet1/0/22", "1000base-t", "management"),
            ("GigabitEthernet1/0/23", "1000base-t", "management"),
            ("GigabitEthernet1/0/24", "1000base-t", "management"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "SCG50R",
        "console",
        "Perle IOLAN",
        (
            ("Ethernet0", "1000base-t", "management"),
            ("Ethernet1", "1000base-t", "management"),
            ("con0", "1000base-t", "console"),
            ("con1", "1000base-t", "console"),
            ("con2", "1000base-t", "console"),
            ("con3", "1000base-t", "console"),
            ("con4", "1000base-t", "console"),
            ("con5", "1000base-t", "console"),
            ("con6", "1000base-t", "console"),
            ("con7", "1000base-t", "console"),
            ("con8", "1000base-t", "console"),
            ("con9", "1000base-t", "console"),
            ("con10", "1000base-t", "console"),
            ("con11", "1000base-t", "console"),
            ("con12", "1000base-t", "console"),
            ("con13", "1000base-t", "console"),
            ("con14", "1000base-t", "console"),
            ("con15", "1000base-t", "console"),
            ("con16", "1000base-t", "console"),
            ("con17", "1000base-t", "console"),
            ("con18", "1000base-t", "console"),
            ("con19", "1000base-t", "console"),
            ("con20", "1000base-t", "console"),
            ("con21", "1000base-t", "console"),
            ("con22", "1000base-t", "console"),
            ("con23", "1000base-t", "console"),
            ("con24", "1000base-t", "console"),
        ),
    ),
    (
        "N9K-C9316D-GX",
        "edge",
        "Cisco NX-OS",
        (
            ("Ethernet1/1", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/2", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/3", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/4", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/5", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/6", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/7", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/8", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/9", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/10", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/11", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/12", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/13", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/14", "400gbase-x-qsfpdd", "uplink"),
            ("Ethernet1/15", "400gbase-x-qsfpdd", "peering"),
            ("Ethernet1/16", "400gbase-x-qsfpdd", "peering"),
            ("mgmt0", "1000base-t", "management"),
            ("con", "1000base-t", "console"),
        ),
    ),
    (
        "5912-54X-O-AC-F",
        "leaf",
        "Sonic OS",
        (
            ("xe1", "10gbase-x-sfpp", "customer"),
            ("xe2", "10gbase-x-sfpp", "customer"),
            ("xe3", "10gbase-x-sfpp", "customer"),
            ("xe4", "10gbase-x-sfpp", "customer"),
            ("xe5", "10gbase-x-sfpp", "customer"),
            ("xe6", "10gbase-x-sfpp", "customer"),
            ("xe7", "10gbase-x-sfpp", "customer"),
            ("xe8", "10gbase-x-sfpp", "customer"),
            ("xe9", "10gbase-x-sfpp", "customer"),
            ("xe10", "10gbase-x-sfpp", "customer"),
            ("xe11", "10gbase-x-sfpp", "customer"),
            ("xe12", "10gbase-x-sfpp", "customer"),
            ("xe13", "10gbase-x-sfpp", "customer"),
            ("xe14", "10gbase-x-sfpp", "customer"),
            ("xe15", "10gbase-x-sfpp", "customer"),
            ("xe16", "10gbase-x-sfpp", "customer"),
            ("xe17", "10gbase-x-sfpp", "customer"),
            ("xe18", "10gbase-x-sfpp", "customer"),
            ("xe19", "10gbase-x-sfpp", "customer"),
            ("xe20", "10gbase-x-sfpp", "customer"),
            ("xe21", "10gbase-x-sfpp", "customer"),
            ("xe22", "10gbase-x-sfpp", "customer"),
            ("xe23", "10gbase-x-sfpp", "customer"),
            ("xe24", "10gbase-x-sfpp", "customer"),
            ("xe25", "10gbase-x-sfpp", "customer"),
            ("xe26", "10gbase-x-sfpp", "customer"),
            ("xe27", "10gbase-x-sfpp", "customer"),
            ("xe28", "10gbase-x-sfpp", "customer"),
            ("xe29", "10gbase-x-sfpp", "customer"),
            ("xe30", "10gbase-x-sfpp", "customer"),
            ("xe31", "10gbase-x-sfpp", "customer"),
            ("xe32", "10gbase-x-sfpp", "customer"),
            ("xe33", "10gbase-x-sfpp", "customer"),
            ("xe34", "10gbase-x-sfpp", "customer"),
            ("xe35", "10gbase-x-sfpp", "customer"),
            ("xe36", "10gbase-x-sfpp", "customer"),
            ("xe37", "10gbase-x-sfpp", "customer"),
            ("xe38", "10gbase-x-sfpp", "customer"),
            ("xe39", "10gbase-x-sfpp", "customer"),
            ("xe40", "10gbase-x-sfpp", "customer"),
            ("xe41", "10gbase-x-sfpp", "customer"),
            ("xe42", "10gbase-x-sfpp", "customer"),
            ("xe43", "10gbase-x-sfpp", "customer"),
            ("xe44", "10gbase-x-sfpp", "customer"),
            ("xe45", "10gbase-x-sfpp", "customer"),
            ("xe46", "10gbase-x-sfpp", "customer"),
            ("xe47", "10gbase-x-sfpp", "customer"),
            ("xe48", "10gbase-x-sfpp", "customer"),
            ("xe49", "100gbase-x-qsfp28", "uplink"),
            ("ce50", "100gbase-x-qsfp28", "uplink"),
            ("ce51", "100gbase-x-qsfp28", "uplink"),
            ("ce52", "100gbase-x-qsfp28", "uplink"),
            ("ce53", "100gbase-x-qsfp28", "uplink"),
            ("ce54", "100gbase-x-qsfp28", "uplink"),
            ("eth0", "1000base-t", "management"),
        ),
    ),
    (
        "7726-32X-O",
        "spine",
        "Sonic OS",
        (
            ("eth0", "1000base-t", "management"),
            # ("eth1", "10gbase-x-sfpp", "mgmt"),
            # ("eth2", "10gbase-x-sfpp", "mgmt"),
            ("Ethernet0", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet4", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet8", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet12", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet16", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet20", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet24", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet28", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet32", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet36", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet40", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet44", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet48", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet52", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet56", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet60", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet64", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet68", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet72", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet76", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet80", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet84", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet88", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet92", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet96", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet100", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet104", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet108", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet112", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet116", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet120", "100gbase-x-qsfp28", "leaf"),
            ("Ethernet124", "100gbase-x-qsfp28", "leaf"),
        ),
    ),
)

DESIGN_ELEMENTS = [
    # name, description, quantity, role, device_type,
    (
        "2 CISCO SPINES C9336C-FX2",
        "2 Cisco C9336C-FX2 spines",
        2,
        "spine",
        "N9K-C9336C-FX2",
    ),
    (
        "8 CISCO LEAFS N9K-C9336C-FX2",
        "8 Cisco C9336C-FX2 leafs",
        8,
        "leaf",
        "N9K-C9336C-FX2",
    ),
    (
        "4 CISCO LEAFS N9K-C9336C-FX2",
        "4 Cisco C9336C-FX2 leafs",
        4,
        "leaf",
        "N9K-C9336C-FX2",
    ),
    (
        "4 CISCO SPINES N9K-C9316D-GX",
        "4 Cisco N9K-C9316D-GX spines",
        4,
        "spine",
        "N9K-C9316D-GX",
    ),
    (
        "16 CISCO LEAFS N9K-C9316D-GX",
        "16 Cisco N9K-C9316D-GX leafs",
        16,
        "leaf",
        "N9K-C9316D-GX",
    ),
    (
        "2 ARISTA SPINES DCS-7280DR3-24-F",
        "2 Arista DCS-7280DR3-24-F spines",
        2,
        "spine",
        "DCS-7280DR3-24-F",
    ),
    (
        "4 ARISTA LEAFS CCS-720DP-48S-2F",
        "4 Arista CCS-720DP-48S-2F leafs",
        4,
        "leaf",
        "CCS-720DP-48S-2F",
    ),
    (
        "2 JUNIPER EDGE FIREWALLS SRX-1500",
        "2 Juniper EDGE SRX-1500 firewalls",
        2,
        "edge_firewall",
        "SRX-1500",
    ),
    (
        "2 JUNIPER DC FIREWALLS SRX-1500",
        "2 Juniper DC SRX-1500 firewalls",
        2,
        "dc_firewall",
        "SRX-1500",
    ),
    (
        "2 CISCO OOB SWITCHES C9200L-24P-4G",
        "2 Cisco C9200L-24P-4G OOB switches",
        2,
        "oob",
        "C9200L-24P-4G",
    ),
    (
        "2 PERLE CONSOLE SCG50R",
        "2 Perle SCG50R console servers",
        2,
        "console",
        "SCG50R",
    ),
    (
        "2 CISCO EDGE N9K-C9316D-GX",
        "2 Cisco N9K-C9316D-GX edges",
        2,
        "edge",
        "N9K-C9316D-GX",
    ),
    (
        "2 EDGECORE SPINES 7726-32X-O",
        "2 EDGECORE 7726-32X-O spines",
        2,
        "spine",
        "7726-32X-O",
    ),
    (
        "4 EDGECORE LEAFS 5912-54X-O-AC-F",
        "4 EDGECORE 5912-54X-O-AC-F leafs",
        4,
        "leaf",
        "5912-54X-O-AC-F",
    ),
    (
        "8 EDGECORE LEAFS 5912-54X-O-AC-F",
        "8 EDGECORE 5912-54X-O-AC-F leafs",
        8,
        "leaf",
        "5912-54X-O-AC-F",
    ),
]

DESIGN = [
    # name, description, type, elements
    (
        "CISCO S",
        "Cisco S 2 spines, 8 leafs, 2 firewalls",
        "DC",
        [
            "2 CISCO SPINES C9336C-FX2",
            "8 CISCO LEAFS N9K-C9336C-FX2",
            "2 JUNIPER DC FIREWALLS SRX-1500",
            "2 CISCO OOB SWITCHES C9200L-24P-4G",
            "2 PERLE CONSOLE SCG50R",
        ],
    ),
    (
        "CISCO L",
        "Cisco L 4 spines, 16 leafs, 2 firewalls",
        "DC",
        [
            "4 CISCO SPINES N9K-C9316D-GX",
            "16 CISCO LEAFS N9K-C9316D-GX",
            "2 JUNIPER DC FIREWALLS SRX-1500",
        ],
    ),
    (
        "ARISTA S",
        "Arista S 2 spines, 4 leafs, 2 firewalls",
        "DC",
        [
            "2 ARISTA SPINES DCS-7280DR3-24-F",
            "4 ARISTA LEAFS CCS-720DP-48S-2F",
            "2 JUNIPER DC FIREWALLS SRX-1500",
        ],
    ),
    (
        "SONIC S",
        "Edgecore S 2 spines, 4 leafs, 2 firewalls",
        "DC",
        [
            "2 EDGECORE SPINES 7726-32X-O",
            "4 EDGECORE LEAFS 5912-54X-O-AC-F",
            "2 JUNIPER DC FIREWALLS SRX-1500",
            "2 CISCO OOB SWITCHES C9200L-24P-4G",
        ],
    ),
    (
        "POP S",
        "POP 2 routers",
        "POP",
        [
            "2 CISCO EDGE N9K-C9316D-GX",
            "2 JUNIPER EDGE FIREWALLS SRX-1500",
        ],
    ),
]
