"""Data for Design demo"""

DESIGN_ELEMENTS = [
    # name, description, quantity, role, device_type, interface_pattern
    (
        "CISCO S 2 SPINES C9336C-FX2",
        "2 Cisco C9336C-FX2 spines",
        2,
        "spine",
        "N9K-C9336C-FX2",
        [
            {"name": "Ethernet1/1", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/2", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/3", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/4", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/5", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/6", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/7", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/8", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/9", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/10", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/11", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/12", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/13", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/14", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/15", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/16", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/17", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/18", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/19", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/20", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/21", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/22", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/23", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/24", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/25", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/26", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/27", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/28", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/29", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/30", "type": "100gbase-x-qsfp28", "role": "leaf"},
            {"name": "Ethernet1/31", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/32", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/33", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/34", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/35", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/36", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO S 8 LEAFS N9K-C9336C-FX2",
        "8 Cisco C9336C-FX2 leafs",
        8,
        "leaf",
        "N9K-C9336C-FX2",
        [
            {"name": "Ethernet1/1", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/2", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/3", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/4", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/5", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/6", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/7", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/8", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/9", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/10", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/11", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/12", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/13", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/14", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/15", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/16", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/17", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/18", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/19", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/20", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/21", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/22", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/23", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/24", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/25", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/26", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/27", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/28", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/29", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/30", "type": "100gbase-x-qsfp28", "role": "server"},
            {"name": "Ethernet1/31", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/32", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/33", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/34", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/35", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/36", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO M 4 SPINES N9K-C9316D-GX",
        "4 Cisco N9K-C9316D-GX spines",
        4,
        "spine",
        "N9K-C9316D-GX",
        [
            {"name": "Ethernet1/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/2", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/3", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/4", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/5", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/6", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/7", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/8", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/9", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/10", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/11", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/12", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet1/13", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/14", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/15", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "Ethernet1/16", "type": "400gbase-x-qsfpdd", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "CISCO M 16 LEAFS N9K-C93180YC-FX3",
        "16 Cisco N9K-C93180YC-FX3 leafs",
        16,
        "leaf",
        "N9K-C93180YC-FX3",
        [
            {"name": "Ethernet1/1", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/2", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/3", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/4", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/5", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/6", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/7", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/8", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/9", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/10", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/11", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/12", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/13", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/14", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/15", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/16", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/17", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/18", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/19", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/20", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/21", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/22", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/23", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/24", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/25", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/26", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/27", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/28", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/29", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/30", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/31", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/32", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/33", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/34", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/35", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/36", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/37", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/38", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/39", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/40", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/41", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/42", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/43", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/44", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/45", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/46", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/47", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/48", "type": "25gbase-x-sfp28", "role": "server"},
            {"name": "Ethernet1/49", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/50", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/51", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/52", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/53", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "Ethernet1/54", "type": "100gbase-x-qsfp28", "role": "uplink"},
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "ARISTA S 2 SPINES DCS-7280DR3-24-F",
        "2 Arista DCS-7280DR3-24-F spimns",
        2,
        "spine",
        "DCS-7280DR3-24-F",
        [
            {"name": "Ethernet1/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet2/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet3/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet4/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet5/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet6/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet7/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet8/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet9/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet10/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet11/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet12/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet13/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet14/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet15/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet16/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet17/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet18/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet19/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet20/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet21/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet22/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet23/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Ethernet24/1", "type": "400gbase-x-qsfpdd", "role": "leaf"},
            {"name": "Management1", "type": "1000base-t", "role": "management"},
            {"name": "Console", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "ARISTA S 6 LEAFS CCS-720DP-48S-2F",
        "6 Arista CCS-720DP-48S-2F leafs",
        6,
        "leaf",
        "CCS-720DP-48S-2F",
        [
            {"name": "Ethernet1", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet2", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet3", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet4", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet5", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet6", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet7", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet8", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet9", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet10", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet11", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet12", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet13", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet14", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet15", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet16", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet17", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet18", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet19", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet20", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet21", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet22", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet23", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet24", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet25", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet26", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet27", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet28", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet29", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet30", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet31", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet32", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet33", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet34", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet35", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet36", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet37", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet38", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet39", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet40", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet41", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet42", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet43", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet44", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet45", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet46", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet47", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet48", "type": "1000base-t", "role": "server"},
            {"name": "Ethernet49", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet50", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet51", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Ethernet52", "type": "10gbase-x-sfpp", "role": "uplink"},
            {"name": "Management1", "type": "1000base-t", "role": "management"},
            {"name": "Console", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "JUNIPER 2 FIREWALLS SRX-1500",
        "2 Juniper SRX-1500 firewalls",
        2,
        "firewall",
        "SRX-1500",
        [
            {"name": "fxp0", "type": "1000base-t", "role": "management"},
            {"name": "ge-0/0/0", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/1", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/2", "type": "1000base-t", "role": "leaf"},
            {"name": "ge-0/0/3", "type": "1000base-t", "role": "leaf"},
        ],
    ),
    (
        "CISCO S 2 OOB SWITCHES C9200L-24P-4G",
        "2 Cisco C9200L-24P-4G OOB switches",
        2,
        "oob",
        "C9200L-24P-4G",
        [
            {
                "name": "GigabitEthernet1/0/1",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/2",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/3",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/4",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/5",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/6",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/7",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/8",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/9",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/10",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/11",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/12",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/13",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/14",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/15",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/16",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/17",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/18",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/19",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/20",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/21",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/22",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/23",
                "type": "1000base-t",
                "role": "management",
            },
            {
                "name": "GigabitEthernet1/0/24",
                "type": "1000base-t",
                "role": "management",
            },
            {"name": "mgmt0", "type": "1000base-t", "role": "management"},
            {"name": "con", "type": "1000base-t", "role": "console"},
        ],
    ),
    (
        "PERLE 2 CONSOLE SCG50R",
        "2 Perle SCG50R console servers",
        2,
        "console",
        "SCG50R",
        [
            {"name": "Ethernet0", "type": "1000base-t", "role": "management"},
            {"name": "Ethernet1", "type": "1000base-t", "role": "management"},
            {"name": "con0", "type": "1000base-t", "role": "console"},
            {"name": "con1", "type": "1000base-t", "role": "console"},
            {"name": "con2", "type": "1000base-t", "role": "console"},
            {"name": "con3", "type": "1000base-t", "role": "console"},
            {"name": "con4", "type": "1000base-t", "role": "console"},
            {"name": "con5", "type": "1000base-t", "role": "console"},
            {"name": "con6", "type": "1000base-t", "role": "console"},
            {"name": "con7", "type": "1000base-t", "role": "console"},
            {"name": "con8", "type": "1000base-t", "role": "console"},
            {"name": "con9", "type": "1000base-t", "role": "console"},
            {"name": "con10", "type": "1000base-t", "role": "console"},
            {"name": "con11", "type": "1000base-t", "role": "console"},
            {"name": "con12", "type": "1000base-t", "role": "console"},
            {"name": "con13", "type": "1000base-t", "role": "console"},
            {"name": "con14", "type": "1000base-t", "role": "console"},
            {"name": "con15", "type": "1000base-t", "role": "console"},
            {"name": "con16", "type": "1000base-t", "role": "console"},
            {"name": "con17", "type": "1000base-t", "role": "console"},
            {"name": "con18", "type": "1000base-t", "role": "console"},
            {"name": "con19", "type": "1000base-t", "role": "console"},
            {"name": "con20", "type": "1000base-t", "role": "console"},
            {"name": "con21", "type": "1000base-t", "role": "console"},
            {"name": "con22", "type": "1000base-t", "role": "console"},
            {"name": "con23", "type": "1000base-t", "role": "console"},
            {"name": "con24", "type": "1000base-t", "role": "console"},
        ],
    ),
]

DESIGN = [
    # name, description, type, elements
    (
        "CISCO S",
        "Cisco S 2 spines, 8 leafs, 2 firewalls",
        "DC",
        [
            "CISCO S 2 SPINES C9336C-FX2",
            "CISCO S 8 LEAFS N9K-C9336C-FX2",
            "JUNIPER 2 FIREWALLS SRX-1500",
            "CISCO S 2 OOB SWITCHES C9200L-24P-4G",
            "PERLE 2 CONSOLE SCG50R",
        ],
    ),
    (
        "CISCO L",
        "Cisco L 4 spines, 16 leafs, 2 firewalls",
        "DC",
        [
            "CISCO M 4 SPINES N9K-C9316D-GX",
            "CISCO M 16 LEAFS N9K-C93180YC-FX3",
            "JUNIPER 2 FIREWALLS SRX-1500",
        ],
    ),
    (
        "ARISTA S",
        "Arista S 2 spines, 4 leafs, 2 firewalls",
        "DC",
        [
            "ARISTA S 2 SPINES DCS-7280DR3-24-F",
            "ARISTA S 6 LEAFS CCS-720DP-48S-2F",
            "JUNIPER 2 FIREWALLS SRX-1500",
        ],
    ),
]

DC_DEPLOYMENT = {
    "name": "DC-2",
    "location": "Katowice",
    "description": "Katowice Data Center",
    "asn": 65005,
    "management": "10.0.0.0/24",
    "strategy": "ebgp-ebgp",
    "customer": "1.1.0.0/24",
    "technical": "1.2.0.0/24",
    "design": "CISCO S",
    "provider": "Technology Partner",
}
