---
jinja2_transforms:
  # Containerlab
  - name: topology_clab
    description: Template to generate a containerlab topology
    query: topology_simulator
    template_path: templates/clab_topology.j2

artifact_definitions:
  # Cisco
  # - name: Cisco edge config
  #   artifact_name: cisco-edge
  #   content_type: text/plain
  #   targets: cisco_edge
  #   transformation: cisco_edge
  #   parameters:
  #     device: name__value
  - name: Cisco leaf config
    artifact_name: cisco-leaf
    content_type: text/plain
    targets: cisco_leaf
    transformation: cisco_leaf
    parameters:
      device: name__value
  - name: Cisco spine config
    artifact_name: cisco-spine
    content_type: text/plain
    targets: cisco_spine
    transformation: cisco_spine
    parameters:
      device: name__value
  - name: Arista leaf config
    artifact_name: arista-leaf
    content_type: text/plain
    targets: arista_leaf
    transformation: arista_leaf
    parameters:
      device: name__value
  - name: Arista spine config
    artifact_name: arista-spine
    content_type: text/plain
    targets: arista_spine
    transformation: arista_spine
    parameters:
      device: name__value
  # Juniper
  # - name: Juniper DC firewall config
  #   artifact_name: juniper-dc-firewall
  #   content_type: text/plain
  #   targets: juniper_dc_firewall
  #   transformation: juniper_firewall
  #   parameters:
  #     device: name__value
  # - name: Juniper POP firewall config
  #   artifact_name: juniper-pop-firewall
  #   content_type: text/plain
  #   targets: juniper_pop_firewall
  #   transformation: juniper_firewall
  #   parameters:
  #     device: name__value
  # Perle
  # - name: Perle DC console config
  #   artifact_name: perle-dc-console
  #   content_type: text/plain
  #   targets: perle_dc_console
  #   transformation: perle_console
  #   parameters:
  #     device: name__value
  # - name: Perle POP console config
  #   artifact_name: perle-pop-console
  #   content_type: text/plain
  #   targets: perle_pop_console
  #   transformation: perle_console
  #   parameters:
  #     device: name__value
  # Sonic
  - name: Edgecore leaf config
    artifact_name: edgecore-leaf
    content_type: application/json
    targets: edgecore_leaf
    transformation: edgecore_leaf
    parameters:
      device: name__value
  - name: Edgecore spine config
    artifact_name: edgecore-spine
    content_type: application/json
    targets: edgecore_spine
    transformation: edgecore_spine
    parameters:
      device: name__value
  # Containerlab
  - name: Containerlab Topology
    artifact_name: containerlab-topology
    content_type: text/plain
    targets: topologies_clab
    transformation: topology_clab
    parameters:
      name: name__value

  - name: Cable marix for Topology
    artifact_name: topology-cabling
    content_type: text/plain
    targets: topologies_dc
    transformation: topology_cabling
    parameters:
      name: name__value

check_definitions:
  - name: validate_spine
    class_name: CheckSpine
    file_path: checks/spine.py
    targets: spines
    parameters:
      device: name__value
  - name: validate_leaf
    class_name: CheckLeaf
    file_path: checks/leaf.py
    targets: leafs
    parameters:
      device: name__value
  - name: validate_edge
    class_name: CheckEdge
    file_path: checks/edge.py
    targets: edges
    parameters:
      device: name__value

python_transforms:
  - name: topology_cabling
    class_name: TopologyCabling
    file_path: transforms/topology_cabling.py
  - name: edgecore_leaf
    class_name: SonicLeaf
    file_path: transforms/sonic_leaf.py
  - name: edgecore_spine
    class_name: SonicSpine
    file_path: transforms/sonic_spine.py
  - name: cisco_leaf
    class_name: CiscoLeaf
    file_path: transforms/cisco_leaf.py
  - name: cisco_spine
    class_name: CiscoSpine
    file_path: transforms/cisco_spine.py
  - name: arista_leaf
    class_name: AristaLeaf
    file_path: transforms/arista_leaf.py
  - name: arista_spine
    class_name: AristaSpine
    file_path: transforms/arista_spine.py

generator_definitions:
  - name: create_dc
    file_path: generators/generate_dc.py
    targets: topologies_dc
    query: topology_dc
    class_name: DCTopologyGenerator
    parameters:
      name: name__value
  - name: create_pop
    file_path: generators/generate_pop.py
    targets: topologies_pop
    query: topology_pop
    class_name: PopTopologyGenerator
    parameters:
      name: name__value


queries:
  - name: topology_dc
    file_path: queries/topology_dc.gql
  - name: topology_pop
    file_path: queries/topology_pop.gql
  - name: topology_simulator
    file_path: queries/topology_clab.gql
  - name: topology_cabling
    file_path: queries/topology_cabling.gql
  - name: leaf_config
    file_path: queries/leaf_config.gql
  - name: spine_config
    file_path: queries/spine_config.gql
  - name: edge_config
    file_path: queries/edge_config.gql
  # - name: dc_oob_config
  #   file_path: queries/dc_oob_config.gql
  # - name: console_config
  #   file_path: queries/console_config.gql
# schemas:
#   - schemas/
# menus:
#   - menus/menu.yml
