---
jinja2_transforms:
  # Containerlab
  - name: topology_clab
    description: Template to generate a containerlab topology
    query: topology_simulator
    template_path: templates/clab_topology.j2

artifact_definitions:
  - name: edge_config
    artifact_name: edge
    content_type: text/plain
    targets: edges
    transformation: edge
    parameters:
      device: name__value
  - name: leaf_config
    artifact_name: leaf
    content_type: text/plain
    targets: leafs
    transformation: leaf
    parameters:
      device: name__value
  - name: borderleaf_config
    artifact_name: border-leaf
    content_type: text/plain
    targets: border-leafs
    transformation: border_leaf
    parameters:
      device: name__value
  - name: tor_config
    artifact_name: tor
    content_type: text/plain
    targets: tors
    transformation: tor
    parameters:
      device: name__value
  - name: spine_config
    artifact_name: spine
    content_type: text/plain
    targets: spines
    transformation: spine
    parameters:
      device: name__value
  - name: super_spine_config
    artifact_name: super-spine
    content_type: text/plain
    targets: super-spines
    transformation: super_spine
    parameters:
      device: name__value
  - name: loadbalancer_config
    artifact_name: loadbalancer
    content_type: text/plain
    targets: loadbalancers
    transformation: loadbalancer
    parameters:
      instance: name__value
  # Cloud Load Balancer Terraform vars
  - name: cloud_lb_terraform
    artifact_name: terraform-vars
    content_type: application/json
    targets: cloud_loadbalancers
    transformation: loadbalancer-cloud
    parameters:
      instance: name__value
  # Containerlab
  - name: Containerlab Topology
    artifact_name: containerlab-topology
    content_type: text/plain
    targets: topologies_clab
    transformation: topology_clab
    parameters:
      name: name__value

  - name: Cable matrix for DC
    artifact_name: topology-cabling
    content_type: text/csv
    targets: topologies_dc
    transformation: topology_cabling
    parameters:
      id: id

  # Equinix POP
  - name: equinix_pop_config
    artifact_name: equinix_pop
    content_type: text/plain
    targets: equinix_pop
    transformation: equinix_pop
    parameters:
      name: name__value
  - name: firewall_config
    artifact_name: firewall
    content_type: text/plain
    targets: firewalls
    transformation: firewall
    parameters:
      device: name__value

check_definitions:
  # - name: validate_dc_capacity
  #   class_name: CheckDataCenterCapacity
  #   file_path: checks/dc.py
  #   targets: topologies_dc
  #   parameters:
  #     name: name__value
  - name: validate_spine
    class_name: CheckSpine
    file_path: checks/spine.py
    targets: spines
    parameters:
      device: name__value
  - name: validate_leaf
    class_name: CheckLeaf
    file_path: checks/leaf.py
    targets: leafs
    parameters:
      device: name__value
  - name: validate_edge
    class_name: CheckEdge
    file_path: checks/edge.py
    targets: edges
    parameters:
      device: name__value
  - name: validate_loadbalancer
    class_name: CheckLoadBalancer
    file_path: checks/loadbalancer.py
    targets: loadbalancers
    parameters:
      instance: name__value
  - name: validate_tor
    class_name: CheckToR
    file_path: checks/tor.py
    targets: tors
    parameters:
      device: name__value
  - name: validate_border_leaf
    class_name: CheckBorderLeaf
    file_path: checks/border_leaf.py
    targets: border-leafs
    parameters:
      device: name__value
  - name: validate_super_spine
    class_name: CheckSuperSpine
    file_path: checks/super_spine.py
    targets: super-spines
    parameters:
      device: name__value
  - name: validate_firewall
    class_name: CheckFirewall
    file_path: checks/firewall.py
    targets: firewalls
    parameters:
      device: name__value

python_transforms:
  - name: topology_cabling
    class_name: TopologyCabling
    file_path: transforms/topology_cabling.py
  - name: leaf
    class_name: Leaf
    file_path: transforms/leaf.py
  - name: border_leaf
    class_name: BorderLeaf
    file_path: transforms/border_leaf.py
  - name: tor
    class_name: ToR
    file_path: transforms/tor.py
  - name: spine
    class_name: Spine
    file_path: transforms/spine.py
  - name: super_spine
    class_name: SuperSpine
    file_path: transforms/super_spine.py
  - name: loadbalancer
    class_name: LoadBalancer
    file_path: transforms/loadbalancer.py
  - name: edge
    class_name: Edge
    file_path: transforms/edge.py
  - name: equinix_pop
    class_name: EquinixPOP
    file_path: transforms/equinix_pop.py
  - name: loadbalancer-cloud
    class_name: LoadBalancerCloud
    file_path: transforms/loadbalancer_cloud.py
  - name: firewall
    class_name: Firewall
    file_path: transforms/firewall.py

queries:
  - name: dc_validation
    file_path: queries/validation/dc_capacity.gql
  - name: endpoint_connectivity
    file_path: queries/topology/add/endpoint.gql
  - name: topology_dc
    file_path: queries/topology/add/dc.gql
  - name: topology_pod
    file_path: queries/topology/add/pod.gql
  - name: rack
    file_path: queries/topology/add/rack.gql
  - name: topology_pop
    file_path: queries/topology/add/pop.gql
  - name: topology_simulator
    file_path: queries/topology/clab.gql
  - name: topology_cabling
    file_path: queries/topology/cabling.gql
  - name: leaf_config
    file_path: queries/config/leaf.gql
  - name: border_leaf_config
    file_path: queries/config/border_leaf.gql
  - name: spine_config
    file_path: queries/config/spine.gql
  - name: super_spine_config
    file_path: queries/config/super_spine.gql
  - name: edge_config
    file_path: queries/config/edge.gql
  - name: loadbalancer_config
    file_path: queries/config/loadbalancer.gql
  - name: loadbalancer_cloud
    file_path: queries/config/loadbalancer_cloud.gql
  - name: firewall_config
    file_path: queries/config/firewall.gql
  - name: oob_config
    file_path: queries/config/oob.gql
  - name: pod_decommission
    file_path: queries/topology/decomission/pod.gql


generator_definitions:
  - name: add_dc
    file_path: generators/add/dc.py
    targets: topologies_dc
    query: topology_dc
    class_name: DCTopologyGenerator
    execute_in_proposed_change: false
    execute_after_merge: false
    parameters:
      name: name__value
  - name: add_pod
    file_path: generators/add/pod.py
    targets: topologies_pod
    query: topology_pod
    class_name: PodTopologyGenerator
    execute_in_proposed_change: false
    execute_after_merge: true
    parameters:
      name: name__value
  - name: decommission_pod
    file_path: generators/decommission/pod.py
    targets: topologies_pod
    query: pod_decommission
    class_name: PodDecommissionGenerator
    execute_in_proposed_change: false
    execute_after_merge: false
    parameters:
      name: name__value
  # - name: decommission_device
  #   file_path: generators/decommission_device.py
  #   targets: devices
  #   query: device_decommission
  #   class_name: DeviceDecommissionGenerator
  #   execute_in_proposed_change: false
  #   execute_after_merge: false
  #   parameters:
  #     name: name__value
  - name: add_rack
    file_path: generators/add/rack.py
    targets: topologies_rack
    query: rack
    class_name: RackGenerator
    execute_in_proposed_change: false
    execute_after_merge: false
    parameters:
      name: name__value
  - name: add_endpoint
    file_path: generators/add/endpoint.py
    targets: endpoints
    query: endpoint_connectivity
    class_name: EndpointConnectivityGenerator
    execute_in_proposed_change: false
    execute_after_merge: false
    parameters:
      device_name: name__value
# - name: create_pop
#   file_path: generators/generate_pop.py
#   targets: topologies_pop
#   query: topology_pop
#   class_name: PopTopologyGenerator
#   parameters:
#     name: name__value

# schemas:
#   - schemas/
# menus:
#   - menus/menu.yml
