#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from infrahub_sdk.protocols import (
    CoreNode,
    BuiltinIPAddress,
    BuiltinIPAddressSync,
    BuiltinIPNamespace,
    BuiltinIPNamespaceSync,
    BuiltinIPPrefix,
    BuiltinIPPrefixSync,
    BuiltinTag,
    BuiltinTagSync,
    CoreAccount,
    CoreAccountGroup,
    CoreAccountGroupSync,
    CoreAccountRole,
    CoreAccountRoleSync,
    CoreAccountSync,
    CoreAction,
    CoreActionSync,
    CoreArtifact,
    CoreArtifactCheck,
    CoreArtifactCheckSync,
    CoreArtifactDefinition,
    CoreArtifactDefinitionSync,
    CoreArtifactSync,
    CoreArtifactTarget,
    CoreArtifactTargetSync,
    CoreArtifactThread,
    CoreArtifactThreadSync,
    CoreArtifactValidator,
    CoreArtifactValidatorSync,
    CoreBasePermission,
    CoreBasePermissionSync,
    CoreChangeComment,
    CoreChangeCommentSync,
    CoreChangeThread,
    CoreChangeThreadSync,
    CoreCheck,
    CoreCheckDefinition,
    CoreCheckDefinitionSync,
    CoreCheckSync,
    CoreComment,
    CoreCommentSync,
    CoreCredential,
    CoreCredentialSync,
    CoreCustomWebhook,
    CoreCustomWebhookSync,
    CoreDataCheck,
    CoreDataCheckSync,
    CoreDataValidator,
    CoreDataValidatorSync,
    CoreFileCheck,
    CoreFileCheckSync,
    CoreFileThread,
    CoreFileThreadSync,
    CoreGeneratorAction,
    CoreGeneratorActionSync,
    CoreGeneratorCheck,
    CoreGeneratorCheckSync,
    CoreGeneratorDefinition,
    CoreGeneratorDefinitionSync,
    CoreGeneratorGroup,
    CoreGeneratorGroupSync,
    CoreGeneratorInstance,
    CoreGeneratorInstanceSync,
    CoreGeneratorValidator,
    CoreGeneratorValidatorSync,
    CoreGenericAccount,
    CoreGenericAccountSync,
    CoreGenericRepository,
    CoreGenericRepositorySync,
    CoreGlobalPermission,
    CoreGlobalPermissionSync,
    CoreGraphQLQuery,
    CoreGraphQLQueryGroup,
    CoreGraphQLQueryGroupSync,
    CoreGraphQLQuerySync,
    CoreGroup,
    CoreGroupAction,
    CoreGroupActionSync,
    CoreGroupSync,
    CoreGroupTriggerRule,
    CoreGroupTriggerRuleSync,
    CoreIPAddressPool,
    CoreIPAddressPoolSync,
    CoreIPPrefixPool,
    CoreIPPrefixPoolSync,
    CoreMenu,
    CoreMenuItem,
    CoreMenuItemSync,
    CoreMenuSync,
    CoreNodeSync,
    CoreNodeTriggerAttributeMatch,
    CoreNodeTriggerAttributeMatchSync,
    CoreNodeTriggerMatch,
    CoreNodeTriggerMatchSync,
    CoreNodeTriggerRelationshipMatch,
    CoreNodeTriggerRelationshipMatchSync,
    CoreNodeTriggerRule,
    CoreNodeTriggerRuleSync,
    CoreNumberPool,
    CoreNumberPoolSync,
    CoreObjectComponentTemplate,
    CoreObjectComponentTemplateSync,
    CoreObjectPermission,
    CoreObjectPermissionSync,
    CoreObjectTemplate,
    CoreObjectTemplateSync,
    CoreObjectThread,
    CoreObjectThreadSync,
    CorePasswordCredential,
    CorePasswordCredentialSync,
    CoreProfile,
    CoreProfileSync,
    CoreProposedChange,
    CoreProposedChangeSync,
    CoreReadOnlyRepository,
    CoreReadOnlyRepositorySync,
    CoreRepository,
    CoreRepositoryGroup,
    CoreRepositoryGroupSync,
    CoreRepositorySync,
    CoreRepositoryValidator,
    CoreRepositoryValidatorSync,
    CoreResourcePool,
    CoreResourcePoolSync,
    CoreSchemaCheck,
    CoreSchemaCheckSync,
    CoreSchemaValidator,
    CoreSchemaValidatorSync,
    CoreStandardCheck,
    CoreStandardCheckSync,
    CoreStandardGroup,
    CoreStandardGroupSync,
    CoreStandardWebhook,
    CoreStandardWebhookSync,
    CoreTaskTarget,
    CoreTaskTargetSync,
    CoreThread,
    CoreThreadComment,
    CoreThreadCommentSync,
    CoreThreadSync,
    CoreTransformJinja2,
    CoreTransformJinja2Sync,
    CoreTransformPython,
    CoreTransformPythonSync,
    CoreTransformation,
    CoreTransformationSync,
    CoreTriggerRule,
    CoreTriggerRuleSync,
    CoreUserValidator,
    CoreUserValidatorSync,
    CoreValidator,
    CoreValidatorSync,
    CoreWebhook,
    CoreWebhookSync,
    CoreWeightedPoolResource,
    CoreWeightedPoolResourceSync,
    InternalAccountToken,
    InternalAccountTokenSync,
    InternalIPPrefixAvailable,
    InternalIPPrefixAvailableSync,
    InternalIPRangeAvailable,
    InternalIPRangeAvailableSync,
    InternalRefreshToken,
    InternalRefreshTokenSync,
    IpamNamespace,
    IpamNamespaceSync,
    LineageOwner,
    LineageOwnerSync,
    LineageSource,
    LineageSourceSync,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        AnyAttribute,
        AnyAttributeOptional,
        String,
        StringOptional,
        Integer,
        IntegerOptional,
        Boolean,
        BooleanOptional,
        DateTime,
        DateTimeOptional,
        Dropdown,
        DropdownOptional,
        HashedPassword,
        HashedPasswordOptional,
        MacAddress,
        MacAddressOptional,
        IPHost,
        IPHostOptional,
        IPNetwork,
        IPNetworkOptional,
        JSONAttribute,
        JSONAttributeOptional,
        ListAttribute,
        ListAttributeOptional,
        URL,
        URLOptional,
    )


class TemplateCoreArtifactTarget(CoreNode):
    template_name: String
    artifacts: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimEndpoint(CoreNode):
    template_name: String
    cable: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimGenericDevice(CoreNode):
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    template_name: String
    device_services: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimInterface(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    device: RelatedNode
    interface_services: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimSubInterface(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TopologyDeployment(CoreNode):
    index: Integer
    name: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    racks: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimEndpoint(CoreNode):
    cable: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationGeneric(CoreNode):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    asn: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceGeneric(CoreNode):
    name: String
    status: DropdownOptional
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimGenericDevice(CoreNode):
    name: String
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    device_services: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceGenericDevice(CoreNode):
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceGenericInterfaces(CoreNode):
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimGenericSFP(CoreNode):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class LocationHosting(CoreNode):
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    device: RelatedNode
    interface_services: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class NetworkManagementServer(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServicePeering(CoreNode):
    peering_type: DropdownOptional
    session_scope: DropdownOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingPolicy(CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingProtocol(CoreNode):
    description: String
    status: Dropdown
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceRouting(CoreNode):
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimSubInterface(CoreNode):
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager


class GeneratorTarget(CoreNode):
    checksum: StringOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingAggregateRoute(RoutingProtocol):
    description: String
    discard: BooleanOptional
    export_policies: StringOptional
    import_policies: StringOptional
    status: Dropdown
    destination: RelationshipManager
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingAutonomousSystem(CoreNode):
    asn: Integer
    description: StringOptional
    name: String
    location: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceBGP(
    ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting
):
    graceful_restart: BooleanOptional
    multipath: BooleanOptional
    name: String
    session_type: Dropdown
    status: DropdownOptional
    device: RelatedNode
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    interfaces: RelationshipManager
    local_as: RelatedNode
    local_ip: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    peer_group: RelatedNode
    profiles: RelationshipManager
    remote_as: RelatedNode
    remote_ip: RelatedNode
    router_id: RelatedNode
    subscriber_of_groups: RelationshipManager


class RoutingBGPCommunity(CoreNode):
    community: String
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    routing_policy: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class RoutingBGPPeerGroup(CoreNode):
    bfd_enabled: BooleanOptional
    description: String
    ebgp_multihop: IntegerOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    name: String
    password: StringOptional
    peer_group_type: DropdownOptional
    route_reflector_client: BooleanOptional
    send_community: BooleanOptional
    send_community_extended: BooleanOptional
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    rr_cluster: RelatedNode
    subscriber_of_groups: RelationshipManager


class ServiceBGPPeering(ServiceGeneric, ServicePeering):
    bfd_enabled: BooleanOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    med: IntegerOptional
    name: String
    password: StringOptional
    peering_type: DropdownOptional
    remove_private_as: BooleanOptional
    send_community: BooleanOptional
    send_extended_community: BooleanOptional
    session_scope: DropdownOptional
    session_type: DropdownOptional
    status: DropdownOptional
    ttl_security: IntegerOptional
    deployment: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingBGPRRCluster(CoreNode):
    description: StringOptional
    name: String
    cluster_id: RelatedNode
    member_of_groups: RelationshipManager
    peer_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimBidiSFP(DcimGenericSFP):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    wavelength_rx: Integer
    wavelength_tx: Integer
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class LocationBuilding(LocationGeneric, LocationHosting):
    description: StringOptional
    facility_id: StringOptional
    is_cloud: BooleanOptional
    name: String
    physical_address: StringOptional
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimCable(CoreNode):
    name: String
    type: Dropdown
    endpoints: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimConsoleInterface(DcimInterface, DcimEndpoint, CoreArtifactTarget):
    description: StringOptional
    name: String
    port: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    artifacts: RelationshipManager
    cable: RelatedNode
    device: RelatedNode
    interface_services: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationCountry(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    timezone: StringOptional
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class OrganizationCustomer(OrganizationGeneric):
    customer_id: StringOptional
    description: StringOptional
    name: String
    asn: RelationshipManager
    customer_deployments: RelationshipManager
    ip_prefixes: RelationshipManager
    member_of_groups: RelationshipManager
    namespaces: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TopologyDataCenter(CoreArtifactTarget, TopologyDeployment):
    amount_of_super_spines: IntegerOptional
    fabric_interface_sorting_method: DropdownOptional
    index: Integer
    name: String
    spine_interface_sorting_method: DropdownOptional
    artifacts: RelationshipManager
    children: RelationshipManager
    customer_deployments: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    racks: RelationshipManager
    subscriber_of_groups: RelationshipManager
    super_spine_switch_template: RelatedNode


class DcimDeviceType(CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    name: String
    part_number: StringOptional
    weight: IntegerOptional
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TopologyElement(CoreNode):
    description: StringOptional
    name: String
    quantity: Integer
    role: DropdownOptional
    device_type: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    template: RelatedNode


class CoreGeneratorAwareGroup(CoreGroup):
    description: StringOptional
    group_type: StringOptional
    label: StringOptional
    name: String
    children: RelationshipManager
    members: RelationshipManager
    parent: RelatedNode
    subscribers: RelationshipManager


class LoadbalancerHealthCheck(CoreNode):
    check: Dropdown
    description: String
    fall: IntegerOptional
    rise: IntegerOptional
    timeout: IntegerOptional
    health_checks: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class OrganizationManufacturer(CoreNode):
    description: StringOptional
    name: String
    device_type: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelationshipManager
    profiles: RelationshipManager
    sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationMetro(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceNetworkSegment(ServiceGeneric, ServiceGenericInterfaces):
    customer_name: String
    environment: DropdownOptional
    external_routing: BooleanOptional
    name: String
    segment_type: DropdownOptional
    status: DropdownOptional
    tenant_isolation: DropdownOptional
    vlan_id: Integer
    deployment: RelatedNode
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    prefix: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceOSPF(
    ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting
):
    name: String
    process_id: StringOptional
    reference_bandwidth: IntegerOptional
    router_type: DropdownOptional
    status: DropdownOptional
    version: Dropdown
    area: RelatedNode
    device: RelatedNode
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    ospf_interface_profile: RelatedNode
    owner: RelatedNode
    profiles: RelationshipManager
    router_id: RelatedNode
    subscriber_of_groups: RelationshipManager


class RoutingOSPFArea(CoreNode):
    area: Integer
    area_type: DropdownOptional
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingOSPFInterface(CoreNode):
    authentication_key: StringOptional
    authentication_mode: DropdownOptional
    metric: IntegerOptional
    mode: DropdownOptional
    name: String
    member_of_groups: RelationshipManager
    ospf_services: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServiceOSPFPeering(ServiceGeneric, ServicePeering):
    area_type: DropdownOptional
    authentication_key: StringOptional
    authentication_type: DropdownOptional
    cost: IntegerOptional
    dead_interval: IntegerOptional
    hello_interval: IntegerOptional
    name: String
    network_type: DropdownOptional
    peering_type: DropdownOptional
    priority: IntegerOptional
    retransmit_interval: IntegerOptional
    session_scope: DropdownOptional
    status: DropdownOptional
    deployment: RelatedNode
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ServicePIM(
    ServiceGeneric, ServiceGenericDevice, ServiceGenericInterfaces, ServiceRouting
):
    dr_priority: IntegerOptional
    name: String
    rp_mode: DropdownOptional
    status: DropdownOptional
    device: RelatedNode
    export_routing_policies: RelationshipManager
    import_routing_policies: RelationshipManager
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    pim_interface_profile: RelationshipManager
    profiles: RelationshipManager
    rp_address: RelatedNode
    subscriber_of_groups: RelationshipManager


class RoutingPIMInterface(CoreNode):
    dr_priority: IntegerOptional
    hello_interval: IntegerOptional
    name: String
    pim_mode: Dropdown
    member_of_groups: RelationshipManager
    pim_services: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimPhysicalDevice(CoreArtifactTarget, DcimGenericDevice):
    name: String
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: Dropdown
    artifacts: RelationshipManager
    device_services: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPhysicalInterface(DcimInterface, DcimEndpoint, DcimSubInterface):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    cable: RelatedNode
    device: RelatedNode
    interface_services: RelationshipManager
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    plugged_sfp: RelatedNode
    profiles: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPlatform(CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    name: String
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    devices: RelationshipManager
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TopologyPod(TopologyDeployment, GeneratorTarget):
    amount_of_spines: IntegerOptional
    checksum: StringOptional
    index: Integer
    leaf_interface_sorting_method: DropdownOptional
    name: String
    role: DropdownOptional
    spine_interface_sorting_method: DropdownOptional
    children: RelationshipManager
    devices: RelationshipManager
    loopback_pool: RelatedNode
    member_of_groups: RelationshipManager
    parent: RelatedNode
    prefix_pool: RelatedNode
    profiles: RelationshipManager
    racks: RelationshipManager
    spine_switch_template: RelatedNode
    subscriber_of_groups: RelationshipManager


class RoutingPolicyAggregate(RoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingPolicyBGP(RoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingPolicyOSPF(RoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class RoutingPolicyPIM(RoutingPolicy):
    address_family: DropdownOptional
    description: StringOptional
    name: String
    policy_type: Dropdown
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    is_top_level: BooleanOptional
    member_type: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: DropdownOptional
    status: DropdownOptional
    utilization: IntegerOptional
    children: RelationshipManager
    gateway: RelatedNode
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    resource_pool: RelationshipManager
    subscriber_of_groups: RelationshipManager


class OrganizationProvider(OrganizationGeneric):
    description: StringOptional
    name: String
    asn: RelationshipManager
    asns: RelationshipManager
    location: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRack(LocationGeneric, LocationHosting, GeneratorTarget):
    checksum: StringOptional
    description: StringOptional
    facility_id: StringOptional
    index: Integer
    name: String
    rack_type: DropdownOptional
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    fabric_devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    pod: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    spare_sfps: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRegion(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LoadbalancerServer(CoreNode):
    description: StringOptional
    hostname: String
    status: DropdownOptional
    ip_address: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    virtual_ips: RelationshipManager


class DcimStandardSFP(DcimGenericSFP):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: DropdownOptional
    interface: RelatedNode
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    spare_location: RelatedNode
    subscriber_of_groups: RelationshipManager


class LocationSuite(LocationGeneric):
    description: StringOptional
    facility_id: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceVIP(ServiceGeneric):
    balance: DropdownOptional
    description: String
    hostname: String
    mode: Dropdown
    name: String
    ssl_certificate: StringOptional
    status: DropdownOptional
    backend_servers: RelationshipManager
    frontend_servers: RelationshipManager
    health_checks: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vip_ip: RelatedNode


class DcimVirtualDevice(CoreArtifactTarget, DcimGenericDevice):
    cpu: IntegerOptional
    memory: IntegerOptional
    name: String
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    storage: IntegerOptional
    artifacts: RelationshipManager
    device_services: RelationshipManager
    device_type: RelatedNode
    hosting_device: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceVirtualFabric(CoreNode):
    deployment_size: DropdownOptional
    name: String
    status: DropdownOptional
    customer: RelatedNode
    deployment: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimVirtualInterface(DcimInterface):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    device: RelatedNode
    interface_services: RelationshipManager
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    parent_interface: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimBidiSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimCable(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimConsoleInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    port: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDeviceType(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    part_number: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimEndpoint(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericDevice(LineageSource, CoreProfile, CoreNode):
    os_version: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalDevice(LineageSource, CoreProfile, CoreNode):
    os_version: StringOptional
    position: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPlatform(LineageSource, CoreProfile, CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimStandardSFP(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimSubInterface(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimVirtualDevice(LineageSource, CoreProfile, CoreNode):
    cpu: IntegerOptional
    memory: IntegerOptional
    os_version: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    storage: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimVirtualInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileGeneratorTarget(LineageSource, CoreProfile, CoreNode):
    checksum: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    fqdn: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLoadbalancerHealthCheck(LineageSource, CoreProfile, CoreNode):
    fall: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rise: IntegerOptional
    timeout: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLoadbalancerServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationBuilding(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    is_cloud: BooleanOptional
    physical_address: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationCountry(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    timezone: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationHosting(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationMetro(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRack(LineageSource, CoreProfile, CoreNode):
    checksum: StringOptional
    description: StringOptional
    facility_id: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    rack_type: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRegion(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationSuite(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileNetworkManagementServer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationCustomer(LineageSource, CoreProfile, CoreNode):
    customer_id: StringOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationManufacturer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationProvider(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingAggregateRoute(LineageSource, CoreProfile, CoreNode):
    discard: BooleanOptional
    export_policies: StringOptional
    import_policies: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingAutonomousSystem(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingBGPCommunity(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingBGPPeerGroup(LineageSource, CoreProfile, CoreNode):
    bfd_enabled: BooleanOptional
    ebgp_multihop: IntegerOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    password: StringOptional
    peer_group_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    route_reflector_client: BooleanOptional
    send_community: BooleanOptional
    send_community_extended: BooleanOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingBGPRRCluster(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingOSPFArea(LineageSource, CoreProfile, CoreNode):
    area_type: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingOSPFInterface(LineageSource, CoreProfile, CoreNode):
    authentication_key: StringOptional
    authentication_mode: DropdownOptional
    metric: IntegerOptional
    mode: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPIMInterface(LineageSource, CoreProfile, CoreNode):
    dr_priority: IntegerOptional
    hello_interval: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPolicy(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPolicyAggregate(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPolicyBGP(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPolicyOSPF(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingPolicyPIM(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileRoutingProtocol(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceBGP(LineageSource, CoreProfile, CoreNode):
    graceful_restart: BooleanOptional
    multipath: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceBGPPeering(LineageSource, CoreProfile, CoreNode):
    bfd_enabled: BooleanOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    med: IntegerOptional
    password: StringOptional
    peering_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    remove_private_as: BooleanOptional
    send_community: BooleanOptional
    send_extended_community: BooleanOptional
    session_scope: DropdownOptional
    session_type: DropdownOptional
    status: DropdownOptional
    ttl_security: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGeneric(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGenericDevice(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGenericInterfaces(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceNetworkSegment(LineageSource, CoreProfile, CoreNode):
    environment: DropdownOptional
    external_routing: BooleanOptional
    profile_name: String
    profile_priority: IntegerOptional
    segment_type: DropdownOptional
    status: DropdownOptional
    tenant_isolation: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceOSPF(LineageSource, CoreProfile, CoreNode):
    process_id: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    reference_bandwidth: IntegerOptional
    router_type: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceOSPFPeering(LineageSource, CoreProfile, CoreNode):
    area_type: DropdownOptional
    authentication_key: StringOptional
    authentication_type: DropdownOptional
    cost: IntegerOptional
    dead_interval: IntegerOptional
    hello_interval: IntegerOptional
    network_type: DropdownOptional
    peering_type: DropdownOptional
    priority: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    retransmit_interval: IntegerOptional
    session_scope: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServicePIM(LineageSource, CoreProfile, CoreNode):
    dr_priority: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rp_mode: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServicePeering(LineageSource, CoreProfile, CoreNode):
    peering_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    session_scope: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceRouting(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceVIP(LineageSource, CoreProfile, CoreNode):
    balance: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    ssl_certificate: StringOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceVirtualFabric(LineageSource, CoreProfile, CoreNode):
    deployment_size: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyDataCenter(LineageSource, CoreProfile, CoreNode):
    amount_of_super_spines: IntegerOptional
    fabric_interface_sorting_method: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    spine_interface_sorting_method: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyDeployment(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyElement(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileTopologyPod(LineageSource, CoreProfile, CoreNode):
    amount_of_spines: IntegerOptional
    checksum: StringOptional
    leaf_interface_sorting_method: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    spine_interface_sorting_method: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimConsoleInterface(
    LineageSource,
    CoreObjectComponentTemplate,
    TemplateDcimInterface,
    TemplateDcimEndpoint,
    TemplateCoreArtifactTarget,
    CoreNode,
):
    description: StringOptional
    name: String
    port: IntegerOptional
    role: DropdownOptional
    speed: IntegerOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    cable: RelatedNode
    device: RelatedNode
    interface_services: RelationshipManager
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimPhysicalDevice(
    LineageSource,
    TemplateCoreArtifactTarget,
    TemplateDcimGenericDevice,
    CoreObjectTemplate,
    CoreNode,
):
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    device_services: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimPhysicalInterface(
    LineageSource,
    CoreObjectComponentTemplate,
    TemplateDcimInterface,
    TemplateDcimEndpoint,
    TemplateDcimSubInterface,
    CoreNode,
):
    description: StringOptional
    interface_type: DropdownOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    cable: RelatedNode
    device: RelatedNode
    interface_services: RelationshipManager
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    plugged_sfp: RelatedNode
    related_nodes: RelationshipManager
    sub_interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimVirtualDevice(
    LineageSource,
    TemplateCoreArtifactTarget,
    TemplateDcimGenericDevice,
    CoreObjectTemplate,
    CoreNode,
):
    cpu: IntegerOptional
    memory: IntegerOptional
    os_version: StringOptional
    role: DropdownOptional
    status: DropdownOptional
    storage: IntegerOptional
    template_name: String
    artifacts: RelationshipManager
    device_services: RelationshipManager
    device_type: RelatedNode
    hosting_device: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimVirtualInterface(
    LineageSource, CoreObjectComponentTemplate, TemplateDcimInterface, CoreNode
):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: DropdownOptional
    template_name: String
    device: RelatedNode
    interface_services: RelationshipManager
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    parent_interface: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
