query VirtualFabricValidation($fabric_id: ID!) {
  ServiceVirtualFabric(ids: [$fabric_id]) {
    edges {
      node {
        id
        name {
          value
        }
        status {
          value
        }
        customer {
          node {
            name {
              value
            }
          }
        }
        deployment {
          node {
            name {
              value
            }
          }
        }
        design_pattern {
          node {
            name {
              value
            }
            maximum_network_segments {
              value
            }
            maximum_ip_prefixes {
              value
            }
            maximum_external_connections {
              value
            }
            maximum_bgp_sessions {
              value
            }
            maximum_load_balancers {
              value
            }
            maximum_firewall_rules {
              value
            }
            maximum_endpoints {
              value
            }
            maximum_bandwidth_mbps {
              value
            }
          }
        }
      }
    }
  }
}