fragment PhysicalInterfaceFields on DcimPhysicalInterface {
  hfid
  name {
    value
  }
  device {
    node {
      ... on DcimPhysicalDevice {
        name {
          value
        }
        rack {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}

fragment CableFields on DcimCable {
  __typename
  id
  display_label
  type {
    value
  }
  endpoints {
    edges {
      node {
        ...PhysicalInterfaceFields
      }
    }
  }
}

query topology_cabling($id: ID) {
  TopologyPhysicalDeployment(ids: [$id]) {
    edges {
      node {
        cables {
          edges {
            node {
              ...CableFields
            }
          }
        }
        ... on TopologyDeployment{
          name{
            value
          }
        }
      }
    }
  }
}
