fragment PhysicalInterfaceFields on DcimPhysicalInterface {
  hfid
  name { value }
  device {
    node {
      ... on DcimPhysicalDevice {
        rack {
          node {
            name { value }
          }
        }
      }
    }
  }
}

fragment CableFields on DcimCable {
  __typename
  id
  type { value }
  endpoints {
    edges {
      node {
        ...PhysicalInterfaceFields
      }
    }
  }
}

query FabricCablingPlanQuery($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        children {
          edges {
            node {
              ... on TopologyPod {
                name { value }
                devices {
                  edges {
                    node {
                      interfaces {
                        edges {
                          node {
                            ... on DcimPhysicalInterface {
                              cable {
                                node {
                                  ...CableFields
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
