query topology_info($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        name {
          value
        }
        devices(
          role__values: [
            "leaf"
            "spine"
            "firewall"
            "edge"
            "core"
            "border-leaf"
            "super-spine"
          ]
        ) {
          edges {
            node {
              name {
                value
              }
              role {
                value
              }
              os_version {
                value
              }
              primary_address {
                node {
                  address {
                    value
                  }
                }
              }
              platform {
                node {
                  name {
                    value
                  }
                  containerlab_os {
                    value
                  }
                }
              }
              device_type {
                node {
                  name {
                    value
                  }
                }
              }
              interfaces {
                edges {
                  node {
                    name {
                      value
                    }
                    role {
                      value
                    }
                    ... on DcimPhysicalInterface {
                      cable {
                        node {
                          hfid
                          display_label
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        children {
          edges {
            node {
              devices(
                role__values: [
                  "leaf"
                  "spine"
                  "firewall"
                  "edge"
                  "core"
                  "border-leaf"
                  "super-spine"
                ]
              ) {
                edges {
                  node {
                    name {
                      value
                    }
                    role {
                      value
                    }
                    os_version {
                      value
                    }
                    primary_address {
                      node {
                        address {
                          value
                        }
                      }
                    }
                    platform {
                      node {
                        name {
                          value
                        }
                        containerlab_os {
                          value
                        }
                      }
                    }
                    device_type {
                      node {
                        name {
                          value
                        }
                      }
                    }
                    interfaces {
                      edges {
                        node {
                          name {
                            value
                          }
                          role {
                            value
                          }
                          ... on DcimPhysicalInterface {
                            cable {
                              node {
                                hfid
                                display_label
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
