query FabricGeneratorQuery($name: String!) {
  TopologyDataCenter(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        size {
          value
        }
        fully_managed {
          value
        }
        amount_of_super_spines {
          value
        }
        super_spine_switch_template {
          node {
            __typename
            id
            device_type {
              node {
                id
              }
            }
            platform {
              node {
                id
              }
            }
          }
        }
      }
    }
  }
}
