query device($name: String!) {
  TopologyDataCenter(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        description {
          value
        }
        strategy{
          value
        }
        management_subnet {
          node {
            id
            prefix {
              value
            }
          }
        }
        technical_subnet {
          node {
            id
            prefix {
              value
            }
          }
        }
        customer_subnet {
          node {
            id
            prefix {
              value
            }
          }
        }
        public_subnet {
          node {
            id
            prefix {
              value
            }
          }
        }
        location {
          node {
            id
          }
        }
        provider {
          node {
            id
          }
        }
        emulation {
          value
        }
        design {
          node {
            name {
              value
            }
            elements {
              edges {
                node {
                  ... on DesignElement {
                    quantity {
                      value
                    }
                    role {
                      value
                    }
                    template {
                      node {
                        id
                        ... on TemplateDcimPhysicalDevice {
                          template_name {
                            value
                          }
                          __typename
                          interfaces {
                            edges {
                              node {
                                ... on TemplateDcimPhysicalInterface {
                                  name {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                }
                                ... on TemplateDcimConsoleInterface {
                                  name {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                }
                              }
                            }
                            count
                          }
                        }
                        template_name {
                          value
                        }
                        ... on CoreObjectTemplate {
                          template_name {
                            value
                          }
                        }
                        ... on TemplateDcimVirtualDevice {
                          template_name {
                            value
                          }
                          __typename
                          interfaces {
                            edges {
                              node {
                                ... on TemplateDcimPhysicalInterface {
                                  name {
                                    value
                                  }
                                  role {
                                    value
                                  }
                                }
                              }
                            }
                            count
                          }
                        }
                        template_name {
                          value
                        }
                        ... on CoreObjectTemplate {
                          template_name {
                            value
                          }
                        }
                      }
                    }
                    device_type {
                      node {
                        id
                        manufacturer {
                          node {
                            name {
                              value
                            }
                          }
                        }
                        platform {
                          node {
                            id
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}