query FabricGeneratorQuery($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        ... on TopologyDataCenter {
          index {
            value
          }
          size {
            value
          }
          amount_of_super_spines {
            value
          }
          super_spine_template {
            node {
              id
              template_name {
                value
              }
              platform {
                node {
                  id
                }
              }
              device_type {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
