query GetEndpointForConnectivity($endpoint_id: ID!) {
  # Get the endpoint device
  DcimGenericDevice(ids: [$endpoint_id]) {
    edges {
      node {
        id
        name {
          value
        }
        role {
          value
        }
        ... on DcimPhysicalDevice {
          rack {
            node {
              id
              name {
                value
              }
              row_index{
                value
              }
              # Get all devices in the same rack
              devices (role__values: ["leaf", "tor"]) {
                edges {
                  node {
                    ... on DcimPhysicalDevice {
                      id
                      name {
                        value
                      }
                      role {
                        value
                      }
                      # Get all interfaces for rack leafs
                      interfaces {
                        edges {
                          node {
                            ... on DcimPhysicalInterface {
                              id
                              name {
                                value
                              }
                              role {
                                value
                              }
                              cable {
                                node {
                                  id
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              ... on DcimPhysicalInterface {
                id
                name {
                  value
                }
                role {
                  value
                }
                cable {
                  node {
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}