query equinix_pop($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        name {
          value
        }
        devices {
          edges {
            node {
              name {
                value
              }
              device_type{
                node{
                  name{
                    value
                  }
                }
              }
              interfaces {
                edges {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
