fragment RackDeviceCountFields on LocationRack {
  id
  index {
    value
  }
  row_index {
    value
  }
  leafs: fabric_templates(role__value: "leaf") {
    edges {
      node {
        quantity {
          value
        }
      }
    }
  }
  tors: fabric_templates(role__value: "tor") {
    edges {
      node {
        quantity {
          value
        }
      }
    }
  }
}

query PodRacksForOffset($pod_id: ID!) {
  TopologyPod(ids: [$pod_id]) {
    edges {
      node {
        racks {
          edges {
            node {
              ...RackDeviceCountFields
            }
          }
        }
      }
    }
  }
}
