query RackGenerator($name: String!) {
  LocationRack(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
        index {
          value
        }
        rack_type {
          value
        }
        row{
          value
        }
        fabric_templates {
          edges {
            node {
              name {
                value
              }
              role {
                value
              }
              quantity {
                value
              }
              template {
                node {
                  id
                  ... on TemplateDcimPhysicalDevice {
                    platform {
                      node {
                        id
                        name{
                          value
                        }
                      }
                    }
                    device_type{
                      node{
                        id
                      }
                    }
                    interfaces(role__value: "uplink") {
                      edges {
                        node {
                          name {
                            value
                          }
                          role {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        pod {
          node {
            id
            name {
              value
            }
            index {
              value
            }
            devices(role__value: "spine"){
              edges{
                node{
                  name{
                    value
                  }
                }
              }
            }
            parent {
              node {
                ... on TopologyDataCenter {
                  id
                  name {
                    value
                  }
                  index {
                    value
                  }
                  design_pattern {
                    node {
                      naming_convention {
                        value
                      }
                      maximum_rack_leafs{
                        value
                      }
                      maximum_tors{
                        value
                      }
                      maximum_middle_racks{
                        value
                      }
                    }
                  }
                }
              }
            }
            amount_of_spines {
              value
            }
            leaf_interface_sorting_method {
              value
            }
            spine_interface_sorting_method {
              value
            }
            loopback_pool {
              node {
                id
              }
            }
            prefix_pool {
              node {
                id
              }
            }
            deployment_type{
              value
            }
            spine_template {
              node {
                id
                interfaces(role__value: "leaf") {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
