query RackElevation($name: String!) {
  LocationRack(name__value: $name) {
    edges {
      node {
        __typename
        name: name {
          value
        }
        height: height {
          value
        }
        devices: devices {
          edges {
            node {
              __typename
              display_label
              ... on DcimPhysicalDevice {
                name: name {
                  value
                }
                status: status {
                  color
                }
              }
              position: position {
                value
              }
              rack_face: rack_face {
                value
              }
              device_type: device_type {
                node {
                  __typename
                  display_label
                  height: height {
                    value
                  }
                  full_depth: full_depth {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
