query GetPodWithServers($pod_name: String!) {
  topology_pod: TopologyPod(name__value: $pod_name) {
    edges {
      node {
        id
        name { value }
        parent {
          node {
            id
            name { value }
          }
        }
        # Racks that contain leaf switches
        racks {
          edges {
            node {
              id
              name { value }
              # Devices in rack (leaves created by rack generator)
              devices {
                edges {
                  node {
                    id
                    name { value }
                    # Leaf downlink interfaces to servers
                    interfaces {
                      edges {
                        node {
                          id
                          name { value }
                          role { value }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
