query device($name: String!, deployment=deployment__name__value) {
  ServiceVirtualFabric(custome__name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        description {
          value
        }
      }
    }
  }
}
