query ComputedDCCapacitySummary($id: ID!) {
  TopologyDataCenter(ids: [$id]) {
    edges {
      node {
        name {
          value
        }
        amount_of_super_spines {
          value
        }
        design_pattern {
          node {
            maximum_super_spines {
              value
            }
            maximum_pods {
              value
            }
            maximum_spines {
              value
            }
            maximum_leafs {
              value
            }
            maximum_tors {
              value
            }
          }
        }
        children {
          edges {
            node {
              ... on TopologyPod {
                name {
                  value
                }
                spine_count: devices(role__value: "spine") {
                  count
                }
                leaf_count: devices(role__value: "leaf") {
                  count
                }
                tor_count: devices(role__value: "tor") {
                  count
                }
              }
            }
          }
        }
      }
    }
  }
}
