query firewall_config($device: String!) {
  DcimGenericDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        ... on DcimDevice{
          asn{
            node{
              name{
                value
              }
            }
          }
        }        
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description{
                value
              }
              enabled{
                value
              }               
              ... on DcimInterfaceL3 {
                role {
                  value
                }
                security_zone {
                  node {
                    name {
                      value
                    }
                  }
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}