query leaf_config($device: String!) {
  DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status{
                value
              }
              role{
                value
              }
              service{
                edges{
                  node{
                    ... on ServiceLayer2Network{
                      vlan{
                        value
                      }
                    }
                    __typename
                    name{
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}