query leaf_config($device: String!) {
  DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_service{
          count
          edges{
            node{
              __typename
              name{
                value
              }
              ... on ServiceOspPeering{
                area{
                  value
                }
              }
              ... on ServiceBgpPeering{
                asn{
                  value
                }
              }
              ... on ServiceLayer3Gateway{
                is_anycast{
                  value
                }
                prefix{
                  node{
                    network_address{
                      value
                    }
                    ip_namespace{
                      node{
                        name{
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status{
                value
              }
              role{
                value
              }
              service{
                edges{
                  node{
                    ... on ServiceLayer2Network{
                      vlan{
                        value
                      }
                    }
                    __typename
                    name{
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}