query leaf_config($device: String!) {
  DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_service {
          count
          edges {
            node {
              __typename
              name {
                value
              }
              ... on ServiceBGPSession {
                name {
                  value
                }
                local_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                local_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                remote_ip {
                  node {
                    address {
                      value
                    }
                  }
                }
                remote_as {
                  node {
                    asn {
                      value
                    }
                  }
                }
                peer_session {
                  node {
                    local_ip {
                      node {
                        address {
                          value
                        }
                      }
                    }
                    local_as {
                      node {
                        asn {
                          value
                        }
                      }
                    }
                    remote_ip {
                      node {
                        address {
                          value
                        }
                      }
                    }
                    remote_as {
                      node {
                        asn {
                          value
                        }
                      }
                    }
                  }
                }
                peer_group {
                  node {
                    name {
                      value
                    }
                    local_pref {
                      value
                    }
                    send_community {
                      value
                    }
                    address_family {
                      value
                    }
                    maximum_routes {
                      value
                    }
                    local_as {
                      node {
                        asn {
                          value
                        }
                      }
                    }
                    remote_as {
                      node {
                        asn {
                          value
                        }
                      }
                    }
                  }
                }
              }
              ... on ServiceOSPF {
                name {
                  value
                }
                router_id {
                  node {
                    address {
                      value
                    }
                  }
                }
                area {
                  node {
                    area {
                      value
                    }
                    namespace {
                      node {
                        name {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status {
                value
              }
              role {
                value
              }
              ... on DcimPhysicalInterface {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                      ip_namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
              ... on DcimVirtualInterface {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                      ip_namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
              service {
                edges {
                  node {
                    ... on ServiceNetworkSegment {
                      __typename
                      vni {
                        value
                      }
                      status {
                        value
                      }
                      description {
                        value
                      }
                      prefixes {
                        edges {
                          node {
                            prefix {
                              value
                            }
                          }
                        }
                      }
                    }
                    ... on ServiceOSPFArea {
                      __typename
                      area {
                        value
                      }
                      namespace {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                    ... on ServiceOSPFInterface {
                      __typename
                      authentication_key {
                        value
                      }
                      metric {
                        value
                      }
                      mode {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}