query GetServiceNetworkSegment($name: String!) {
  ServiceNetworkSegment(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        description {
          value
        }
        status {
          value
        }
        environment {
          value
        }
        vlan_id {
          value
        }
        external_routing {
          value
        }
        segment_type {
          value
        }
        tenant_isolation {
          value
        }
        customer {
          id
          name {
            value
          }
        }
        namespace {
          id
          name {
            value
          }
        }
        fabric {
          id
          name {
            value
          }
        }
      }
    }
  }
}