query spine_config($device: String!) {
  DcimPhysicalDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_service{
          count
          edges{
            node{
              __typename
              name{
                value
              }
              ... on ServiceOspfPeering{
                area{
                  value
                }
              }
            }
          }
        }      
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status{
                value
              }
              role{
                value
              }              
              service{
                edges{
                  node{
                    __typename
                    name{
                      value
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}