query topology_info($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        name {
          value
        }
        management {
          value
        }
        design {
          node {
            type {
              value
            }
          }
        }
        devices(role__values: ["leaf", "spine", "dc_firewall", "edge", "core"]) {
          edges {
            node {
              name {
                value
              }
              role {
                value
              }
              os_version {
                value
              }
              primary_address {
                node {
                  address {
                    value
                  }
                }
              }
              platform {
                node {
                  name {
                    value
                  }
                  containerlab_os {
                    value
                  }
                }
              }
              ... on DcimPhysicalDevice {
                device_type {
                  node {
                    name {
                      value
                    }
                  }
                }
              }
              interfaces {
                edges {
                  node {
                    name {
                      value
                    }
                    role {
                      value
                    }
                    ... on DcimPhysicalInterface {
                      connector {
                        node {
                          hfid
                          display_label
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}