#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Dropdown,
        DropdownOptional,
        Integer,
        String,
        StringOptional,
    )


class NetworkBuildingBlock(CoreNode):
    index: Integer
    name: String


class NetworkEndpoint(CoreNode):
    link: RelatedNode


class LocationPhysical(CoreNode):
    index: Integer
    name: String


class GeneratorTarget(CoreNode):
    checksum: StringOptional


class NetworkDevice(CoreArtifactTarget):
    hostname: String
    role: Dropdown
    interfaces: RelationshipManager
    loopback_ip: RelatedNode
    pod: RelatedNode
    rack: RelatedNode


class NetworkFabric(NetworkBuildingBlock):
    amount_of_super_spines: Integer
    super_spine_switch_template: RelatedNode


class LocationHall(LocationPhysical):
    pass


class IpamIPAddress(BuiltinIPAddress):
    pass


class IpamIPPrefix(BuiltinIPPrefix):
    role: Dropdown


class NetworkInterface(NetworkEndpoint):
    description: StringOptional
    index: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelatedNode
    ip_address: RelatedNode


class NetworkLink(CoreNode):
    medium: Dropdown
    name: String
    endpoints: RelationshipManager


class NetworkPod(NetworkBuildingBlock, GeneratorTarget):
    amount_of_spines: Integer
    role: DropdownOptional
    devices: RelationshipManager
    loopback_pool: RelatedNode
    prefix_pool: RelatedNode
    racks: RelationshipManager
    spine_switch_template: RelatedNode


class LocationRack(LocationPhysical, GeneratorTarget):
    rack_type: Dropdown
    devices: RelationshipManager
    leaf_switch_template: RelatedNode
    pod: RelatedNode
