fragment PeeringParticipant on DcimDevice {
  name { value }
  role { value }
}

fragment DeviceRoutingFields on DcimDevice {
  name { value }
  role { value }
  ... on DcimCapabilities {
    capabilities {
      edges {
        node {
          __typename
          ... on ManagedBGP {
            name { value }
            local_as { node { asn { value } } }
            peerings {
              edges {
                node {
                  name { value }
                  session_type { value }
                  bgp_processes {
                    edges {
                      node {
                        capabilities {
                          edges {
                            node {
                              ...PeeringParticipant
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          ... on ManagedOSPF {
            name { value }
          }
        }
      }
    }
  }
}

query GetDCTopology($dc_name: String!) {
  all_cables: DcimCable {
    count
  }
  TopologyDataCenter(name__value: $dc_name) {
    edges {
      node {
        devices {
          edges {
            node {
              ...DeviceRoutingFields
            }
          }
        }
      }
    }
  }
  TopologyPod(parent__name__value: $dc_name) {
    edges {
      node {
        devices {
          edges {
            node {
              ...DeviceRoutingFields
            }
          }
        }
        racks {
          edges {
            node {
              devices {
                edges {
                  node {
                    ...DeviceRoutingFields
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
