# yaml-language-server: $schema=https://schema.infrahub.app/infrahub/schema/latest.json
---
version: "1.0"

generics:
  - name: Protocol
    namespace: Routing
    description: "Generic protocol model for routing protocols"
    label: "Protocol"
    icon: "carbon:router"
    include_in_menu: false
    attributes:
      # TODO: Should be computed later
      - name: description
        kind: Text
        optional: false
        unique: true
        description: "Description of the protocol"
        order_weight: 1100
      - name: status
        kind: Dropdown
        choices:
          - name: active
            label: Active
            description: "Configuration is active and operational."
            color: "#A9CCE3" # pastel blue
          - name: disabled
            label: Disabled
            description: "Configuration has been disabled."
            color: "#D3D3D3" # light grey
          - name: deleted
            label: Deleted
            description: "Configuration has been deleted."
            color: "#FAD7A0" # pastel orange
        description: "Status of the Protocol Configuration."
        order_weight: 1150
    relationships:
      - name: device
        peer: DcimGenericDevice
        optional: false
        cardinality: one
        kind: Parent
        order_weight: 1050
      # - name: vrf
      #   label: VRF
      #   peer: IpamVRF
      #   optional: false
      #   cardinality: one
      #   kind: Attribute
      #   order_weight: 1075
