query capability_guard {
  DcimDevice {
    edges {
      node {
        name { value }
        role { value }
        ... on DcimCapabilities {
          capabilities {
            edges {
              node {
                __typename
                ... on ManagedGeneric {
                  name { value }
                }
              }
            }
          }
        }
      }
    }
  }
}
