query capability_guard {
  DcimDevice {
    edges {
      node {
        name { value }
        role { value }
        device_capabilities {
          edges {
            node {
              __typename
              ... on ManagedGeneric {
                name { value }
              }
            }
          }
        }
      }
    }
  }
}
