query loadbalancer_validation($device: String!) {
  DcimVirtualDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        device_type {
          node {
            platform {
              node {
                netmiko_device_type {
                  value
                }
              }
            }
            manufacturer {
              node {
                name {
                  value
                }
              }
            }
          }
        }
        role {
          value
        }
        status {
          value
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              status {
                value
              }
              role {
                value
              }
              ... on DcimVirtualInterface {
                ip_address {
                  node {
                    address {
                      value
                    }
                    ip_namespace {
                      node {
                        name {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        device_capabilities {
          edges {
            node {
              __typename
              name {
                value
              }
              status {
                value
              }
              ... on OnpremLoadbalancer {
                vip_services {
                  edges {
                    node {
                      hostname {
                        value
                      }
                      protocol {
                        value
                      }
                      ssl_certificate {
                        value
                      }
                      vip_ip {
                        node {
                          address {
                            value
                          }
                        }
                      }
                      health_checks {
                        edges {
                          node {
                            check {
                              value
                            }
                            rise {
                              value
                            }
                            fall {
                              value
                            }
                            timeout {
                              value
                            }
                          }
                        }
                      }
                      backend_pool {
                        node {
                          load_balancing_algorithm {
                            value
                          }
                          onprem_servers {
                            edges {
                              node {
                                hostname {
                                  value
                                }
                                ip_address {
                                  node {
                                    address {
                                      value
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
