query loadbalancer_validation($instance: String!) {
  OnpremLoadbalancer(name__value: $instance) {
    edges {
      node {
        name {
          value
        }
        status {
          value
        }
        frontend_servers {
          count
          edges {
            node {
              __typename
              name {
                value
              }
              role {
                value
              }
              status {
                value
              }
              primary_address {
                node {
                  address {
                    value
                  }
                }
              }
              interfaces {
                edges {
                  node {
                    __typename
                    name {
                      value
                    }
                    status {
                      value
                    }
                    ... on DcimPhysicalInterface {
                      ip_address {
                        node {
                          address {
                            value
                          }
                          ip_namespace {
                            node {
                              name {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                    ... on DcimVirtualInterface {
                      ip_address {
                        node {
                          address {
                            value
                          }
                          ip_namespace {
                            node {
                              name {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        vip_services {
          edges {
            node {
              hostname {
                value
              }
              protocol {
                value
              }
              port {
                value
              }
              ssl_certificate {
                value
              }
              vip_ip {
                node {
                  address {
                    value
                  }
                }
              }
              health_checks {
                edges {
                  node {
                    check {
                      value
                    }
                    rise {
                      value
                    }
                    fall {
                      value
                    }
                    timeout {
                      value
                    }
                  }
                }
              }
              backend_pool {
                node {
                  load_balancing_algorithm {
                    value
                  }
                  onprem_servers {
                    count
                    edges {
                      node {
                        hostname {
                          value
                        }
                        ip_address {
                          node {
                            address {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
