query RackGeneratorQuery($rack_name: String!) {
  LocationRack(name__value: $rack_name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
				index {
					value
				}
				rack_type {
					value
				}
				amount_of_leafs {
					value
				}
				leaf_switch_template {
					node {
						__typename
						id
					}
				}
				parent {
					node {
						__typename
						id
						name {
							value
						}
					}
				}
				pod {
					node {
						id
						name {
							value
						}
						index {
							value
						}
						prefix_pool {
							node {
								__typename
								id
							}
						}
						loopback_pool {
							node {
								__typename
								id
							}
						}
						amount_of_spines {
							value
						}
						leaf_interface_sorting_method {
							value
						}
						spine_interface_sorting_method {
							value
						}
					}
				}
      }
    }
  }
}
