#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPNamespace,
    BuiltinIPPrefix,
    BuiltinTag,
    CoreArtifactTarget,
    CoreIPAddressPool,
    CoreIPPrefixPool,
    CoreNode,
    CoreNumberPool,
    CoreObjectTemplate,
    IpamNamespace,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelationshipAttribute, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Boolean,
        BooleanOptional,
        DateTimeOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPHostOptional,
        String,
        StringOptional,
        URLOptional,
    )


class DcimCapabilities(CoreNode):
    name: StringOptional


class TopologyCircuit(CoreNode):
    bandwidth: IntegerOptional
    description: StringOptional
    name: String
    status: Dropdown
    locations: RelationshipManager[TopologyConnectableLocation]
    owner: RelationshipAttribute[OrganizationCustomer]
    provider: RelationshipAttribute[OrganizationProvider]


class TopologyClusterHosting(CoreNode):
    name: String
    clusters: RelationshipManager[VirtCluster]


class TopologyConnectableLocation(CoreNode):
    name: String


class TopologyConnector(CoreNode):
    name: StringOptional


class ManagedController(CoreNode):
    controller_type: Dropdown
    managed_devices: RelationshipManager[DcimDevice]


class TopologyCustomer(CoreNode):
    environment: Dropdown
    name: String
    status: Dropdown
    namespace: RelationshipAttribute[BuiltinIPNamespace]
    owner: RelationshipAttribute[OrganizationEntity]


class TopologyCustomerTemplate(CoreNode):
    dedicated_firewall: Boolean
    dedicated_loadbalancer: Boolean
    dedicated_proxy: Boolean
    default_environment: Dropdown
    description: StringOptional
    name: String
    network_segment_count: Integer
    size: Dropdown


class TopologyDeployment(CoreNode):
    name: String


class TopologyDesign(CoreNode):
    name: String


class DcimDevice(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device_type: RelationshipAttribute[DcimDeviceType]
    interfaces: RelationshipManager[DcimInterface]
    platform: RelationshipAttribute[DcimPlatform]
    primary_address: RelationshipAttribute[IpamIPAddress]
    tags: RelationshipManager[BuiltinTag]


class TopologyDeviceHosting(CoreNode):
    name: String
    naming_convention: Dropdown
    devices: RelationshipManager[DcimDevice]


class DcimEndpoint(CoreNode):
    cable: RelationshipAttribute[DcimCable]


class OrganizationEntity(CoreNode):
    org_id: StringOptional


class TopologyExchangeGateway(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    common_exchange: RelationshipAttribute[TopologyCommonExchange]
    customer_deployments: RelationshipManager[TopologyDeployment]
    namespace_a: RelationshipAttribute[IpamNamespace]
    namespace_z: RelationshipAttribute[IpamNamespace]


class LocationGeneric(CoreNode):
    name: String
    shortname: String
    tags: RelationshipManager[BuiltinTag]


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    tags: RelationshipManager[BuiltinTag]


class AppGeneric(CoreNode):
    description: StringOptional


class ManagedGeneric(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown


class ManagedGenericCluster(CoreNode):
    cluster_capabilities: RelationshipManager[VirtCluster]


class ManagedGenericDevice(CoreNode):
    capabilities: RelationshipManager[DcimCapabilities]


class ManagedGenericInterfaces(CoreNode):
    interface_capabilities: RelationshipManager[DcimInterface]


class DcimGenericSFP(CoreNode):
    form_factor: Dropdown
    serial: StringOptional
    sfp_type: Dropdown
    status: Dropdown
    interface: RelationshipAttribute[DcimInterface]
    manufacturer: RelationshipAttribute[OrganizationManufacturer]


class ManagedHA(CoreNode):
    group_id: IntegerOptional
    mode: Dropdown
    preempt: Boolean
    priority: Integer


class ManagedInlineService(CoreNode):
    pass


class AppInstance(CoreNode):
    name: String


class DcimInterface(CoreNode):
    description: StringOptional
    index: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelationshipAttribute[DcimDevice]
    tags: RelationshipManager[BuiltinTag]


class ManagedLoadBalancer(CoreNode):
    description: StringOptional
    lb_type: DropdownOptional
    lb_vendor: DropdownOptional
    name: String
    scheme: DropdownOptional
    status: Dropdown
    tags: RelationshipManager[BuiltinTag]


class NetworkManagementServer(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    ip_addresses: RelationshipManager[IpamIPAddress]
    location: RelationshipManager[LocationGeneric]


class ManagedNetworkSegment(CoreNode):
    customer_name: String
    description: StringOptional
    environment: Dropdown
    isolation_mode: Dropdown
    name: String
    pbr_enabled: Boolean
    segment_role: Dropdown
    segment_type: DropdownOptional
    status: Dropdown
    gateway: RelationshipAttribute[IpamIPAddress]
    owner: RelationshipAttribute[OrganizationCustomer]


class ManagedPeering(CoreNode):
    pass


class TopologyPhysicalDeployment(CoreNode):
    name: String
    cables: RelationshipManager[DcimCable]


class RoutingProtocol(CoreNode):
    description: String
    status: Dropdown
    device: RelationshipAttribute[DcimDevice]


class ManagedProxyService(CoreNode):
    name: String


class CustomerQuotation(CoreNode):
    description: StringOptional
    estimated_total_cost: IntegerOptional
    name: String
    request_type: Dropdown
    status: Dropdown
    line_items: RelationshipManager[CustomerQuotationLineItem]
    owner: RelationshipAttribute[OrganizationEntity]


class TopologyRackHosting(CoreNode):
    name: String
    racks: RelationshipManager[LocationRack]


class CloudResource(CoreNode):
    cloud_id: StringOptional
    description: StringOptional
    name: String
    status: DropdownOptional


class ManagedRouting(CoreNode):
    name: String


class ManagedSaasService(CoreNode):
    contract_end_date: StringOptional
    data_classification: Dropdown
    description: StringOptional
    name: String
    service_tier: Dropdown
    status: Dropdown
    tenant_id: StringOptional


class TopologySegmentHosting(CoreNode):
    name: String
    l3_vni_pool: RelationshipAttribute[CoreNumberPool]
    vlan_pool: RelationshipAttribute[CoreNumberPool]
    vni_pool: RelationshipAttribute[CoreNumberPool]


class DcimSubInterface(CoreNode):
    sub_interfaces: RelationshipManager[DcimVirtualInterface]


class ManagedAAA(ManagedGeneric, ManagedGenericDevice):
    accounting_enabled: Boolean
    authentication_order: Dropdown
    authorization_commands: Boolean
    servers: RelationshipManager[ManagedAAAServer]


class ManagedAAAServer(CoreNode):
    name: String
    port: IntegerOptional
    protocol: Dropdown
    secret_key: StringOptional
    timeout: Integer
    aaa_config: RelationshipAttribute[ManagedAAA]
    address: RelationshipAttribute[IpamIPAddress]


class CloudAccount(CloudResource, CoreArtifactTarget):
    account_id: StringOptional
    environment: DropdownOptional
    owner: RelationshipAttribute[OrganizationEntity]
    provider: RelationshipAttribute[OrganizationProvider]


class AppApplication(AppGeneric):
    cost_center: StringOptional
    criticality: Dropdown
    environment: Dropdown
    fqdn: String
    ingress_mode: Dropdown
    label: String
    name: StringOptional
    security_profile: Dropdown
    owner: RelationshipAttribute[OrganizationCustomer]


class RoutingAutonomousSystem(CoreNode):
    asn: Integer
    description: StringOptional
    name: String
    location: RelationshipAttribute[LocationGeneric]
    owner: RelationshipAttribute[OrganizationProvider]


class ManagedBGP(ManagedGeneric, ManagedGenericDevice, ManagedRouting):
    confederation_identifier: IntegerOptional
    graceful_restart: Boolean
    multipath: Boolean
    local_as: RelationshipAttribute[RoutingAutonomousSystem]
    router_id: RelationshipAttribute[IpamIPAddress]


class RoutingBGPAddressFamily(CoreNode):
    advertise_all_vni: Boolean
    advertise_default_gw: Boolean
    advertise_svi_ip: Boolean
    afi: Dropdown
    description: StringOptional
    safi: Dropdown


class ManagedBGPPeering(ManagedGeneric, ManagedPeering, ManagedGenericInterfaces):
    bfd_enabled: Boolean
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    med: IntegerOptional
    remove_private_as: Boolean
    route_reflector_client: Boolean
    send_community: Boolean
    send_extended_community: Boolean
    session_type: Dropdown
    ttl: Integer
    bgp_processes: RelationshipManager[ManagedBGP]
    password: RelationshipAttribute[RoutingPassword]


class DcimBidiSFP(DcimGenericSFP):
    wavelength_rx: Integer
    wavelength_tx: Integer


class VirtCNI(ManagedGeneric, ManagedGenericCluster):
    bgp_enabled: Boolean
    encapsulation: DropdownOptional
    plugin: Dropdown
    pod_cidr: StringOptional
    service_cidr: StringOptional
    version: StringOptional
    bgp_peers: RelationshipManager[RoutingAutonomousSystem]


class ManagedCRMService(ManagedSaasService):
    instance_url: StringOptional
    provider: Dropdown
    sandbox: Boolean


class DcimCable(CoreNode):
    name: String
    type: Dropdown
    endpoints: RelationshipManager[DcimEndpoint]


class LocationCampus(LocationGeneric):
    physical_address: StringOptional
    owner: RelationshipAttribute[OrganizationGeneric]


class LocationCampusBuilding(LocationGeneric):
    pass


class LocationCampusFloor(LocationGeneric):
    area_sqm: Integer
    conference_rooms: Integer
    employee_count: Integer
    index: Integer


class TopologyCloud(TopologyDeployment):
    pass


class ManagedCloudFirewallHA(ManagedHA, ManagedGeneric, ManagedInlineService):
    policy_arn: StringOptional
    provider: Dropdown
    region: StringOptional


class ManagedCloudProxy(ManagedSaasService, ManagedInlineService, ManagedProxyService):
    deployment_model: Dropdown
    provider: Dropdown
    region: StringOptional


class TopologyCloudRegion(TopologyDeployment):
    status: Dropdown
    direct_connects: RelationshipManager[CloudDirectConnect]
    location: RelationshipAttribute[LocationMetro]
    virtual_networks: RelationshipManager[CloudVirtualNetwork]
    vpn_gateways: RelationshipManager[CloudVPNGateway]


class TopologyCloudZone(TopologyDeployment):
    instances: RelationshipManager[CloudInstance]
    network_segments: RelationshipManager[CloudNetworkSegment]


class VirtCluster(CoreNode):
    description: StringOptional
    ha_enabled: Boolean
    name: String
    platform: Dropdown
    status: Dropdown
    total_cpu: StringOptional
    total_memory_gb: StringOptional
    total_storage_gb: StringOptional
    version: StringOptional
    cloud_account: RelationshipAttribute[CloudAccount]
    deployment: RelationshipAttribute[TopologyDeployment]
    ip_namespace: RelationshipAttribute[IpamNamespace]
    node_pools: RelationshipManager[VirtNodePool]
    proxy_service: RelationshipAttribute[ManagedProxyService]
    tags: RelationshipManager[BuiltinTag]
    vip_service: RelationshipAttribute[LoadbalancerVIP]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class TopologyColocation(CoreArtifactTarget, TopologyDeployment):
    pass


class TopologyColocationMetro(CoreArtifactTarget, TopologyDeployment, TopologySegmentHosting):
    location: RelationshipAttribute[LocationMetro]


class TopologyColocationZone(
    TopologyDeployment, TopologyPhysicalDeployment, TopologyRackHosting, TopologyDeviceHosting
):
    deployment_type: Dropdown


class TopologyCommonExchange(CoreNode):
    description: StringOptional
    is_default: Boolean
    name: String
    deployments: RelationshipManager[TopologyDeployment]
    exchange_gateways: RelationshipManager[TopologyExchangeGateway]
    namespace: RelationshipAttribute[IpamNamespace]


class AppComponent(AppGeneric):
    component_type: Dropdown
    name: String
    slug: StringOptional
    health_checks: RelationshipManager[LoadbalancerHealthCheck]
    instances: RelationshipManager[AppInstance]
    load_balancer: RelationshipAttribute[ManagedLoadbalancerHA]
    network_segment: RelationshipAttribute[ManagedNetworkSegment]
    proxy_service: RelationshipAttribute[ManagedProxyService]


class ManagedConferencingService(ManagedSaasService):
    media_optimization: Boolean
    provider: Dropdown


class DcimConsoleInterface(DcimInterface, DcimEndpoint, CoreArtifactTarget):
    port: Integer
    speed: Integer


class ManagedControllerPhysical(ManagedController, CoreArtifactTarget, DcimDevice, DcimCapabilities, AppInstance):
    position: IntegerOptional
    rack_face: Dropdown
    serial: StringOptional


class ManagedControllerVirtual(ManagedController, CoreArtifactTarget, DcimDevice, DcimCapabilities, AppInstance):
    cpu: IntegerOptional
    memory: IntegerOptional
    storage: IntegerOptional
    hosting_device: RelationshipAttribute[DcimPhysicalDevice]


class LocationCountry(LocationGeneric):
    timezone: StringOptional


class OrganizationCustomer(OrganizationGeneric, OrganizationEntity):
    pass


class TopologyCustomerCloud(TopologyCustomer, TopologyDeployment, TopologyClusterHosting, TopologyConnectableLocation):
    customer_name: String
    name: StringOptional
    cloud_account: RelationshipAttribute[CloudAccount]


class TopologyCustomerColocation(
    TopologyCustomer, TopologyDeployment, TopologyClusterHosting, TopologyConnectableLocation
):
    name: StringOptional


class TopologyCustomerDC(TopologyCustomer, TopologyDeployment, TopologyClusterHosting, TopologyConnectableLocation):
    name: StringOptional
    design: RelationshipAttribute[TopologyCustomerTemplateDC]


class CloudCustomerGateway(CloudResource):
    device_type: DropdownOptional
    account: RelationshipAttribute[CloudAccount]
    asn: RelationshipAttribute[RoutingAutonomousSystem]
    ip_address: RelationshipAttribute[IpamIPAddress]
    physical_device: RelationshipAttribute[DcimDevice]


class TopologyCustomerOffice(
    TopologyCustomer,
    TopologyDeployment,
    TopologyClusterHosting,
    TopologyPhysicalDeployment,
    TopologyDeviceHosting,
    TopologyConnectableLocation,
):
    name: StringOptional
    locations: RelationshipManager[LocationFacility]


class TopologyCustomerTemplateCloud(TopologyCustomerTemplate):
    pass


class TopologyCustomerTemplateColo(TopologyCustomerTemplate):
    uplink_100g_count: Integer
    uplink_10g_count: Integer
    uplink_400g_count: Integer
    uplink_40g_count: Integer


class TopologyCustomerTemplateDC(TopologyCustomerTemplate):
    uplink_100g_count: Integer
    uplink_10g_count: Integer
    uplink_400g_count: Integer
    uplink_40g_count: Integer


class TopologyDataCenter(
    CoreArtifactTarget,
    TopologyDeployment,
    TopologyPhysicalDeployment,
    TopologyConnectableLocation,
    TopologyDeviceHosting,
    TopologySegmentHosting,
):
    connectivity_mode: Dropdown
    fabric_interface_sorting_method: Dropdown
    index: Integer
    routing_strategy: Dropdown
    size: Dropdown
    spine_interface_sorting_method: Dropdown
    status: Dropdown
    underlay_protocol: Dropdown
    controllers: RelationshipManager[ManagedController]
    design: RelationshipManager[TopologyDataCenterDesign]
    fabric_asn_pool: RelationshipAttribute[CoreNumberPool]
    fabric_templates: RelationshipManager[TopologyElement]
    loopback_pool: RelationshipAttribute[CoreIPPrefixPool]
    management_pool: RelationshipAttribute[CoreIPAddressPool]
    technical_pool: RelationshipAttribute[CoreIPPrefixPool]


class TopologyDataCenterDesign(CoreNode):
    pass


class AppDependency(CoreNode):
    access_expires_at: DateTimeOptional
    access_status: Dropdown
    decision_at: DateTimeOptional
    decision_reason: StringOptional
    description: StringOptional
    name: String
    port_end: IntegerOptional
    port_start: IntegerOptional
    protocol: DropdownOptional
    source: RelationshipAttribute[AppComponent]
    target: RelationshipAttribute[AppComponent]


class DcimDeviceType(CoreNode):
    core_count: IntegerOptional
    cpu_count: IntegerOptional
    description: StringOptional
    full_depth: Boolean
    height: Integer
    max_routes: IntegerOptional
    memory_gb: IntegerOptional
    name: String
    part_number: StringOptional
    storage_gb: IntegerOptional
    tcam_entries: IntegerOptional
    unit_price: IntegerOptional
    weight: IntegerOptional
    manufacturer: RelationshipAttribute[OrganizationManufacturer]
    platform: RelationshipAttribute[DcimPlatform]
    tags: RelationshipManager[BuiltinTag]


class CloudDirectConnect(CloudResource):
    bandwidth: String
    connection_type: Dropdown
    vlan_id: IntegerOptional
    account: RelationshipAttribute[CloudAccount]
    location: RelationshipAttribute[LocationFacility]
    physical_devices: RelationshipManager[DcimDevice]
    region: RelationshipAttribute[TopologyCloudRegion]
    virtual_interfaces: RelationshipManager[CloudVirtualInterface]


class TopologyElement(CoreNode):
    quantity: Integer
    role: DropdownOptional
    template: RelationshipAttribute[CoreObjectTemplate]


class TopologyExternal(TopologyDeployment):
    pass


class TopologyExternalProviders(TopologyDeployment, TopologyConnectableLocation, TopologyDeviceHosting):
    provider_type: Dropdown
    status: Dropdown
    provider: RelationshipAttribute[OrganizationProvider]


class LocationFacility(LocationGeneric):
    facility_id: StringOptional
    is_cloud: Boolean
    physical_address: StringOptional
    owner: RelationshipAttribute[OrganizationGeneric]


class ManagedFirewallContext(ManagedGeneric, ManagedGenericInterfaces, ManagedInlineService):
    context_id: StringOptional
    cluster: RelationshipAttribute[ManagedFirewallHA]
    tenant: RelationshipAttribute[TopologyCustomer]


class ManagedFirewallHA(ManagedHA, ManagedGeneric, ManagedGenericDevice, ManagedInlineService):
    ha_protocol: Dropdown
    ha_timer: Dropdown
    capabilities: RelationshipManager[DcimCapabilities]


class ManagedHAInterface(ManagedGeneric, ManagedGenericInterfaces):
    link_type: Dropdown
    ha_domain: RelationshipAttribute[ManagedHA]


class LoadbalancerHealthCheck(CoreNode):
    check: Dropdown
    description: String
    fall: Integer
    rise: Integer
    timeout: Integer


class IpamIPAddress(BuiltinIPAddress):
    fqdn: StringOptional


class VirtIngress(ManagedGeneric, ManagedGenericCluster):
    address_pool: StringOptional
    controller: Dropdown
    version: StringOptional
    vip_prefix: RelationshipAttribute[IpamPrefix]


class CloudInstance(CloudResource, DcimCapabilities, AppInstance):
    cpu_count: IntegerOptional
    image: StringOptional
    instance_type: StringOptional
    memory_gb: IntegerOptional
    os_type: DropdownOptional
    private_ip: IPHostOptional
    public_ip: IPHostOptional
    root_volume_size_gb: IntegerOptional
    account: RelationshipAttribute[CloudAccount]
    availability_zone: RelationshipAttribute[TopologyCloudZone]
    network_segment: RelationshipAttribute[CloudNetworkSegment]
    security_groups: RelationshipManager[CloudSecurityGroup]


class CloudInternetGateway(CloudResource):
    account: RelationshipAttribute[CloudAccount]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class DcimLAGInterface(DcimInterface):
    lacp_mode: Dropdown
    lag_id: Integer
    minimum_links: Integer
    mtu: Integer
    ip_address: RelationshipAttribute[IpamIPAddress]
    member_interfaces: RelationshipManager[DcimPhysicalInterface]


class CloudLoadBalancer(ManagedLoadBalancer, CloudResource, CoreArtifactTarget):
    network_segments: RelationshipManager[CloudNetworkSegment]
    public_ips: RelationshipManager[CloudPublicIP]
    security_groups: RelationshipManager[CloudSecurityGroup]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class OnpremLoadbalancer(ManagedLoadBalancer, ManagedGeneric, CoreArtifactTarget):
    deployment: RelationshipAttribute[TopologyDeployment]


class ManagedLoadbalancerHA(ManagedHA, ManagedGeneric, ManagedGenericDevice, ManagedInlineService, ManagedLoadBalancer):
    capabilities: RelationshipManager[DcimCapabilities]


class ManagedMLAG(ManagedGeneric, ManagedGenericDevice, ManagedGenericInterfaces):
    domain_id: Integer
    reload_delay: Integer
    reload_delay_non_mlag: Integer
    virtual_peer_link: Boolean


class VirtManagementPlane(ManagedGeneric, ManagedGenericCluster):
    auth_method: DropdownOptional
    endpoint: StringOptional
    endpoint_access: DropdownOptional
    port: IntegerOptional
    management_ip: RelationshipAttribute[IpamIPAddress]


class OrganizationManufacturer(CoreNode):
    description: StringOptional
    name: String
    device_type: RelationshipManager[DcimDeviceType]
    platform: RelationshipManager[DcimPlatform]


class LocationMetro(LocationGeneric):
    pass


class VirtMonitoring(ManagedGeneric, ManagedGenericCluster):
    remote_write: StringOptional
    retention_days: IntegerOptional
    stack: Dropdown
    version: StringOptional


class CloudNATGateway(CloudResource):
    public_ip: IPHostOptional
    account: RelationshipAttribute[CloudAccount]
    network_segments: RelationshipManager[CloudNetworkSegment]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class ManagedNTP(ManagedGeneric, ManagedGenericDevice):
    timezone: String
    servers: RelationshipManager[ManagedNTPServer]


class ManagedNTPServer(CoreNode):
    name: String
    prefer: Boolean
    version: Integer
    address: RelationshipAttribute[IpamIPAddress]
    ntp_config: RelationshipAttribute[ManagedNTP]


class CloudNetworkSegment(CloudResource, ManagedNetworkSegment):
    auto_assign_public_ip: Boolean
    is_public: BooleanOptional
    segment_type: Dropdown
    availability_zone: RelationshipAttribute[TopologyCloudZone]
    cidr_block: RelationshipAttribute[IpamPrefix]
    customer_deployment: RelationshipAttribute[TopologyCustomer]
    ip_prefixes: RelationshipManager[IpamPrefix]
    tags: RelationshipManager[BuiltinTag]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class VirtNodePool(CoreNode):
    cpu_per_node: IntegerOptional
    desired_capacity: IntegerOptional
    image: StringOptional
    instance_flavor: StringOptional
    max_size: IntegerOptional
    memory_per_node_gb: IntegerOptional
    min_size: IntegerOptional
    name: String
    node_count: IntegerOptional
    os_type: DropdownOptional
    os_version: StringOptional
    pool_type: Dropdown
    scaling_mode: Dropdown
    status: Dropdown
    storage_per_node_gb: IntegerOptional
    cluster: RelationshipAttribute[VirtCluster]
    instances: RelationshipManager[CloudInstance]
    management_ip: RelationshipAttribute[IpamIPAddress]
    network_segments: RelationshipManager[ManagedNetworkSegment]
    physical_hosts: RelationshipManager[DcimPhysicalDevice]
    security_groups: RelationshipManager[CloudSecurityGroup]
    tags: RelationshipManager[BuiltinTag]


class ManagedOSPF(ManagedGeneric, ManagedGenericDevice, ManagedRouting):
    process_id: String
    reference_bandwidth: Integer
    router_type: Dropdown
    version: Dropdown
    peerings: RelationshipManager[ManagedOSPFPeering]
    router_id: RelationshipAttribute[IpamIPAddress]


class RoutingOSPFArea(CoreNode):
    area: Integer
    area_type: Dropdown
    description: StringOptional
    name: String


class RoutingOSPFInterface(ManagedGeneric, ManagedGenericInterfaces):
    authentication_mode: DropdownOptional
    metric: IntegerOptional
    mode: Dropdown
    name: String
    password: RelationshipAttribute[RoutingPassword]


class ManagedOSPFPeering(ManagedGeneric, ManagedPeering, ManagedGenericInterfaces):
    cost: IntegerOptional
    network_type: Dropdown
    namespace: RelationshipAttribute[IpamNamespace]
    ospf_area: RelationshipAttribute[RoutingOSPFArea]
    ospf_interface: RelationshipManager[RoutingOSPFInterface]
    ospf_process: RelationshipManager[ManagedOSPF]


class LocationOffice(LocationGeneric):
    physical_address: StringOptional
    owner: RelationshipAttribute[OrganizationGeneric]


class TopologyOffice(CoreArtifactTarget, TopologyDeployment):
    site_type: Dropdown


class LocationOfficeFloor(LocationGeneric):
    area_sqm: Integer
    conference_rooms: Integer
    employee_count: Integer
    index: Integer


class RoutingPassword(CoreNode):
    description: StringOptional
    name: String
    password: String


class TopologyPhysicalCircuit(TopologyCircuit, ManagedGeneric):
    circuit_id: String
    circuit_type: Dropdown
    committed_rate: IntegerOptional
    contract_end_date: StringOptional
    install_date: StringOptional
    customer_interfaces: RelationshipManager[DcimInterface]
    provider_interfaces: RelationshipManager[DcimInterface]


class DcimPhysicalDevice(CoreArtifactTarget, DcimDevice, DcimCapabilities, AppInstance):
    position: IntegerOptional
    rack_face: Dropdown
    serial: StringOptional


class DcimPhysicalInterface(DcimInterface, DcimEndpoint, DcimSubInterface):
    interface_type: Dropdown
    mtu: Integer
    ip_address: RelationshipAttribute[IpamIPAddress]
    lag: RelationshipAttribute[DcimLAGInterface]


class DcimPlatform(CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    name: String
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    devices: RelationshipManager[DcimDevice]
    manufacturer: RelationshipAttribute[OrganizationManufacturer]


class TopologyPod(TopologyDeployment, TopologyRackHosting, TopologyDeviceHosting):
    deployment_type: Dropdown
    index: Integer
    layout: Dropdown
    leaf_interface_sorting_method: Dropdown
    mlag_create: Dropdown
    name: String
    spine_interface_sorting_method: Dropdown
    status: Dropdown
    asn_pool: RelationshipAttribute[CoreNumberPool]
    design: RelationshipManager[TopologyPodDesign]
    fabric_templates: RelationshipManager[TopologyElement]
    loopback_pool: RelationshipAttribute[CoreIPAddressPool]
    prefix_pool: RelationshipAttribute[CoreIPPrefixPool]
    suites: RelationshipManager[LocationSuite]


class TopologyPodDesign(CoreNode):
    pass


class ProxyPolicy(CoreNode):
    default_action: Dropdown
    description: StringOptional
    enabled: Boolean
    name: String
    policy_type: Dropdown
    priority: Integer
    rules: RelationshipManager[ProxyPolicyRule]


class SecurityPolicy(ManagedGenericDevice):
    default_action: Dropdown
    description: StringOptional
    enabled: Boolean
    name: String
    rules: RelationshipManager[SecurityPolicyRule]


class ProxyPolicyRule(CoreNode):
    action: Dropdown
    description: StringOptional
    destination: StringOptional
    destination_type: Dropdown
    disabled: Boolean
    log: Boolean
    name: String
    priority: Integer
    categories: RelationshipManager[ProxyURLCategory]
    policy: RelationshipAttribute[ProxyPolicy]


class SecurityPolicyRule(CoreNode):
    action: Dropdown
    apply_on_switch: Boolean
    description: StringOptional
    disabled: Boolean
    expires_at: DateTimeOptional
    index: Integer
    log: Boolean
    name: String
    port_end: IntegerOptional
    port_start: IntegerOptional
    protocol: Dropdown
    destination_ip_addresses: RelationshipManager[IpamIPAddress]
    destination_prefixes: RelationshipManager[IpamPrefix]
    destination_segment: RelationshipAttribute[ManagedNetworkSegment]
    destination_zone: RelationshipAttribute[SecurityZone]
    policy: RelationshipAttribute[SecurityPolicy]
    security_profile: RelationshipAttribute[SecuritySecurityProfile]
    source_ip_addresses: RelationshipManager[IpamIPAddress]
    source_prefixes: RelationshipManager[IpamPrefix]
    source_segment: RelationshipAttribute[ManagedNetworkSegment]
    source_zone: RelationshipAttribute[SecurityZone]


class LoadbalancerPoolInterface(ManagedGeneric, ManagedGenericInterfaces):
    port: IntegerOptional
    ip_address: RelationshipAttribute[IpamIPAddress]
    pool_member: RelationshipAttribute[LoadbalancerPoolMember]


class LoadbalancerPoolMember(ManagedGeneric, ManagedGenericDevice):
    drain_timeout: IntegerOptional
    weight: Integer
    pool_interfaces: RelationshipManager[LoadbalancerPoolInterface]
    vip_service: RelationshipAttribute[LoadbalancerVIP]


class IpamPrefix(BuiltinIPPrefix):
    role: DropdownOptional
    status: Dropdown


class OrganizationProvider(OrganizationGeneric, OrganizationEntity):
    pass


class ManagedProxyHA(ManagedHA, ManagedGeneric, ManagedGenericDevice, ManagedInlineService, ManagedProxyService):
    proxy_type: DropdownOptional
    proxy_vendor: DropdownOptional
    capabilities: RelationshipManager[DcimCapabilities]


class CloudPublicIP(CloudResource):
    public_ip: IPHost
    account: RelationshipAttribute[CloudAccount]
    instance: RelationshipAttribute[CloudInstance]
    region: RelationshipAttribute[TopologyCloudRegion]


class CustomerQuotationCampusBuilding(CoreNode):
    access_points: IntegerOptional
    access_switches: IntegerOptional
    demand_mbps: IntegerOptional
    distribution_switches: IntegerOptional
    floors: IntegerOptional
    name: String
    design: RelationshipAttribute[CustomerQuotationCampusDesign]
    floors_breakdown: RelationshipManager[CustomerQuotationCampusFloor]
    source_building: RelationshipAttribute[CustomerQuotationOfficeBuilding]


class CustomerQuotationCampusDesign(CoreNode):
    name: StringOptional
    total_access_points: IntegerOptional
    total_access_switches: IntegerOptional
    total_buildings: IntegerOptional
    total_core_routers: IntegerOptional
    total_demand_mbps: IntegerOptional
    total_distribution_switches: IntegerOptional
    total_floors: IntegerOptional
    buildings: RelationshipManager[CustomerQuotationCampusBuilding]
    quotation: RelationshipAttribute[CustomerQuotationOffice]


class CustomerQuotationCampusFloor(CoreNode):
    access_points: IntegerOptional
    access_switches: IntegerOptional
    demand_mbps: IntegerOptional
    index: Integer
    wired_endpoints: IntegerOptional
    building: RelationshipAttribute[CustomerQuotationCampusBuilding]


class CustomerQuotationDC(CustomerQuotation):
    growth_buffer_percent: Integer
    pod_count: Integer
    preferred_firewall_vendor: StringOptional
    preferred_load_balancer_vendor: StringOptional
    preferred_switch_vendor: StringOptional
    recommended_switch_vendor: StringOptional
    topology_strategy: Dropdown
    proposed_design: RelationshipAttribute[CustomerQuotationProposedDesign]
    rooms: RelationshipManager[CustomerQuotationRoom]


class CustomerQuotationLineItem(CoreNode):
    quantity: Integer
    role: Dropdown
    speed: DropdownOptional
    total_cost: IntegerOptional
    unit_price: IntegerOptional
    device_type: RelationshipAttribute[DcimDeviceType]
    quotation: RelationshipAttribute[CustomerQuotation]


class CustomerQuotationOffice(CustomerQuotation):
    access_switch_port_density: Integer
    access_switch_reserved_ports: Integer
    access_switch_utilization_target: Integer
    access_to_distribution_oversub: Integer
    conference_concurrency: Integer
    conference_room_mbps: Integer
    core_router_port_density: Integer
    core_router_reserved_ports: Integer
    core_router_utilization_target: Integer
    dist_core_uplinks_per_dist: Integer
    dist_switch_reserved_ports: Integer
    dist_switch_util_target: Integer
    distribution_switch_port_density: Integer
    distribution_to_core_oversub: Integer
    endpoint_growth_ratio: Integer
    m2_per_ap: Integer
    min_core_routers: Integer
    min_distribution_switches: Integer
    preferred_switch_vendor: StringOptional
    printer_concurrency: Integer
    printer_mbps: Integer
    size_for_single_link_failure: Boolean
    uplinks_per_access_switch: Integer
    user_concurrency: Integer
    users_per_ap: Integer
    wifi_mbps_per_user: Integer
    buildings: RelationshipManager[CustomerQuotationOfficeBuilding]
    proposed_campus_design: RelationshipAttribute[CustomerQuotationCampusDesign]


class CustomerQuotationOfficeBuilding(CoreNode):
    area_m2_per_floor: Integer
    conference_rooms_per_floor: Integer
    floors: Integer
    name: String
    people_per_floor: Integer
    printers_per_floor: Integer
    quotation: RelationshipAttribute[CustomerQuotationOffice]


class CustomerQuotationProposedDesign(CoreNode):
    name: StringOptional
    pods: RelationshipManager[CustomerQuotationProposedPod]
    quotation: RelationshipAttribute[CustomerQuotationDC]
    recommended_dc_design: RelationshipManager[TopologyDataCenterDesign]


class CustomerQuotationProposedPod(CoreNode):
    compute_rack_share: IntegerOptional
    index: Integer
    leaf_count: IntegerOptional
    recommended_pod_layout: StringOptional
    spine_count: IntegerOptional
    storage_rack_share: IntegerOptional
    design: RelationshipAttribute[CustomerQuotationProposedDesign]
    racks: RelationshipManager[CustomerQuotationProposedRack]
    recommended_pod_design: RelationshipManager[TopologyPodDesign]


class CustomerQuotationProposedRack(CoreNode):
    index: Integer
    rack_type: Dropdown
    pod: RelationshipAttribute[CustomerQuotationProposedPod]
    room: RelationshipAttribute[CustomerQuotationRoom]


class CustomerQuotationRoom(CoreNode):
    compute_rack_count: Integer
    name: String
    port_count_100g: Integer
    port_count_10g: Integer
    port_count_25g: Integer
    port_count_400g: Integer
    port_count_40g: Integer
    preferred_cabling_method: Dropdown
    preferred_leaf_link_offset: Integer
    preferred_spine_uplink_offset: Integer
    rack_assignment_strategy: Dropdown
    racks_per_row: Integer
    rows: Integer
    storage_rack_count: Integer
    quotation: RelationshipAttribute[CustomerQuotationDC]


class LocationRack(LocationGeneric, CoreArtifactTarget):
    facility_id: StringOptional
    height: Integer
    index: Integer
    name: String
    rack_type: Dropdown
    row_index: Integer
    devices: RelationshipManager[DcimPhysicalDevice]
    fabric_templates: RelationshipManager[TopologyElement]
    owner: RelationshipAttribute[OrganizationGeneric]
    pod: RelationshipAttribute[TopologyRackHosting]


class LocationRegion(LocationGeneric):
    pass


class VirtRegistry(ManagedGeneric, ManagedGenericCluster):
    endpoint: StringOptional
    insecure: Boolean
    registry_type: Dropdown


class CloudRoute(CloudResource):
    destination: RelationshipAttribute[IpamPrefix]
    instance: RelationshipAttribute[CloudInstance]
    internet_gateway: RelationshipAttribute[CloudInternetGateway]
    nat_gateway: RelationshipAttribute[CloudNATGateway]
    route_table: RelationshipAttribute[CloudRouteTable]


class TopologyRouteLeakExchange(TopologyExchangeGateway, ManagedGeneric, ManagedGenericInterfaces):
    direction: Dropdown
    route_target: StringOptional


class CloudRouteTable(CloudResource):
    is_main: Boolean
    network_segments: RelationshipManager[CloudNetworkSegment]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class TopologyRoutedExchange(TopologyExchangeGateway, ManagedGeneric, ManagedGenericInterfaces):
    pass


class ManagedSNMP(ManagedGeneric, ManagedGenericDevice):
    community_ro: StringOptional
    community_rw: StringOptional
    contact: StringOptional
    location: StringOptional
    version: Dropdown
    trap_targets: RelationshipManager[ManagedSNMPTrapTarget]


class ManagedSNMPTrapTarget(CoreNode):
    community: StringOptional
    name: String
    port: Integer
    address: RelationshipAttribute[IpamIPAddress]
    snmp_config: RelationshipAttribute[ManagedSNMP]


class TopologySaas(TopologyDeployment, CoreArtifactTarget):
    description: StringOptional
    provider: Dropdown
    service_type: Dropdown
    status: Dropdown


class TopologySaasRegion(TopologyDeployment, TopologyConnectableLocation):
    name: String
    region_name: String
    status: Dropdown
    location: RelationshipAttribute[LocationMetro]
    saas_services: RelationshipManager[ManagedSaasService]


class CloudSecurityGroup(CloudResource):
    account: RelationshipAttribute[CloudAccount]
    rules: RelationshipManager[CloudSecurityGroupRule]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class CloudSecurityGroupRule(CloudResource):
    action: Dropdown
    description: StringOptional
    dest_cidr: StringOptional
    direction: Dropdown
    disabled: Boolean
    log: Boolean
    port_end: IntegerOptional
    port_start: IntegerOptional
    priority: IntegerOptional
    protocol: Dropdown
    source_cidr: StringOptional
    security_group: RelationshipAttribute[CloudSecurityGroup]


class SecuritySecurityProfile(CoreNode):
    antivirus_enabled: Boolean
    data_loss_prevention_enabled: Boolean
    description: StringOptional
    ips_enabled: Boolean
    name: String
    ssl_inspection_enabled: Boolean
    url_filtering_enabled: Boolean


class ManagedSegmentDeployment(CoreNode):
    status: Dropdown
    vlan_id: Integer
    vni: IntegerOptional
    deployment: RelationshipAttribute[TopologySegmentHosting]
    segment: RelationshipAttribute[ManagedNetworkSegment]


class AppServicePort(CoreNode):
    description: StringOptional
    name: StringOptional
    port: Integer
    port_end: IntegerOptional
    protocol: Dropdown


class DcimSoftwareImage(CoreNode):
    description: StringOptional
    end_of_life: DateTimeOptional
    end_of_support: DateTimeOptional
    is_approved: Boolean
    is_recommended: Boolean
    known_cve_count: IntegerOptional
    name: String
    release_date: DateTimeOptional
    release_notes_url: URLOptional
    release_type: Dropdown
    version: String
    devices: RelationshipManager[DcimDevice]
    platform: RelationshipAttribute[DcimPlatform]


class DcimStandardSFP(DcimGenericSFP):
    pass


class VirtStorageBackend(ManagedGeneric, ManagedGenericCluster):
    backend_type: Dropdown
    default_class: Boolean
    reclaim_policy: Dropdown
    version: StringOptional


class ManagedStorageService(ManagedSaasService):
    encryption_at_rest: Boolean
    provider: Dropdown


class LocationSuite(LocationGeneric):
    index: Integer
    name: String
    racks_per_row: Integer
    rows: Integer
    suite_name: String
    owner: RelationshipAttribute[OrganizationGeneric]


class ManagedSyslog(ManagedGeneric, ManagedGenericDevice):
    servers: RelationshipManager[ManagedSyslogServer]


class ManagedSyslogServer(CoreNode):
    name: String
    port: Integer
    severity: Dropdown
    address: RelationshipAttribute[IpamIPAddress]
    syslog_config: RelationshipAttribute[ManagedSyslog]


class SecurityTag(CoreNode):
    color: StringOptional
    description: StringOptional
    group_id: Integer
    name: String


class SecurityTagRule(CoreNode):
    action: Dropdown
    description: StringOptional
    log: Boolean
    destination_tag: RelationshipAttribute[SecurityTag]
    source_tag: RelationshipAttribute[SecurityTag]


class CloudTransitGateway(CloudResource):
    default_route_table: Boolean
    dns_support: Boolean
    vpn_ecmp_support: Boolean
    account: RelationshipAttribute[CloudAccount]
    asn: RelationshipAttribute[RoutingAutonomousSystem]
    attached_virtual_networks: RelationshipManager[CloudVirtualNetwork]
    region: RelationshipAttribute[TopologyCloudRegion]


class ProxyURLCategory(CoreNode):
    category_type: Dropdown
    description: StringOptional
    entries: StringOptional
    name: String


class LoadbalancerVIP(ManagedGenericInterfaces):
    description: StringOptional
    hostname: String
    load_balancing_algorithm: DropdownOptional
    max_connections: IntegerOptional
    port: Integer
    protocol: Dropdown
    session_persistence: DropdownOptional
    ssl_certificate: StringOptional
    ssl_redirect: Boolean
    status: Dropdown
    timeout_client: IntegerOptional
    timeout_server: IntegerOptional
    health_checks: RelationshipManager[LoadbalancerHealthCheck]
    load_balancer: RelationshipAttribute[ManagedLoadBalancer]
    members: RelationshipManager[LoadbalancerPoolMember]
    vip_ip: RelationshipAttribute[IpamIPAddress]


class CloudVPNGateway(CloudResource):
    vpn_type: Dropdown
    asn: RelationshipAttribute[RoutingAutonomousSystem]
    customer_gateway: RelationshipAttribute[CloudCustomerGateway]
    region: RelationshipAttribute[TopologyCloudRegion]
    transit_gateway: RelationshipAttribute[CloudTransitGateway]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class TopologyVirtualCircuit(TopologyCircuit, ManagedGeneric):
    cloud_resource_id: StringOptional
    encryption: Boolean
    link_type: Dropdown
    transport_mode: DropdownOptional
    tunnel_id: IntegerOptional
    vni: IntegerOptional
    interfaces: RelationshipManager[DcimInterface]
    physical_circuits: RelationshipManager[TopologyPhysicalCircuit]


class DcimVirtualDevice(CoreArtifactTarget, DcimDevice, DcimCapabilities, AppInstance):
    cpu: IntegerOptional
    memory: IntegerOptional
    storage: IntegerOptional
    hosting_device: RelationshipAttribute[DcimPhysicalDevice]


class DcimVirtualInterface(DcimInterface):
    ip_address: RelationshipAttribute[IpamIPAddress]
    parent_interface: RelationshipAttribute[DcimPhysicalInterface]


class CloudVirtualInterface(CloudResource):
    vif_type: Dropdown
    vlan_id: Integer
    asn: RelationshipAttribute[RoutingAutonomousSystem]
    direct_connect: RelationshipAttribute[CloudDirectConnect]
    transit_gateway: RelationshipAttribute[CloudTransitGateway]
    virtual_network: RelationshipAttribute[CloudVirtualNetwork]


class CloudVirtualNetwork(CloudResource):
    dns_hostnames: Boolean
    dns_support: Boolean
    is_default: Boolean
    is_shared: BooleanOptional
    account: RelationshipAttribute[CloudAccount]
    cidr_blocks: RelationshipManager[IpamPrefix]
    network_segments: RelationshipManager[CloudNetworkSegment]
    region: RelationshipAttribute[TopologyCloudRegion]


class ManagedVlanSegment(ManagedGeneric, ManagedNetworkSegment, ManagedGenericInterfaces):
    segment_type: Dropdown
    vlan_id: IntegerOptional
    customer_deployment: RelationshipAttribute[TopologyCustomer]


class ManagedVxlanSegment(ManagedGeneric, ManagedNetworkSegment, ManagedGenericInterfaces):
    arp_suppression: Boolean
    segment_type: Dropdown
    terminate_inline: Boolean
    customer_deployments: RelationshipManager[TopologyCustomer]


class SecurityZone(CoreNode):
    description: StringOptional
    name: String
    trust_level: Integer
    zone_type: Dropdown
    network_segments: RelationshipManager[ManagedNetworkSegment]
    rules_as_dest: RelationshipManager[SecurityPolicyRule]
    rules_as_source: RelationshipManager[SecurityPolicyRule]
