#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import BuiltinIPAddress, BuiltinIPPrefix, CoreArtifactTarget, CoreNode

if TYPE_CHECKING:
    from infrahub_sdk.node import RelationshipAttribute, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Boolean,
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPHostOptional,
        IPNetwork,
        String,
        StringOptional,
    )


class AppGeneric(CoreNode):
    description: StringOptional
    children: RelationshipManager[AppGeneric]
    member_of_groups: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[AppGeneric]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class DcimCapabilities(CoreNode):
    name: StringOptional
    capabilities: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class DcimDevice(CoreNode):
    description: StringOptional
    name: String
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    device_type: RelationshipAttribute[CoreNode]
    interfaces: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    platform: RelationshipAttribute[CoreNode]
    primary_address: RelationshipAttribute[IpamIPAddress]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class DcimEndpoint(CoreNode):
    cable: RelationshipAttribute[DcimCable]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class DcimInterface(CoreNode):
    description: StringOptional
    index: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelationshipAttribute[DcimDevice]
    interface_capabilities: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class DcimSubInterface(CoreNode):
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    sub_interfaces: RelationshipManager[DcimVirtualInterface]
    subscriber_of_groups: RelationshipManager[CoreNode]


class DcimCable(CoreNode):
    name: String
    type: Dropdown
    deployment: RelationshipAttribute[CoreNode]
    endpoints: RelationshipManager[DcimEndpoint]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class DcimPhysicalDevice(CoreArtifactTarget, DcimDevice, DcimCapabilities):
    description: StringOptional
    name: StringOptional
    os_version: StringOptional
    position: IntegerOptional
    rack_face: Dropdown
    role: DropdownOptional
    serial: StringOptional
    status: Dropdown
    artifacts: RelationshipManager[CoreNode]
    capabilities: RelationshipManager[CoreNode]
    deployment: RelationshipAttribute[CoreNode]
    device_type: RelationshipAttribute[CoreNode]
    interfaces: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    object_template: RelationshipAttribute[CoreNode]
    platform: RelationshipAttribute[CoreNode]
    primary_address: RelationshipAttribute[IpamIPAddress]
    profiles: RelationshipManager[CoreNode]
    rack: RelationshipAttribute[LocationRack]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class DcimPhysicalInterface(DcimInterface, DcimEndpoint, DcimSubInterface):
    description: StringOptional
    index: StringOptional
    interface_type: Dropdown
    mtu: Integer
    name: String
    role: DropdownOptional
    status: Dropdown
    cable: RelationshipAttribute[DcimCable]
    device: RelationshipAttribute[DcimDevice]
    interface_capabilities: RelationshipManager[CoreNode]
    ip_address: RelationshipAttribute[IpamIPAddress]
    lag: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    plugged_sfp: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    sub_interfaces: RelationshipManager[DcimVirtualInterface]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class DcimVirtualDevice(CoreArtifactTarget, DcimDevice, DcimCapabilities):
    cpu: IntegerOptional
    description: StringOptional
    memory: IntegerOptional
    name: StringOptional
    os_version: StringOptional
    role: DropdownOptional
    status: Dropdown
    storage: IntegerOptional
    artifacts: RelationshipManager[CoreNode]
    capabilities: RelationshipManager[CoreNode]
    deployment: RelationshipAttribute[CoreNode]
    device_type: RelationshipAttribute[CoreNode]
    hosting_device: RelationshipAttribute[DcimPhysicalDevice]
    interfaces: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    object_template: RelationshipAttribute[CoreNode]
    platform: RelationshipAttribute[CoreNode]
    primary_address: RelationshipAttribute[IpamIPAddress]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class DcimVirtualInterface(DcimInterface):
    description: StringOptional
    index: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelationshipAttribute[DcimDevice]
    interface_capabilities: RelationshipManager[CoreNode]
    ip_address: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreNode]
    parent_interface: RelationshipAttribute[DcimPhysicalInterface]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class GeneratorTarget(CoreNode):
    checksum: StringOptional
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    ip_namespace: RelationshipAttribute[CoreNode]
    ip_prefix: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class IpamPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: DropdownOptional
    status: Dropdown
    utilization: IntegerOptional
    children: RelationshipManager[CoreNode]
    ip_addresses: RelationshipManager[CoreNode]
    ip_namespace: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    resource_pool: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class LoadbalancerHealthCheck(CoreNode):
    check: Dropdown
    description: String
    fall: Integer
    rise: Integer
    timeout: Integer
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    vip_services: RelationshipManager[LoadbalancerVIP]


class LocationGeneric(CoreNode):
    name: String
    shortname: String
    children: RelationshipManager[LocationGeneric]
    member_of_groups: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[LocationGeneric]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class LocationRack(LocationGeneric, GeneratorTarget, CoreArtifactTarget):
    checksum: StringOptional
    facility_id: StringOptional
    height: Integer
    index: Integer
    name: String
    rack_type: Dropdown
    row_index: Integer
    shortname: String
    artifacts: RelationshipManager[CoreNode]
    children: RelationshipManager[LocationGeneric]
    devices: RelationshipManager[DcimPhysicalDevice]
    fabric_templates: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    parent: RelationshipAttribute[CoreNode]
    pod: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]


class ManagedGeneric(CoreNode):
    description: StringOptional
    name: String
    status: Dropdown
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedGenericDevice(CoreNode):
    capabilities: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedGenericInterfaces(CoreNode):
    interface_capabilities: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedNetworkSegment(CoreNode):
    customer_name: String
    description: StringOptional
    environment: Dropdown
    isolation_mode: Dropdown
    name: String
    pbr_enabled: Boolean
    segment_role: Dropdown
    segment_type: DropdownOptional
    status: Dropdown
    terminate_inline: Boolean
    gateway: RelationshipAttribute[IpamIPAddress]
    inline_service: RelationshipAttribute[ManagedGeneric]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    security_policies: RelationshipManager[CoreNode]
    security_tag: RelationshipAttribute[CoreNode]
    security_zone: RelationshipAttribute[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    virt_clusters: RelationshipManager[CoreNode]


class ManagedPeering(CoreNode):
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedRouting(CoreNode):
    name: String
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedBGP(ManagedGeneric, ManagedGenericDevice, ManagedRouting):
    confederation_identifier: IntegerOptional
    description: StringOptional
    graceful_restart: Boolean
    multipath: Boolean
    name: String
    status: Dropdown
    capabilities: RelationshipManager[CoreNode]
    local_as: RelationshipAttribute[RoutingAutonomousSystem]
    member_of_groups: RelationshipManager[CoreNode]
    peerings: RelationshipManager[ManagedBGPPeering]
    profiles: RelationshipManager[CoreNode]
    router_id: RelationshipAttribute[IpamIPAddress]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedBGPPeering(ManagedGeneric, ManagedPeering, ManagedGenericInterfaces):
    bfd_enabled: Boolean
    description: StringOptional
    local_pref: IntegerOptional
    maximum_routes: IntegerOptional
    med: IntegerOptional
    name: String
    remove_private_as: Boolean
    route_reflector_client: Boolean
    send_community: Boolean
    send_extended_community: Boolean
    session_type: Dropdown
    status: Dropdown
    ttl: Integer
    address_families: RelationshipManager[CoreNode]
    bgp_processes: RelationshipManager[ManagedBGP]
    interface_capabilities: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    password: RelationshipAttribute[RoutingPassword]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedOSPF(ManagedGeneric, ManagedGenericDevice, ManagedRouting):
    description: StringOptional
    name: String
    process_id: String
    reference_bandwidth: Integer
    router_type: Dropdown
    status: Dropdown
    version: Dropdown
    capabilities: RelationshipManager[CoreNode]
    interface_configs: RelationshipManager[RoutingOSPFInterface]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    router_id: RelationshipAttribute[IpamIPAddress]
    subscriber_of_groups: RelationshipManager[CoreNode]


class ManagedVlanSegment(ManagedGeneric, ManagedNetworkSegment, ManagedGenericInterfaces):
    customer_name: String
    description: StringOptional
    environment: Dropdown
    isolation_mode: Dropdown
    name: String
    pbr_enabled: Boolean
    segment_role: Dropdown
    segment_type: Dropdown
    status: Dropdown
    terminate_inline: Boolean
    deployment: RelationshipAttribute[CoreNode]
    gateway: RelationshipAttribute[IpamIPAddress]
    inline_service: RelationshipAttribute[ManagedGeneric]
    interface_capabilities: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    security_policies: RelationshipManager[CoreNode]
    security_tag: RelationshipAttribute[CoreNode]
    security_zone: RelationshipAttribute[CoreNode]
    segment_deployments: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    virt_clusters: RelationshipManager[CoreNode]


class ManagedVxlanSegment(ManagedGeneric, ManagedNetworkSegment, ManagedGenericInterfaces):
    arp_suppression: Boolean
    customer_name: String
    description: StringOptional
    environment: Dropdown
    isolation_mode: Dropdown
    name: String
    pbr_enabled: Boolean
    segment_role: Dropdown
    segment_type: Dropdown
    status: Dropdown
    terminate_inline: Boolean
    deployments: RelationshipManager[CoreNode]
    gateway: RelationshipAttribute[IpamIPAddress]
    inline_service: RelationshipAttribute[ManagedGeneric]
    interface_capabilities: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    security_policies: RelationshipManager[CoreNode]
    security_tag: RelationshipAttribute[CoreNode]
    security_zone: RelationshipAttribute[CoreNode]
    segment_deployments: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    virt_clusters: RelationshipManager[CoreNode]


class ManagedProxyService(ManagedGeneric):
    name: String
    status: DropdownOptional
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class RoutingAutonomousSystem(CoreNode):
    asn: Integer
    description: StringOptional
    name: String
    location: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class RoutingOSPFArea(CoreNode):
    area: Integer
    area_type: Dropdown
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class RoutingOSPFInterface(ManagedGeneric, ManagedGenericInterfaces):
    authentication_mode: DropdownOptional
    description: StringOptional
    metric: IntegerOptional
    mode: Dropdown
    name: String
    status: Dropdown
    area: RelationshipAttribute[RoutingOSPFArea]
    interface_capabilities: RelationshipManager[DcimInterface]
    member_of_groups: RelationshipManager[CoreNode]
    ospf_process: RelationshipAttribute[ManagedOSPF]
    ospf_services: RelationshipManager[ManagedOSPF]
    password: RelationshipAttribute[RoutingPassword]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class RoutingPassword(CoreNode):
    description: StringOptional
    name: String
    password: StringOptional
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class LoadbalancerPoolInterface(ManagedGeneric, ManagedGenericInterfaces):
    description: StringOptional
    name: String
    port: IntegerOptional
    status: Dropdown
    interface_capabilities: RelationshipManager[DcimInterface]
    ip_address: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreNode]
    pool_member: RelationshipAttribute[LoadbalancerPoolMember]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class LoadbalancerPoolMember(ManagedGeneric, ManagedGenericDevice):
    description: StringOptional
    drain_timeout: IntegerOptional
    name: String
    status: Dropdown
    weight: Integer
    capabilities: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    pool_interfaces: RelationshipManager[LoadbalancerPoolInterface]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    vip_service: RelationshipAttribute[LoadbalancerVIP]


class LoadbalancerVIP(ManagedGenericInterfaces):
    description: StringOptional
    hostname: String
    load_balancing_algorithm: DropdownOptional
    max_connections: IntegerOptional
    port: Integer
    protocol: Dropdown
    session_persistence: DropdownOptional
    ssl_certificate: StringOptional
    ssl_redirect: Boolean
    status: Dropdown
    timeout_client: IntegerOptional
    timeout_server: IntegerOptional
    components: RelationshipManager[CoreNode]
    health_checks: RelationshipManager[LoadbalancerHealthCheck]
    interface_capabilities: RelationshipManager[DcimInterface]
    load_balancer: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    members: RelationshipManager[LoadbalancerPoolMember]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    vip_ip: RelationshipAttribute[IpamIPAddress]


class CloudResource(CoreNode):
    cloud_id: StringOptional
    description: StringOptional
    name: String
    status: DropdownOptional
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    virtual_circuits: RelationshipManager[CoreNode]


class CloudInstance(CloudResource, DcimCapabilities):
    cloud_id: StringOptional
    cpu_count: IntegerOptional
    description: StringOptional
    image: StringOptional
    instance_type: StringOptional
    memory_gb: IntegerOptional
    name: String
    os_type: DropdownOptional
    private_ip: IPHostOptional
    public_ip: IPHostOptional
    root_volume_size_gb: IntegerOptional
    status: DropdownOptional
    account: RelationshipAttribute[CoreNode]
    availability_zone: RelationshipAttribute[TopologyCloudZone]
    capabilities: RelationshipManager[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    network_segment: RelationshipAttribute[CloudNetworkSegment]
    node_pool: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    security_groups: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    virtual_circuits: RelationshipManager[CoreNode]


class CloudNetworkSegment(CloudResource, ManagedNetworkSegment):
    auto_assign_public_ip: Boolean
    cloud_id: StringOptional
    customer_name: String
    description: StringOptional
    environment: Dropdown
    is_public: BooleanOptional
    isolation_mode: Dropdown
    name: String
    pbr_enabled: Boolean
    segment_role: Dropdown
    segment_type: Dropdown
    status: Dropdown
    terminate_inline: Boolean
    availability_zone: RelationshipAttribute[TopologyCloudZone]
    cidr_block: RelationshipAttribute[IpamPrefix]
    gateway: RelationshipAttribute[IpamIPAddress]
    inline_service: RelationshipAttribute[ManagedGeneric]
    ip_prefixes: RelationshipManager[IpamPrefix]
    member_of_groups: RelationshipManager[CoreNode]
    owner: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    security_policies: RelationshipManager[CoreNode]
    security_tag: RelationshipAttribute[CoreNode]
    security_zone: RelationshipAttribute[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
    tags: RelationshipManager[CoreNode]
    virt_clusters: RelationshipManager[CoreNode]
    virtual_circuits: RelationshipManager[CoreNode]
    virtual_network: RelationshipAttribute[CoreNode]


class TopologyDeployment(CoreNode):
    name: String
    children: RelationshipManager[TopologyDeployment]
    member_of_groups: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[TopologyDeployment]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class TopologyRackHosting(CoreNode):
    name: String
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    racks: RelationshipManager[LocationRack]
    subscriber_of_groups: RelationshipManager[CoreNode]


class TopologyDeviceHosting(CoreNode):
    name: String
    devices: RelationshipManager[DcimDevice]
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class TopologyDataCenter(TopologyDeployment, GeneratorTarget, TopologyRackHosting, TopologyDeviceHosting):
    name: String
    status: Dropdown
    member_of_groups: RelationshipManager[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class TopologyCloudZone(TopologyDeployment):
    name: String
    children: RelationshipManager[TopologyDeployment]
    instances: RelationshipManager[CloudInstance]
    member_of_groups: RelationshipManager[CoreNode]
    network_segments: RelationshipManager[CloudNetworkSegment]
    parent: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]


class TopologyPod(TopologyDeployment, GeneratorTarget, TopologyRackHosting, TopologyDeviceHosting):
    amount_of_spines: Integer
    checksum: StringOptional
    deployment_type: Dropdown
    index: Integer
    leaf_interface_sorting_method: Dropdown
    name: String
    spine_interface_sorting_method: Dropdown
    status: Dropdown
    asn_pool: RelationshipAttribute[CoreNode]
    children: RelationshipManager[TopologyDeployment]
    design: RelationshipAttribute[CoreNode]
    devices: RelationshipManager[DcimDevice]
    loopback_pool: RelationshipAttribute[CoreNode]
    member_of_groups: RelationshipManager[CoreNode]
    parent: RelationshipAttribute[CoreNode]
    prefix_pool: RelationshipAttribute[CoreNode]
    profiles: RelationshipManager[CoreNode]
    racks: RelationshipManager[LocationRack]
    spine_template: RelationshipAttribute[CoreNode]
    subscriber_of_groups: RelationshipManager[CoreNode]
