fragment OspfInterfaceCapabilityFields on RoutingOSPFInterface {
  name { value }
  mode { value }
  metric { value }
  authentication_mode { value }
  password { node { password { value } } }
  peering {
    node {
      ospf_process {
        edges {
          node {
            process_id { value }
            router_id { node { address { value } } }
            capabilities { edges { node { name { value } } } }
          }
        }
      }
      ospf_area { node { area { value } area_type { value } } }
      network_type { value }
      cost { value }
      interface_capabilities {
        edges {
          node {
            name { value }
            device { node { name { value } } }
          }
        }
      }
    }
  }
}

fragment ExchangeGatewayInterfaceCapabilityFields on TopologyExchangeGateway {
  ... on TopologyRoutedExchange {
    id
    namespace_a { node { name { value } l3_vni { value } namespace_type { value } } }
    namespace_z { node { name { value } l3_vni { value } namespace_type { value } } }
    name { value }
    description { value }
    status { value }
    # The firewall context the two VRFs are exchanged through. Its legs are
    # NOT listed here (that grows O(exchanges x interfaces)): a consumer
    # groups the legs of the context by the exchange id carried on each leg.
    gateway { node { id tenant { node { id } } } }
  }
  ... on TopologyRouteLeakExchange {
    direction { value }
    route_target { value }
  }
}

fragment InterfaceCapabilitiesFields on DcimInterface {
  interface_capabilities {
    edges {
      node {
        __typename
        ...OspfInterfaceCapabilityFields
      }
    }
  }
}

fragment FirewallContextInterfaceCapabilityFields on ManagedFirewallContext {
  id
  name { value }
  vlan_id { value }
  tenant { node { id } }
  served_deployments { edges { node { id } } }
  # The context's legs: each member's VLAN sub-interface, in the leg's VRF
  # namespace, tagged with the context and with the exchange(s) of that leg.
  interface_capabilities {
    edges {
      node {
        name { value }
        device { node { name { value } role { value } } }
        ... on DcimVirtualInterface {
          ip_address {
            node {
              address { value }
              ip_namespace { node { name { value } l3_vni { value } namespace_type { value } } }
            }
          }
          interface_capabilities {
            edges {
              node {
                ... on TopologyRoutedExchange {
                  id
                  namespace_a { node { name { value } namespace_type { value } } }
                  namespace_z { node { name { value } namespace_type { value } } }
                  gateway { node { id tenant { node { id } } } }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment InterfaceCapabilitiesWithSegmentFields on DcimInterface {
  interface_capabilities {
    edges {
      node {
        __typename
        ...OspfInterfaceCapabilityFields
        ...NetworkSegmentFields
        ...ExchangeGatewayInterfaceCapabilityFields
        ...FirewallContextInterfaceCapabilityFields
      }
    }
  }
}

fragment InterfaceCapabilitiesOnInterfaceFields on DcimInterface {
  ...InterfaceCapabilitiesFields
}

fragment InterfaceCapabilitiesWithSegmentOnInterfaceFields on DcimInterface {
  ...InterfaceCapabilitiesWithSegmentFields
}
