fragment SegmentBaseFields on ManagedNetworkSegment {
  name { value }
  description { value }
  status { value }
}

fragment SegmentStatusFields on ManagedNetworkSegment {
  name { value }
  status { value }
}

fragment SegmentDeploymentsFields on ManagedNetworkSegment {
  ... on ManagedVlanSegment {
    vlan_id { value }
  }
  ... on ManagedVxlanSegment {
    segment_deployments {
      edges {
        node {
          vlan_id { value }
          vni { value }
        }
      }
    }
  }
}

fragment SegmentDeploymentsActiveFields on ManagedNetworkSegment {
  ... on ManagedVlanSegment {
    status { value }
    vlan_id { value }
  }
  ... on ManagedVxlanSegment {
    segment_deployments(status__values: $segment_status_values) {
      edges {
        node {
          vlan_id { value }
          vni { value }
        }
      }
    }
  }
}

fragment SegmentGatewayWithNamespaceFields on ManagedNetworkSegment {
  gateway {
    node {
      address { value }
      ip_prefix {
        node {
          prefix { value }
          ip_namespace {
            node {
              name { value }
              l3_vni { value }
            }
          }
        }
      }
    }
  }
}

fragment SegmentSecurityZoneFields on ManagedNetworkSegment {
  security_zone {
    node {
      name { value }
      trust_level { value }
      zone_type { value }
    }
  }
}

fragment SegmentSecurityPolicyFields on ManagedNetworkSegment {
  ... on ManagedVxlanSegment {
    inline_service {
      node { id name { value } }
    }
  }
  isolation_mode { value }
  security_tag {
    node {
      name { value }
      group_id { value }
      rules_as_source {
        edges {
          node {
            action { value }
            log { value }
            destination_tag {
              node {
                name { value }
                group_id { value }
              }
            }
          }
        }
      }
    }
  }
}

fragment NetworkSegmentFields on ManagedNetworkSegment {
  ... on ManagedVlanSegment {
    id
    name { value }
    description { value }
    status { value }
    vlan_id { value }
    gateway {
      node {
        address { value }
        ip_prefix {
          node {
            prefix { value }
            ip_namespace {
              node {
                name { value }
                l3_vni { value }
              }
            }
          }
        }
      }
    }
    ...SegmentSecurityZoneFields
    ...SegmentSecurityPolicyFields
  }
  ... on ManagedVxlanSegment {
    id
    name { value }
    description { value }
    status { value }
    customer_name { value }
    arp_suppression { value }
    segment_deployments(status__values: ["active", "provisioning"]) {
      edges {
        node {
          vlan_id { value }
          vni { value }
        }
      }
    }
    gateway {
      node {
        address { value }
        ip_prefix {
          node {
            prefix { value }
            ip_namespace {
              node {
                name { value }
                l3_vni { value }
              }
            }
          }
        }
      }
    }
    ...SegmentSecurityZoneFields
    ...SegmentSecurityPolicyFields
  }
}
