# generated by datamodel-codegen:
#   filename:  rack.json
#   timestamp: 2025-11-11T11:37:47+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Platform(BaseModel):
    id: str
    name: str


class Interface(BaseModel):
    name: str
    role: str


class Template(BaseModel):
    id: str
    platform: Optional[Platform]
    interfaces: List[Interface]


class FabricTemplate(BaseModel):
    name: str
    role: str
    quantity: int
    template: Template


class DesignPattern(BaseModel):
    naming_convention: str


class Parent(BaseModel):
    id: str
    name: str
    index: int
    design_pattern: DesignPattern


class LoopbackPool(BaseModel):
    id: str


class PrefixPool(BaseModel):
    id: str


class SpineTemplate(BaseModel):
    id: str
    interfaces: List[Interface]


class Pod(BaseModel):
    id: str
    name: str
    index: int
    parent: Parent
    amount_of_spines: int
    leaf_interface_sorting_method: str
    spine_interface_sorting_method: str
    loopback_pool: LoopbackPool
    prefix_pool: PrefixPool
    spine_template: SpineTemplate


class LocationRack(BaseModel):
    id: str
    name: str
    index: int
    rack_type: str
    fabric_templates: List[FabricTemplate]
    pod: Pod


class RackGenerator(BaseModel):
    LocationRack: List[LocationRack]
