query validate_firewall($device: String!) {
  DcimGenericDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        ... on DcimFirewall {
          policy {
            node {
              ... on SecurityPolicy {
                rules {
                  edges {
                    node {
                      name {
                        value
                      }
                      index {
                        value
                      }
                      action {
                        value
                      }
                      log {
                        value
                      }
                      source_zone {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      destination_zone {
                        node {
                          name {
                            value
                          }
                        }
                      }
                      source_address {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                      source_groups {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                      destination_address {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                      destination_groups {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                      destination_services {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                      destination_service_groups {
                        edges {
                          node {
                            name {
                              value
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              ... on DcimInterfaceL3 {
                role{
                  value
                }
                security_zone {
                  node {
                    name {
                      value
                    }
                  }
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}