# add_app_component: a component moved to another segment. Its own
# application is reconciled from the application query (application.gql);
# this payload only has to find that application and the other applications
# whose components call this component's endpoints, since their rules name
# its segment too.
query app_component($slug: String!) {
  AppComponent(slug__value: $slug) {
    edges {
      node {
        id
        slug { value }
        parent {
          node {
            id
            ... on AppApplication {
              name { value }
            }
          }
        }
        children {
          edges {
            node {
              id
              ... on AppEndpoint {
                name { value }
                dependents {
                  edges {
                    node {
                      id
                      source {
                        node {
                          id
                          ... on AppComponent {
                            parent {
                              node {
                                id
                                ... on AppApplication {
                                  name { value }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
