query app_dependency_service_port($name: String!) {
  AppDependency(name__value: $name) {
    edges {
      node {
        id
        name { value }
        protocol { value }
        port_start { value }
        port_end { value }
        target {
          node {
            id
            ... on AppComponent {
              slug { value }
            }
          }
        }
      }
    }
  }
}
