fragment SegmentSecurityFields on ManagedNetworkSegment {
  name { value }
  isolation_mode { value }
  security_zone { node { name { value } trust_level { value } } }
  security_tag { node { id name { value } } }
  gateway { node { ip_prefix { node { prefix { value } } } } }
}

fragment AppComponentSecurityFields on AppComponent {
  id
  name { value }
  fqdn { value }
  ports { value }
  load_balanced { value }
  component_type { value }
  instances {
    edges {
      node {
        id
        name { value }
        __typename
        ... on DcimPhysicalDevice {
          role { value }
        }
        ... on DcimVirtualDevice {
          role { value }
          hosting_device {
            node {
              id
              name { value }
            }
          }
        }
      }
    }
  }
  dependents {
    edges {
      node {
        id
        name { value }
        ports { value }
        access_status { value }
        source_profile {
          node {
            id
            name { value }
          }
        }
      }
    }
  }
  depends_on {
    edges {
      node {
        id
        name { value }
        ports { value }
        target_fqdn { value }
        description { value }
        access_status { value }
        decision_reason { value }
        access_expires_at { value }
        target {
          node {
            id
            ... on AppComponent {
              name { value }
              fqdn { value }
              ports { value }
              component_type { value }
              network_segment {
                node {
                  id
                  name { value }
                  ...SegmentSecurityFields
                }
              }
              parent {
                node {
                  ... on AppApplication {
                    id
                    name { value }
                    environment { value }
                    owner {
                      node {
                        id
                        org_id { value }
                        name { value }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  parent {
    node {
      id
      ... on AppApplication {
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            name { value }
            egress_service {
              node {
                id
                name { value }
              }
            }
            private_access_service {
              node {
                id
                name { value }
              }
            }
          }
        }
      }
    }
  }
  network_segment {
    node {
      id
      __typename
      ...SegmentSecurityFields
      ... on CloudNetworkSegment {
        name { value }
        segment_type { value }
        cidr_block { value }
        virtual_network {
          node {
            id
            name { value }
            account {
              node {
                id
                name { value }
              }
            }
          }
        }
      }
    }
  }
  health_checks {
    edges {
      node {
        id
      }
    }
  }
}

fragment AppApplicationSecurityFields on AppApplication {
  id
  name { value }
  environment { value }
  criticality { value }
  security_profile { value }
  children {
    edges {
      node {
        ...AppComponentSecurityFields
      }
    }
  }
}

query application($name: String!) {
  AppApplication(name__value: $name) {
    edges {
      node {
        ...AppApplicationSecurityFields
      }
    }
  }
}
