query customer_dc_data($name: String!) {
  TopologyCustomerDC(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            name { value }
          }
        }
      }
    }
  }

  TopologyCustomerColocation(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            name { value }
          }
        }
      }
    }
  }

  TopologyCustomerCloud(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            name { value }
          }
        }
        parent {
          node {
            id
            ... on TopologyCloudRegion {
              namespace {
                node {
                  id
                  name { value }
                }
              }
              circuits {
                edges {
                  node {
                    id
                    __typename
                    ... on TopologyVirtualCircuit {
                      name { value }
                      customer_deployment { node { id } }
                      interfaces {
                        edges {
                          node {
                            id
                            name { value }
                            device { node { name { value } } }
                          }
                        }
                      }
                      locations {
                        edges {
                          node {
                            id
                            __typename
                            ... on TopologyCloudRegion {
                              namespace {
                                node {
                                  id
                                  name { value }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  TopologyCustomerOffice(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            name { value }
          }
        }
        parent {
          node {
            id
            ... on TopologyOffice {
              circuits {
                edges {
                  node {
                    id
                    __typename
                    ... on TopologyVirtualCircuit {
                      name { value }
                      customer_deployment { node { id } }
                      interfaces {
                        edges {
                          node {
                            id
                            name { value }
                            device { node { name { value } } }
                          }
                        }
                      }
                      locations {
                        edges {
                          node {
                            id
                            __typename
                            ... on TopologyCloudRegion {
                              namespace {
                                node {
                                  id
                                  name { value }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
