query customer_colocation($name: String!) {
  TopologyCustomerColocation(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        owner {
          node {
            id
            org_id { value }
            ... on OrganizationCustomer {
              name { value }
            }
            ... on OrganizationProvider {
              name { value }
            }
          }
        }
        parent { node { id name { value } } }
      }
    }
  }
}
