query customer_boarding_data($name: String!) {
  OrganizationCustomer(name__value: $name) {
    edges {
      node {
        id
        name { value }
        org_id { value }
        profile {
          node {
            id
            name { value }
            allowed_environments { value }
            global_subnet_size { value }
          }
        }
      }
    }
  }
}
