query customer_office($name: String!) {
  TopologyCustomerOffice(name__value: $name) {
    edges {
      node {
        id
        name { value }
        environment { value }
        parent {
          node {
            ... on TopologyOfficeCustomer {
              owner {
                node {
                  id
                  org_id { value }
                  ... on OrganizationCustomer {
                    name { value }
                  }
                  ... on OrganizationProvider {
                    name { value }
                  }
                }
              }
            }
          }
        }
        circuits {
          edges {
            node {
              id
              __typename
              ... on TopologyVirtualCircuit {
                name { value }
                interface_capabilities {
                  edges {
                    node {
                      id
                      name { value }
                      device { node { name { value } } }
                    }
                  }
                }
                locations {
                  edges {
                    node {
                      id
                      __typename
                      ... on TopologyCustomerColocation {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                      ... on TopologyCustomerCloud {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                      ... on TopologyCustomerOffice {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                    }
                  }
                }
              }
              ... on TopologyPhysicalCircuit {
                name { value }
                customer_interfaces {
                  edges {
                    node {
                      id
                      name { value }
                      device { node { name { value } } }
                    }
                  }
                }
                locations {
                  edges {
                    node {
                      id
                      __typename
                      ... on TopologyCustomerColocation {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                      ... on TopologyCustomerCloud {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                      ... on TopologyCustomerOffice {
                        namespace {
                          node {
                            id
                            name { value }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
