query topology_dc($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        ... on TopologyDataCenter {
          index {
            value
          }
          design {
            node {
              strategy { value }
              underlay { value }
              max_super_spine_count { value }
              max_pod_count { value }
              naming_convention { value }
              dc_loopback_parent_size { value }
              dc_technical_parent_size { value }
              loopback_prefix_size { value }
              p2p_prefix_size { value }
            }
          }
          children {
            edges {
              node {
                id
                ... on TopologyPod {
                  checksum {
                    value
                  }
                }
              }
            }
          }
          amount_of_super_spines {
            value
          }
          super_spine_template {
            node {
              id
              template_name {
                value
              }
              platform {
                node {
                  id
                }
              }
              device_type {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
