query FabricGeneratorQuery($name: String!) {
  TopologyDeployment(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        ... on TopologyDataCenter {
          index {
            value
          }
          underlay{
            value
          }
          children {
            edges {
              node {
                id
                ... on TopologyPod {
                  checksum {
                    value
                  }
                }
              }
            }
          }
          design_pattern {
            node {
              maximum_super_spines {
                value
              }
              maximum_pods{
                value
              }
              maximum_spines {
                value
              }
              maximum_switches {
                value
              }
              naming_convention {
                value
              }
            }
          }
          amount_of_super_spines {
            value
          }
          super_spine_template {
            node {
              id
              template_name {
                value
              }
              platform {
                node {
                  id
                }
              }
              device_type {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
