query dci_peering_service_data($name: String!) {
  ManagedDCIPeeringService(name__value: $name) {
    edges {
      node {
        id
        name { value }
        ip_family { value }
        a_side_dc {
          node { id name { value } }
        }
        z_side_dc {
          node { id name { value } }
        }
        primary_circuits {
          edges {
            node {
              id
              name { value }
              link_type { value }
              ...CircuitEndpoints
            }
          }
        }
        secondary_circuits {
          edges {
            node {
              id
              name { value }
              link_type { value }
              ...CircuitEndpoints
            }
          }
        }
        vxlan_segments {
          edges {
            node {
              id
              name { value }
              deployments {
                edges { node { id name { value } } }
              }
            }
          }
        }
      }
    }
  }
}

fragment CircuitEndpoints on TopologyVirtualCircuit {
  interfaces {
    edges {
      node {
        id
        name { value }
        ... on DcimPhysicalInterface {
          ip_address { node { id address { value } } }
        }
        ... on DcimVirtualInterface {
          ip_address { node { id address { value } } }
        }
        device {
          node { id name { value } role { value } }
        }
      }
    }
  }
}
