fragment PhysicalInterfaceFields on DcimPhysicalInterface {
  id
  name { value }
  interface_type { value }
  role { value }
  status { value }
  cable {
    node {
      id
    }
  }
}

fragment PodFields on TopologyPod {
  id
  name { value }
  deployment_type { value }
  index { value }
  parent {
    node {
      id
      name { value }
    }
  }
}

fragment RackFields on LocationRack {
  id
  name { value }
  index { value }
  row_index { value }
  rack_type { value }
  pod {
    node {
      ...PodFields
    }
  }
}

query GetEndpointForConnectivity($device_name: String!) {
  DcimDevice(name__value: $device_name) {
    edges {
      node {
        id
        name { value }
        role { value }
        ... on DcimPhysicalDevice {
          rack {
            node {
              ...RackFields
            }
          }
        }
        interfaces {
          edges {
            node {
              ...PhysicalInterfaceFields
            }
          }
        }
      }
    }
  }
}
