query interface_descriptions_data($deployment: String!) {
  TopologyPhysicalDeployment(name__value: $deployment) {
    edges {
      node {
        id
        name { value }
        cables {
          edges {
            node {
              id
              endpoints {
                edges {
                  node {
                    id
                    name { value }
                    device {
                      node {
                        ... on DcimPhysicalDevice {
                          name { value }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
