fragment DeviceTemplateFields on TemplateDcimPhysicalDevice {
  id
  platform {
    node {
      id
      name { value }
    }
  }
  device_type {
    node {
      id
    }
  }
  interfaces(role__value: "uplink") {
    edges {
      node {
        name { value }
      }
    }
  }
}

fragment SuperSpineTemplateFields on TemplateDcimPhysicalDevice {
  id
  platform { node { id } }
  device_type { node { id } }
  interfaces(role__value: "downlink") {
    edges { node { name { value } } }
  }
}

fragment SiteLayoutFields on TopologySiteLayout {
  id
  name { value }
  rows { value }
  compute_racks_per_row { value }
  network_racks_per_row { value }
  rack_numbering_scheme { value }
  naming_convention { value }
}

fragment PodDesignFields on TopologyPodDesign {
  id
  name { value }
  deployment_type { value }
  spine_count { value }
  max_leafs_per_row { value }
  max_tors_per_row { value }
  technical_pool_size { value }
  loopback_pool_size { value }
  naming_convention { value }
  leaf_interface_sorting_method { value }
  spine_interface_sorting_method { value }
  loopback_prefix_size { value }
  p2p_prefix_size { value }
  management_prefix_size { value }
  spine_template { node { ...DeviceTemplateFields } }
}

fragment DataCenterFields on TopologyDataCenter {
  id
  devices(role__value: "super-spine") {
    edges { node { name { value } } }
  }
  name { value }
  index { value }
  amount_of_super_spines { value }
  fabric_interface_sorting_method { value }
  spine_interface_sorting_method { value }
  super_spine_template { node { ...SuperSpineTemplateFields } }
}

query topology_pod($name: String!) {
  TopologyPod(name__value: $name) {
    edges {
      node {
        id
        name { value }
        checksum { value }
        index { value }
        # New three-layer architecture
        site_layout { node { ...SiteLayoutFields } }
        design { node { ...PodDesignFields } }
        # Legacy attributes (for backward compatibility)
        deployment_type { value }
        amount_of_spines { value }
        leaf_interface_sorting_method { value }
        spine_interface_sorting_method { value }
        spine_template { node { ...DeviceTemplateFields } }
        loopback_pool { node { id name { value } } }
        prefix_pool { node { id name { value } } }
        spine_count: devices(role__value: "spine") {
          count
        }
        leaf_count: devices(role__value: "leaf") {
          count
        }
        tor_count: devices(role__value: "tor") {
          count
        }
        parent { node { ...DataCenterFields } }
      }
    }
  }
}
