fragment TemplateDeviceFields on TemplateDcimPhysicalDevice {
  platform {
    node {
      id
      name {
        value
      }
    }
  }
  device_type {
    node {
      id
    }
  }
  interfaces(role__value: "uplink") {
    edges {
      node {
        name {
          value
        }
        role {
          value
        }
      }
    }
  }
}

fragment FabricTemplateFields on TopologyElement {
  role {
    value
  }
  quantity {
    value
  }
  template {
    node {
      id
      ...TemplateDeviceFields
    }
  }
}

fragment SiteLayoutFields on TopologySiteLayout {
  id
  name { value }
  rows { value }
  compute_racks_per_row { value }
  network_racks_per_row { value }
  rack_numbering_scheme { value }
  naming_convention { value }
}

fragment PodDesignFields on TopologyPodDesign {
  id
  name { value }
  deployment_type { value }
  spine_count { value }
  max_leafs_per_row { value }
  max_tors_per_row { value }
  naming_convention { value }
  leaf_interface_sorting_method { value }
  spine_interface_sorting_method { value }
  spine_template {
    node {
      id
      interfaces(role__value: "downlink") {
        edges {
          node {
            name { value }
          }
        }
      }
    }
  }
}

fragment PodFields on TopologyPod {
  id
  name {
    value
  }
  index {
    value
  }
  # New three-layer architecture
  site_layout { node { ...SiteLayoutFields } }
  design { node { ...PodDesignFields } }
  # Legacy attributes (for backward compatibility)
  deployment_type {
    value
  }
  parent {
    node {
      ... on TopologyDataCenter {
        id
        name {
          value
        }
        index {
          value
        }
      }
    }
  }
  amount_of_spines {
    value
  }
  leaf_interface_sorting_method {
    value
  }
  spine_interface_sorting_method {
    value
  }
  loopback_pool {
    node {
      id
    }
  }
  prefix_pool {
    node {
      id
    }
  }
  spine_template {
    node {
      id
      interfaces(role__value: "downlink") {
        edges {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}

query RackGenerator($name: String) {
  LocationRack(name__value: $name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
        index {
          value
        }
        rack_type {
          value
        }
        checksum {
          value
        }
        row_index {
          value
        }
        parent {
          node {
            ... on LocationSuite {
              index {
                value
              }
            }
          }
        }
        leafs: fabric_templates(role__value: "leaf") {
          edges {
            node {
              ...FabricTemplateFields
            }
          }
        }
        tors: fabric_templates(role__value: "tor") {
          edges {
            node {
              ...FabricTemplateFields
            }
          }
        }
        pod {
          node {
            ...PodFields
          }
        }
      }
    }
  }
}
