query virtual_circuit_data($name: String!) {
  TopologyVirtualCircuit(name__value: $name) {
    edges {
      node {
        id
        name { value }
        link_type { value }
        transport_mode { value }
        vni { value }
        tunnel_id { value }
        interfaces {
          edges {
            node {
              id
              name { value }
              __typename
              device {
                node {
                  id
                  name { value }
                }
              }
            }
          }
        }
        physical_circuits {
          edges {
            node {
              id
              name { value }
              circuit_id { value }
              circuit_type { value }
              status { value }
              provider {
                node {
                  id
                  name { value }
                }
              }
            }
          }
        }
      }
    }
  }
}
