query vlan_segment_data($name: String!) {
  ManagedVlanSegment(name__value: $name) {
    edges {
      node {
        id
        name { value }
        deployment {
          node {
            id
            name { value }
          }
        }
        gateway { node { id address { value } } }
      }
    }
  }
}
