query vxlan_segment_data($name: String!) {
  ManagedVxlanSegment(name__value: $name) {
    edges {
      node {
        id
        name { value }
        stretch_scope { value }
        arp_suppression { value }
        terminate_inline { value }
        inline_service {
          node {
            id
            name { value }
            ... on ManagedHA {
              inline_vlan_id { value }
              inline_vlan_pool { node { id } }
            }
            ... on ManagedGenericDevice {
              capabilities {
                edges {
                  node {
                    id
                    __typename
                  }
                }
              }
            }
          }
        }
        customer_deployments {
          edges {
            node {
              id
              name { value }
              ... on TopologyCustomerDC {
                parent {
                  node {
                    id
                    name { value }
                    ... on TopologySegmentHosting {
                      vni_pool { node { id name { value } } }
                    }
                  }
                }
              }
              ... on TopologyCustomerColocation {
                parent {
                  node {
                    id
                    name { value }
                    ... on TopologySegmentHosting {
                      vni_pool { node { id name { value } } }
                    }
                  }
                }
              }
            }
          }
        }
        gateway { node { id address { value } } }
      }
    }
  }
}
