---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== ORGANIZATION =====================
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:factory"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:cloud-outline"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:account-group"

    # ===================== LOCATION =====================
    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mdi:map-marker"

    # ===================== DESIGN =====================
    # Design patterns, templates, and reusable elements
    - namespace: Design
      name: MainMenu
      label: Design
      icon: "mdi:pencil-ruler"
      children:
        data:
          # --------- Design & Planning ---------
          - namespace: Design
            name: DesignMenu
            label: Design & Planning
            icon: "mdi:pencil-ruler"
            children:
              data:
                - name: DataCenterDesign
                  namespace: Topology
                  label: Data Center Templates
                  kind: TopologyDataCenterDesign
                  icon: "mdi:vector-arrange-above"
                  description: "Data center design templates and patterns"

                - name: PopDesign
                  namespace: Topology
                  label: PoP Templates
                  kind: TopologyPopDesign
                  icon: "mdi:vector-arrange-above"
                  description: "PoP design templates and patterns"

                - name: BranchOfficeDesign
                  namespace: Topology
                  label: Branch Office Templates
                  kind: TopologyBranchOfficeDesign
                  icon: "mdi:vector-arrange-above"
                  description: "Branch office design templates and patterns"

          # --------- Design Elements ---------
          - namespace: Design
            name: ElementsMenu
            label: Design Elements
            icon: "mdi:cube-outline"
            children:
              data:
                - name: Element
                  namespace: Topology
                  label: Design Elements
                  kind: TopologyElement
                  icon: "mdi:cube-outline"
                  description: "Reusable design elements for infrastructure"

    # ===================== DEPLOYMENT =====================
    # Deployed infrastructure and topologies
    - namespace: Infrastructure
      name: MainMenu
      label: Deployment
      icon: "mdi:server-network"
      children:
        data:
          # --------- Data Centers ---------
          - name: DataCenter
            namespace: Topology
            label: Data Centers
            kind: TopologyDataCenter
            icon: "mdi:server-network"
            description: "Enterprise data center deployments"

          # --------- Colocation Centers ---------
          - name: ColocationCenter
            namespace: Topology
            label: Colocation Centers
            kind: TopologyColocationCenter
            icon: "mdi:office-building"
            description: "Third-party colocation facilities"

          # --------- Branch Offices ---------
          - name: BranchOffice
            namespace: Topology
            label: Branch Offices
            kind: TopologyBranchOffice
            icon: "mdi:office-building-outline"
            description: "Remote office deployments"

    # ===================== INVENTORY =====================
    # Physical and logical inventory management
    - namespace: Inventory
      name: MainMenu
      label: Inventory
      icon: "mdi:warehouse"
      children:
        data:
          # --------- Physical Inventory ---------
          - namespace: Dcim
            name: InventoryMenu
            label: Physical Inventory
            icon: "mdi:server-plus"
            description: "Hardware devices, interfaces, and modules"
            children:
              data:
                - namespace: Dcim
                  name: GenericDevice
                  label: Devices
                  kind: DcimGenericDevice
                  icon: "mdi:server"
                  description: "All physical and virtual devices"

                - name: Interface
                  namespace: Dcim
                  label: Interfaces
                  icon: "mdi:ethernet"
                  kind: DcimInterface
                  description: "Network and management interfaces"

                - name: GenericSFP
                  namespace: Dcim
                  label: SFP Modules
                  icon: "mdi:expansion-card"
                  kind: DcimGenericSFP
                  description: "Optical and network transceiver modules"

                - name: Cables
                  namespace: Dcim
                  label: Cabling & Connections
                  icon: "mdi:cable-data"
                  kind: DcimCable
                  description: "Cabling between devices"

          # --------- Device Catalog ---------
          - namespace: Dcim
            name: CatalogMenu
            label: Device Catalog
            icon: "mdi:package-variant-closed"
            description: "Device types and platform definitions"
            children:
              data:
                - namespace: Dcim
                  name: DeviceType
                  label: Device Types
                  kind: DcimDeviceType
                  icon: "mdi:package-variant"
                  description: "Device model definitions and specifications"

                - namespace: Dcim
                  name: Platform
                  label: Platforms
                  kind: DcimPlatform
                  icon: "mdi:chip"
                  description: "Operating system and firmware platforms"
    # Operational networking and connectivity management
    - namespace: Network
      name: MainMenu
      label: Network & Connectivity
      icon: "mdi:lan-connect"
      children:
        data:
          # --------- Network Services ---------
          - namespace: Service
            name: NetworkMenu
            label: Network Services
            icon: "mdi:lan"
            description: "Network segments, load balancers, and DNS/NTP"
            children:
              data:
                - namespace: Service
                  name: NetworkSegment
                  label: Network Segments
                  kind: ServiceNetworkSegment
                  icon: "mdi:lan"
                  description: "VLANs, VXLANs, and network overlays"

                - namespace: Service
                  name: Loadbalancer
                  label: Load Balancers
                  kind: ServiceVIP
                  icon: "carbon:floating-ip"
                  description: "Load balancers and virtual IPs"

                - namespace: Service
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "mdi:clock-outline"
                  description: "Time synchronization services"

                - namespace: Service
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"
                  description: "Domain name services"

          # --------- Routing Protocols ---------
          - namespace: Routing
            name: RoutingProtocolMenu
            label: Routing Protocols
            icon: "mdi:router-network"
            description: "BGP, OSPF, and PIM configuration"
            children:
              data:
                # BGP Management
                - namespace: Routing
                  name: BGPMenu
                  label: BGP Management
                  icon: "mdi:router-network"
                  children:
                    data:
                      - namespace: Routing
                        name: AutonomousSystem
                        label: Autonomous Systems
                        kind: RoutingAutonomousSystem
                        icon: "mdi:bank-circle-outline"
                        description: "BGP AS definitions"

                      - namespace: Routing
                        name: BGPService
                        label: BGP Services
                        kind: ServiceBGP
                        icon: "carbon:ibm-cloud-internet-services"
                        description: "BGP service instances"

                      - namespace: Routing
                        name: BGPPeerGroup
                        label: BGP Peer Groups
                        kind: RoutingBGPPeerGroup
                        icon: "mdi:view-grid-plus-outline"
                        description: "BGP peer group templates"

                      - namespace: Routing
                        name: BGPCommunity
                        label: BGP Communities
                        kind: RoutingBGPCommunity
                        icon: "mdi:tag-multiple"
                        description: "Community definitions and policies"

                # OSPF Management
                - namespace: Routing
                  name: OSPFMenu
                  label: OSPF Management
                  icon: "mdi:network-outline"
                  children:
                    data:
                      - namespace: Routing
                        name: OSPFArea
                        label: OSPF Areas
                        kind: RoutingOSPFArea
                        icon: "mdi:square-rounded-outline"
                        description: "OSPF area definitions"

                      - namespace: Routing
                        name: OSPFService
                        label: OSPF Services
                        kind: ServiceOSPF
                        icon: "carbon:ibm-cloud-internet-services"
                        description: "OSPF service instances"

                      - namespace: Routing
                        name: OSPFInterface
                        label: OSPF Interface Profiles
                        kind: RoutingOSPFInterface
                        icon: "mdi:shield-check"
                        description: "OSPF interface configurations"

                # PIM Management
                - namespace: Routing
                  name: PIMMenu
                  label: PIM Management
                  icon: "mdi:network-pos"
                  children:
                    data:
                      - namespace: Routing
                        name: PIMService
                        label: PIM Services
                        kind: ServicePIM
                        icon: "carbon:ibm-cloud-internet-services"
                        description: "PIM service instances"

                      - namespace: Routing
                        name: PIMInterface
                        label: PIM Interface Profiles
                        kind: RoutingPIMInterface
                        icon: "mdi:ethernet"
                        description: "PIM interface configurations"

          # --------- Peering & Sessions ---------
          - namespace: Service
            name: PeeringMenu
            label: Peering & Sessions
            icon: "mdi:handshake"
            description: "BGP and OSPF peering relationships"
            children:
              data:
                - namespace: Service
                  name: BGPPeering
                  label: BGP Peering Sessions
                  kind: ServiceBGPPeering
                  icon: "carbon:network-4-reference"
                  description: "BGP peer with internal and external networks"

                - namespace: Service
                  name: OSPFPeering
                  label: OSPF Peering Sessions
                  kind: ServiceOSPFPeering
                  icon: "carbon:network-4-reference"
                  description: "OSPF neighbor relationships"

                - namespace: Service
                  name: PeeringPolicy
                  label: Peering Policies
                  kind: ServicePeeringPolicy
                  icon: "carbon:policy"
                  description: "Policies and rules for peer relationships"

          # --------- Load Balancing ---------
          - namespace: Loadbalancing
            name: LBMenu
            label: Load Balancing
            icon: "carbon:load-balancer-global"
            description: "Health checks and backend servers"
            children:
              data:
                - namespace: Loadbalancing
                  name: HealthCheck
                  label: Health Checks
                  kind: LoadbalancerHealthCheck
                  icon: "tabler:checkup-list"
                  description: "Health check definitions and monitoring"

                - namespace: Loadbalancing
                  name: Servers
                  label: Backend Servers
                  kind: LoadbalancerServer
                  icon: "mdi:server-plus"
                  description: "Backend servers for load balancing"
