---
apiVersion: infrahub.app/v1
kind: Menu
spec:
  data:
    # ===================== ORGANIZATION =====================
    - namespace: Organization
      name: MainMenu
      label: Organization
      icon: "mdi:domain"
      kind: OrganizationGeneric
      children:
        data:
          - namespace: Organization
            name: Manufacturer
            label: Manufacturers
            kind: OrganizationManufacturer
            icon: "mdi:factory"

          - namespace: Organization
            name: Provider
            label: Providers
            kind: OrganizationProvider
            icon: "mdi:cloud-outline"

          - namespace: Organization
            name: Customer
            label: Customers
            kind: OrganizationCustomer
            icon: "mdi:account-group"
    # ===================== LOCATION =====================
    - namespace: Location
      name: Generic
      label: Location
      kind: LocationGeneric
      icon: "mdi:map-marker"
    # ===================== DESIGN =====================
    - namespace: Design
      name: MainMenu
      label: Design
      icon: "mdi:pencil-ruler"
      children:
        data:
          # --------- Design & Planning ---------
          - namespace: Design
            name: DesignMenu
            label: Templates & Designs
            icon: "mdi:pencil-ruler"
            children:
              data:
                - name: DataCenterDesign
                  namespace: Topology
                  label: Data Center Templates
                  kind: TopologyDataCenterDesign
                  icon: "mdi:vector-arrange-above"
                  description: "Data center design templates and patterns"

                - name: PopDesign
                  namespace: Topology
                  label: PoP Templates
                  kind: TopologyPopDesign
                  icon: "mdi:vector-arrange-above"
                  description: "PoP design templates and patterns"

                - name: BranchOfficeDesign
                  namespace: Topology
                  label: Branch Office Templates
                  kind: TopologyBranchOfficeDesign
                  icon: "mdi:vector-arrange-above"
                  description: "Branch office design templates and patterns"

                - name: VirtualFabricDesign
                  namespace: Topology
                  label: Virtual Fabric Templates
                  kind: TopologyVirtualFabricDesign
                  icon: "mdi:vector-arrange-above"
                  description: |
                    Virtual fabric design templates with resource limits

          # --------- Design Elements ---------
          - namespace: Design
            name: ElementsMenu
            label: Design Elements
            icon: "mdi:cube-outline"
            children:
              data:
                - name: Element
                  namespace: Topology
                  label: Design Elements
                  kind: TopologyElement
                  icon: "mdi:cube-outline"
                  description: "Reusable design elements for infrastructure"
    # ===================== DEPLOYMENT =====================
    - namespace: Infrastructure
      name: MainMenu
      label: Deployment
      icon: "mdi:server-network"
      children:
        data:
          # --------- Data Centers ---------
          - name: DataCenter
            namespace: Topology
            label: Data Centers
            kind: TopologyDataCenter
            icon: "mdi:office-building-outline"
            description: "Enterprise data center deployments"

          # --------- Colocation Centers ---------
          - name: Colocation
            namespace: Topology
            label: Colocation Centers
            kind: TopologyColocation
            icon: "mdi:server-network"
            description: "Third-party colocation facilities"

          # --------- Branch Offices ---------
          - name: BranchOffice
            namespace: Topology
            label: Branch Offices
            kind: TopologyBranchOffice
            icon: "mdi:office-building"
            description: "Remote office deployments"

          # --------- Public Clouds ---------
          - namespace: Topology
            name: Cloud
            label: Cloud Topology
            kind: TopologyCloud
            icon: "mdi:cloud"
            description: "Public cloud topology deployments"

          - name: VirtualisationMenu
            namespace: Service
            label: Customer Deployments
            icon: "mdi:cloud-outline"
            description: "Topology and Cloud customer deployments"
            children:
              data:
                # --------- Virtual Fabric Deployments ---------
                - name: VirtualFabricDeployment
                  namespace: Service
                  label: Virtual Data Centers
                  kind: ServiceVirtualFabricDeployment
                  icon: "carbon:ibm-cloud-internet-services"
                  description: "Customer virtual fabric deployments"

                - namespace: Service
                  name: VirtualCloud
                  label: Virtual Clouds
                  kind: ServiceVirtualCloud
                  icon: "carbon:ibm-cloud-internet-services"
                  description: "Customer virtual cloud deployments"
    # ===================== INVENTORY =====================
    - namespace: Inventory
      name: MainMenu
      label: Inventory
      icon: "mdi:warehouse"
      children:
        data:
          # --------- Device Inventory ---------
          - namespace: Dcim
            name: InventoryMenu
            label: Device Inventory
            icon: "mdi:server-plus"
            description: "Hardware devices, interfaces, and modules"
            children:
              data:
                - namespace: Dcim
                  name: GenericDevice
                  label: Devices
                  kind: DcimGenericDevice
                  icon: "mdi:server"
                  description: "All physical and virtual devices"

                - name: Interface
                  namespace: Dcim
                  label: Interfaces
                  icon: "mdi:ethernet"
                  kind: DcimInterface
                  description: "Network and management interfaces"

                - name: GenericSFP
                  namespace: Dcim
                  label: SFP Modules
                  icon: "mdi:expansion-card"
                  kind: DcimGenericSFP
                  description: "Optical and network transceiver modules"

                - name: Cables
                  namespace: Dcim
                  label: Cabling & Connections
                  icon: "mdi:cable-data"
                  kind: DcimCable
                  description: "Cabling between devices"
          # --------- Device Catalog ---------
          - namespace: Dcim
            name: CatalogMenu
            label: Device Catalog
            icon: "mdi:package-variant-closed"
            description: "Device types and platform definitions"
            children:
              data:
                - namespace: Dcim
                  name: DeviceType
                  label: Device Types
                  kind: DcimDeviceType
                  icon: "mdi:package-variant"
                  description: "Device model definitions and specifications"

                - namespace: Dcim
                  name: Platform
                  label: Platforms
                  kind: DcimPlatform
                  icon: "mdi:chip"
                  description: "Operating system and firmware platforms"
    # ===================== ROUTING =====================
    - namespace: Routing
      name: MainMenu
      label: Routing & Peering
      icon: "mdi:router"
      children:
        data:
          - namespace: Routing
            name: BGPMenu
            label: BGP Management
            icon: "mdi:router-network"
            children:
              data:
                - namespace: Routing
                  name: AutonomousSystem
                  label: Autonomous Systems
                  kind: RoutingAutonomousSystem
                  icon: "mdi:bank-circle-outline"
                  description: "BGP AS definitions"

                - namespace: Routing
                  name: BGPService
                  label: BGP Services
                  kind: ServiceBGP
                  icon: "carbon:ibm-cloud-internet-services"
                  description: "BGP service instances"

                - namespace: Routing
                  name: BGPPeerGroup
                  label: BGP Peer Groups
                  kind: RoutingBGPPeerGroup
                  icon: "mdi:view-grid-plus-outline"
                  description: "BGP peer group templates"

                - namespace: Routing
                  name: BGPCommunity
                  label: BGP Communities
                  kind: RoutingBGPCommunity
                  icon: "mdi:tag-multiple"
                  description: "Community definitions and policies"

                - namespace: Routing
                  name: BGPPeering
                  label: BGP Peering Sessions
                  kind: ServiceBGPPeering
                  icon: "carbon:network-4-reference"
                  description: "BGP peer with internal and external networks"

          # OSPF Management
          - namespace: Routing
            name: OSPFMenu
            label: OSPF Management
            icon: "mdi:network-outline"
            children:
              data:
                - namespace: Routing
                  name: OSPFArea
                  label: OSPF Areas
                  kind: RoutingOSPFArea
                  icon: "mdi:square-rounded-outline"
                  description: "OSPF area definitions"

                - namespace: Routing
                  name: OSPFService
                  label: OSPF Services
                  kind: ServiceOSPF
                  icon: "carbon:ibm-cloud-internet-services"
                  description: "OSPF service instances"

                - namespace: Routing
                  name: OSPFInterface
                  label: OSPF Interface Profiles
                  kind: RoutingOSPFInterface
                  icon: "mdi:shield-check"
                  description: "OSPF interface configurations"

                - namespace: Routing
                  name: OSPFPeering
                  label: OSPF Peering Sessions
                  kind: ServiceOSPFPeering
                  icon: "carbon:network-4-reference"
                  description: "OSPF neighbor relationships"

          # PIM Management
          - namespace: Routing
            name: PIMMenu
            label: PIM Management
            icon: "mdi:network-pos"
            children:
              data:
                - namespace: Routing
                  name: PIMService
                  label: PIM Services
                  kind: ServicePIM
                  icon: "carbon:ibm-cloud-internet-services"
                  description: "PIM service instances"

                - namespace: Routing
                  name: PIMInterface
                  label: PIM Interface Profiles
                  kind: RoutingPIMInterface
                  icon: "mdi:ethernet"
                  description: "PIM interface configurations"

                - namespace: Service
                  name: PeeringPolicy
                  label: Peering Policies
                  kind: ServicePeeringPolicy
                  icon: "carbon:policy"
                  description: "Policies and rules for peer relationships"
    # ===================== SERVICES =====================
    - namespace: Network
      name: MainMenu
      label: Services
      icon: "mdi:lan-connect"
      children:
        data:
          # --------- Network Services ---------
          - namespace: Service
            name: NetworkMenu
            label: Network Services
            icon: "mdi:lan"
            description: "Network segments, load balancers, and DNS/NTP"
            children:
              data:
                - namespace: Service
                  name: NetworkSegment
                  label: Network Segments
                  kind: ServiceNetworkSegment
                  icon: "mdi:lan"
                  description: "VLANs, VXLANs, and network overlays"

                - namespace: Service
                  name: NTPServer
                  label: NTP Servers
                  kind: NetworkNTPServer
                  icon: "mdi:clock-outline"
                  description: "Time synchronization services"

                - namespace: Service
                  name: NameServer
                  label: DNS Servers
                  kind: NetworkNameServer
                  icon: "mdi:dns"
                  description: "Domain name services"

          # --------- Load Balancing ---------
          - namespace: Loadbalancing
            name: LBMenu
            label: Load Balancing
            icon: "carbon:load-balancer-global"
            description: "Health checks and backend servers"
            children:
              data:
                - namespace: Service
                  name: Loadbalancer
                  label: Load Balancers
                  kind: ServiceVIP
                  icon: "carbon:floating-ip"
                  description: "Load balancers and virtual IPs"

                - namespace: Loadbalancing
                  name: HealthCheck
                  label: Health Checks
                  kind: LoadbalancerHealthCheck
                  icon: "tabler:checkup-list"
                  description: "Health check definitions and monitoring"

                - namespace: Loadbalancing
                  name: Servers
                  label: Backend Servers
                  kind: LoadbalancerServer
                  icon: "mdi:server-plus"
                  description: "Backend servers for load balancing"
